README.md
Updating readme telemetry section to note that data is collected only when using release builds and not when using private builds. Please refer to privacy.md for the link to detailed privacy statement. The release build telemetry is covered by Windows 10 privacy -  https://support.microsoft.com/en-us/help/4468236/diagnostics-feedback-and-privacy-in-windows-10-microsoft-privacy
=> Updating readme telemetry section

doc/ManifestSpecv0.1.md
=> Fix typo in ManifestSpecv0.1.md

doc/windows-package-manager-v1-roadmap.md
The use of HTML for bullet points broke the links embedded in the document. This pull request fixes that and a spelling error.
=> Fix markdown links in the roadmap

README.md
This ensures that the link works even on machines which doesn't have access to the Microsoft Store via the browser.
=> Point to the Microsoft Store website link

README.md
=> Updating readme to include instructions to opt out of telemetry.

src/AppInstallerCLICore/TableOutput.h, src/AppInstallerCLITests/Strings.cpp, src/AppInstallerCommonCore/AppInstallerStrings.cpp, src/AppInstallerCommonCore/Public/AppInstallerStrings.h
This PR suggests a fix for #268. The problem is that `std::string::length()` is used in `TableOutput` to determine the length of table cell values. Since `std::string` is not UTF8-aware, it returns the number of bytes, not characters. The two are different if the string contains special characters.
This fix adds a `Utility::UTF8Length` method to obtain the number of characters of a UTF8 string, and uses it in `TableOutput` to compute the display length of cell values.
=> Fix misalignment of table output for multi-byte chars (#268)

doc/windows-package-manager-v1-roadmap.md
First of all, apologies if this should be an issue first, but would rather open a pr to show what I mean. 
A lot of roadmaps and timelines use seasons as targets which I personally really dislike. Seasons aren't the same throughout the world and so it can be a bit confusing for people in the southern hemisphere (like myself) and we normally just have to assume northern. This change also aligns with some of the things highlighted in the code of conduct . https://opensource.microsoft.com/codeofconduct/
This may seem super minor and petty but I do think that it should honestly just be standard to go by either actual months, or even better quarters. (I prefer quarters but that is slightly different to seasons.) I also think we should be more exclusive in general of people throughout the …
=> Change "Spring" to "March-May" to be more explicit

doc/specs/#292 - winget should install an app if there is an exact match.md, doc/specs/spec-template.md
Add a place in the template to include a link to the issue, as it is somewhat onerous to have to find the issue oneself from the id alone.
Why wasn't my "# 292" (added a space because I don't actually want to reference it) turned into a link to the issue in this md file?  Does that only work in PRs and Issues themselves, but not in standalone markdown? ... Looked it up myself, and files don't get the short links:
https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls
```
Note: Autolinked references are not created in wikis or files in a repository.
```
=> Update spec template and spec to include link

src/AppInstallerCLIPackage/AppInstallerCLIPackage.wapproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
If there are spaces in a folder anywhere between the root directory and the project directory, builds will fail when copying files.
This patch puts quotes around the parameters for the copy commands in the project files.
=> Fix build errors if there are spaces in an ancestor folder

src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLITests/PreIndexedPackageSource.cpp, src/AppInstallerCLITests/Settings.cpp, src/AppInstallerCLITests/Sources.cpp, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj.filters, src/AppInstallerCommonCore/FileLogger.cpp, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Public/winget/Settings.h, src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerCommonCore/Settings.cpp, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/pch.h
As groundwork for #396 , we need a way to differentiate settings streams.  This change adds an enum that allows us to do just that.
The GetPathTo* functions were all collapsed into a single one that uses and enum to select the desired path.  This enables new paths to be added more easily, which should lead to each one being semantically meaningful, rather than potentially muddied.
The settings code was moved to its own files, and a new enum added to enable differentiation of semantics.  The existing paths are called 'Standard', while the new path is called 'UserFile'.  These new streams are intended to be user editable files, and so always use files instead of containers.
The settings code was also coalesced under an interface internally, making the call site much cleaner, and the code …
=> Enable differentiation of settings streams

doc/specs/#396 - Settings command.md
=> Settings Command Spec

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
Moving command line args logging to local file log instead of telemetry.
=> Moving command line args logging to local file log

doc/specs/#364 - Feature Toggle.md
Add  setting property proposal to spec #364
=> Feature toggle setting

src/AppInstallerCLICore/Commands/SettingsCommand.cpp, src/AppInstallerCommonCore/UserSettings.cpp
Add logs to have more information about the settings such as from where it got loaded and the values to failures parsing the file or validating values.
Validated by running scenarios and looking at the logs.
=> Add logging to user settings

src/AppInstallerCLICore/TableOutput.h, src/AppInstallerCLITests/Strings.cpp
#446 Fixed the issue where change file encoding from Windows-1252 to UTF-8 (with BOM).
=> Fix #446: Save some file to UTF-8 (with BOM) encoding.

src/AppInstallerCLIE2ETests/ShowCommand.cs
These tests were using the default search mechanism, and thus were at the whims of outside forces.  This change forces them to use the source configured in the tests.
The tests.
=> Always use the configured source for show E2E tests

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToOneTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToOneTable.h
Resolves #252 
Makes version and channel case insensitive for lookups from the user.  They already were required to be case insensitive unique, so this shouldn't have any effect other than making use easier.
Causes an index modification (add / update) to overwrite the existing Id value with the incoming one if the casing is different.  So last writer wins on Id casing.  Other fields can have distinct casing per manifest revision for now, but since Id needs to be the thing that ties them together, it needs to be a single value.
Added unit tests that verify both behaviors.
=> Case insensitivity improvements

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
#139 Fixed the issue where winget has incorrect capitalization in --help.
=> Fixed incorrect capitalization for en-us

src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerCommonCore/pch.h
For #464 
Injects the current user SID into the secure settings path to enable multiple users to have independent settings streams.
Existing tests.
=> Add user specific directory for secure settings

src/WinGetUtil/WinGetUtil.vcxproj
Delay load these binaries as they are not needed for every function.  This enables those util functions that do not need them to be used on older versions of Windows.
=> Delay load SQLite and ICU binaries in util dll

src/AppInstallerCLICore/Commands/SearchCommand.cpp, src/AppInstallerCLICore/Commands/ShowCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h, src/AppInstallerCLIE2ETests/SearchCommand.cs, src/AppInstallerCLIE2ETests/ShowCommand.cs, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Errors.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface.cpp, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySearch.h, src/AppInstallerRepositoryCore/RepositorySource.cpp
For #292 
This changes show and install to use case insensitive equality on id, name or moniker as the default query behavior.  So ```winget show git``` now returns ```Git.Git``` as it matches on both name and moniker.  The filters can still be used to target specific fields, but they too will require case insensitive equality rather than substring.  The best way to target a specific package will be to use ```--id```, as the command ```winget install --id foo.bar``` should now always find the package ```foo.bar```, or nothing. (For reference, show and install use the same algorithm to find the package to operate on.)
```
PS C:\git\pkgs\Tools> wingetdev search git
Name                                    Id                                       Version      Match …
```
=> Change show and install to use a narrower search

src/IndexCreationTool/Program.cs, src/IndexCreationTool/WinGetUtilWrapper.cs
Update IndexCreationTool code to use the updated WinGet* names
No product code is affected with this change.
Used updated code to generate an index successfully.
=> Update IndexCreationTool to align with the renamed WinGet*

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/Sources.cpp, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj.filters, src/AppInstallerRepositoryCore/AggregatedSource.cpp, src/AppInstallerRepositoryCore/AggregatedSource.h, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySearch.h, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/pch.h
This is part 2 of #117
- Added support to search across multiple sources
- Added store source as one of the default sources if experimental feature is enabled
- Fixed a minor bug where removing a source will always restore default sources
- Existing tests passed
- Added new tests to test multiple source search
- Manually tested the test msstore source and community source work together
=> Search across multiple sources and add msstore source

doc/Settings.md, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/pch.h, src/AppInstallerCommonCore/pch.h, src/AppInstallerRepositoryCore/RepositorySource.cpp
This is part 3 of #117
- Added a preindexed Microsoft Store source as default source is feature is enabled
- A minor fix to make Store app install failure message align correctly
- Updates settings doc with Experimental Store feature
- Fixed compilation failure after upgraded to VS ver 16.7.2
- Existing tests(including Store flow) passed
- Manually searching and installing a Store app succeeded
=> Add preindexed Microsoft Store source 

doc/windows-package-manager-v1-roadmap.md
There was a milestone missing (the /milestone/22 one) and because of that, the links were redirecting to the wrong milestone.
=> Put milestones in the right order

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/Manifest-Bad-InvalidManifestVersionValue.yaml, src/AppInstallerCLITests/TestData/Manifest-Bad-PackageFamilyNameOnMSI.yaml, src/AppInstallerCLITests/TestData/Manifest-Bad-ProductCodeOnMSIX.yaml, src/AppInstallerCLITests/TestData/Manifest-Good-SystemReferenceComplex.yaml, src/AppInstallerCLITests/TestData/Manifest-Good.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/Manifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestInstaller.cpp, src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp, src/AppInstallerCommonCore/Manifest/YamlParser.cpp, src/AppInstallerCommonCore/Public/AppInstallerVersions.h, src/AppInstallerCommonCore/Public/winget/Manifest.h, src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h, src/AppInstallerCommonCore/Public/winget/ManifestValidation.h, src/AppInstallerCommonCore/Public/winget/ManifestYamlParser.h, src/AppInstallerCommonCore/Versions.cpp
Adds the PackageFamilyName and ProductCode values to parsing by the manifest.  These can be at the root level, where they will be inherited.  They can also be provided per installer, but they must match the InstallerType or it will be an error.
Also makes major changes to the way the ManifestVersion is handled.  For now, the version is largely ignored (except it must be major version 0 if provided).  A concept of extensions is added, which are defined as the hyphen separated values after the primary version.  These can also be versioned, although the code does not exist to check it.  The syntax is:
```
ManifestVersion := Version (- Extension)
Extension := Version (- Extension)
```
where the Version portion of Extension is treated as `Name.Version`.  For instance, `1.0.0-extension` and …
=> Add system reference values to manifest parsing

src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.cpp, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySearch.h, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/pch.h
The expected interface definition for use by `list`, `update`, and `uninstall` commands.  This will allow others to make progress implementing these commands, but note that they are not themselves yet implemented.
The expected use is:
```
auto source = OpenPredefinedSource(PredefinedSource::Installed, progress);
auto results = source->Search(...);
if (results.Matches.empty()) { ... } // Found none
else if (results.Matches.size() == 1) { ... } // For targeting a single application
else
{
for (const auto& match : results.Matches) // For targeting all
{
if (match.IsUpdateAvailable())
{ ... } // An update is available
}
}
```
No functional changes should be observed.
=> Interface changes for list/update/uninstall

doc/specs/#164 - PWA Support.md, doc/specs/#194 - PWA Support.md
Added PWA support spec for community review
=> Added PWA support spec

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/ManifestTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToOneTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/PathPartTable.cpp, src/AppInstallerRepositoryCore/SQLiteStatementBuilder.cpp, src/AppInstallerRepositoryCore/SQLiteStatementBuilder.h
The previous change to create stand-alone indexes rather than primary keys, and subsequently drop more of them when packaging, exposed an issue with our database schema.  SQLite's implicit rowid is not guaranteed to be stable, especially across a `VACUUM`.  As the index was built around referencing other data by it's rowid, this lead to corrupted databases being created when manifests were removed or updated.
This change causes all relevant tables (every table except the map tables) to have an integer primary key column, which will prevent the rowid from changing, as it is now a data member.
A new test is added to ensure that rowid's do not change after a manifest removal and `VACUUM`. It failed prior to the fix being in place, and succeeds afterward.
=> Create integer primary keys in tables that need to be referenced

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface_1_0.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/ManifestTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/ManifestTable.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToManyTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToManyTable.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/PathPartTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/PathPartTable.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_1/Interface.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_1/Interface_1_1.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/ISQLiteIndex.h, src/AppInstallerRepositoryCore/SQLiteStatementBuilder.cpp, src/AppInstallerRepositoryCore/SQLiteStatementBuilder.h, src/WinGetUtil/Exports.cpp, src/WinGetUtil/WinGetUtil.h
To ensure at least a base level of consistency within the index, these functions ensure that all referenced rows actually exist.  Failures are logged out if requested.  More extensive checks can be added as needed, although some form of cycle detection in the pathparts is the only thing that I can foresee without additional data being added.  The function is also exported via WinGetUtil.
A call is made in the recently added test for rowid migration, as well as adding a test that directly removes a row to ensure failure from the function.
=> Create consistency check functionality

azure-pipelines.yml, src/AppInstallerCLIE2ETests/TestCommon.cs
Minor Change:
Revised the path used to publish E2E Test Logs from %LOCALAPPDATA%/E2ETestLogs --> %TEMP%/E2ETestLogs
Validation:
- Passes all azp tests
=> modified path for E2ETestLogs

src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCLICore/ExecutionContext.h, src/AppInstallerCLICore/Workflows/UpdateFlow.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Manifest/YamlParser.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
- Move the reporting of IsManifestLocal upfront to filter out some noises
- Added execution stage info when failures or exceptions occur.
- Add sub execution telemetry support (for upgrade --all)
This should not change the client behavior. Also manually validated basic install and search.
=> Telemetry reporting improvements

doc/settings.schema.json
Booleans in JSON are not quoted; remove the quotes as such.  VS Code now properly autofills a boolean rather than a string on tab completion.
While it isn't actually true, we could also change the default value for the experimental features to `true` to cause the tab completion (in VS Code at least) to fill in with the value that one likely wants in that case.
=> Remove quotes from booleans

azure-pipelines.yml, src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp, src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/FileLogger.cpp, src/AppInstallerCommonCore/Public/AppInstallerFileLogger.h, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Runtime.cpp
Moves the default log location for installer logs to be the same as the location for `winget` logs, which on a default install is:
```
%LOCALAPPDATA%\Packages\WinGetDevCLI_8wekyb3d8bbwe\LocalState\DiagOutputDir
```
This will allow reports through [Feedback Hub](https://aka.ms/winget-feedback) to gather those logs to better help us diagnose issues with specific installers.
Additionally, `winget --info` will now also show this log location.
=> Move the default location for installer logs

src/AppInstallerCLICore/Workflows/CompletionFlow.cpp, src/AppInstallerCommonCore/AppInstallerStrings.cpp, src/AppInstallerCommonCore/Public/AppInstallerStrings.h, src/AppInstallerCommonCore/Versions.cpp, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/RepositorySource.cpp
Revert the change that I made previously to use ICU case folding for all case insensitive comparisons, and instead use it only when both sides are user defined.  If one side is a known value (given that these will be ASCII), then a simple ToLower will work to determine equality.
=> Only use ICU folding when needed

src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/ExecutionContext.h, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/Deployment.cpp, src/AppInstallerCommonCore/Public/AppInstallerDeployment.h, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp
- Use AddPackageAsync to bypass smart screen when adding or updating trusted source
- Use AddPackageAsync to bypass smart screen when deploying msix from trusted source
Modified unit test to also verify IsInstallerTrusted flag
=> Update Smart Screen experience for msix

src/WinGetUtil/Source.def
`WinGetSQLiteIndexCheckConsistency` was forgotten from the def file.
dumpbin shows the export now.
=> Add forgotten export to def file

src/AppInstallerCLICore/Commands/ListCommand.cpp, src/AppInstallerCLICore/Commands/SearchCommand.cpp, src/AppInstallerCLICore/Commands/ShowCommand.cpp, src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/ExecutionContext.h, src/AppInstallerCLICore/TableOutput.h, src/AppInstallerCLICore/Workflows/CompletionFlow.cpp, src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp, src/AppInstallerCLICore/Workflows/ShowFlow.cpp, src/AppInstallerCLICore/Workflows/UpdateFlow.cpp, src/AppInstallerCLICore/Workflows/UpdateFlow.h, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h, src/AppInstallerCLITests/Sources.cpp, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/Manifest/ManifestInstaller.cpp, src/AppInstallerRepositoryCore/RepositorySource.cpp
- Previously, upgrade flow assumes at least one available version is there for each search match from composite installed source. It's not the case. So in this change, all places calling GetLatestAvailableVersion() are examined and made sure there's proper null check.
- Fixed output spamming in upgrade --all case
- Fixed an issue where any user source operation will restore tombstoned default source
- Always log E_ABORT context termination to reduce noise
- Updated tests
- Manual validation and fix
=> Improve upgrade output experience

src/WinGetUtil/Exports.cpp, src/WinGetUtil/Source.def, src/WinGetUtil/WinGetUtil.h, src/WinGetUtil/WinGetUtil.vcxproj
Adding new export, WinGetCompareVersions, which compares two versions for ordering purposes. This allows other tools and services to be guaranteed the same version sorting when working with the OWC that WinGet uses.
=> Adding export to WinGetUtil.dll to expose Version comparing

.github/actions/spelling/expect.txt, src/AppInstallerCLITests/PredefinedInstalledSource.cpp, src/AppInstallerCLITests/Registry.cpp, src/AppInstallerCLITests/TestCommon.cpp, src/AppInstallerCLITests/TestCommon.h, src/AppInstallerCommonCore/Registry.cpp
Fixes #657 
The issue was due to a REG_SZ value containing a wide string with a narrow null terminator.  Move to using RegGetValue, as it ensures that a proper null character will always be at the end of a registry string value.
The provided registry hive was readable by the underlying list code, and a new test is added to ensure that this specific case works.
=> Fix registry reading code to allow for a single null byte on a wide string value

src/AppInstallerCLICore/ExecutionProgress.cpp
Otherwise the Spinner and Progress widgets merrily set the foreground colour but `TextFormat::Default` is never sent because the Reporter actually checks the VT setting!
Fixes #665
=> Ensure progress widgets respect UseVT

.github/actions/spelling/allow.txt, doc/windows-package-manager-v1-roadmap.md
=> spelling: strikethrough

src/AppInstallerCLICore/ChannelStreams.cpp, src/AppInstallerCLICore/ChannelStreams.h, src/AppInstallerCLIE2ETests/SourceCommand.cs, src/AppInstallerCLITests/Strings.cpp, src/AppInstallerCommonCore/Public/AppInstallerLogging.h, src/AppInstallerCommonCore/Public/winget/LocIndependent.h
When paths with non-ASCII characters are used, logging them is resulting in an exception due to not being able to convert them to ASCII (the default behavior when forced to convert to a narrow char).
To better handle all situations of output of a path, both the logging and reporting infrastructure have been enlightened to force the use of `u8String()` when they see one.
=> Force output paths to use u8string with filesystem::path

azure-pipelines.loc.yml
The pipeline task that submits files for localization requires an AAD app for auth. Updating the App Id to one owned by the team. Will update the secret key in the pipeline when merging.
=> Update AAD App ID used for localization

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/VTSupport.cpp, src/AppInstallerCLICore/VTSupport.h, src/AppInstallerCLICore/Workflows/ShowFlow.cpp
Adding VirtualTerminal TextFormat helper for making text a clickable link.
=> Add Hyperlink function to ViritualTerminal TextFormat namespace

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Commands/ExportCommand.h, src/AppInstallerCLICore/Commands/ImportCommand.h, src/AppInstallerCLIE2ETests/ImportCommand.cs, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
=> Split Import/Export experimental feature setting

schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json, schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json, src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/InstallFlowTest_NonZeroExitCode.yaml, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp, src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h, src/AppInstallerTestExeInstaller/main.cpp
Also added tests for custom installer success codes.
=> Support custom installer success exit codes

schemas/JSON/manifests/preview/manifest.0.1.0.json
Relaxed values match v1 manifest schema values.
=> Relax preview manifest switches length restriction

src/AppInstallerCLICore/ExecutionReporter.cpp, src/AppInstallerCLICore/ExecutionReporter.h
Progress bar style is not being respected for import (and I assume upgrade all). This is because when creating the sub-ExecutionContexts where each install is made we clone the Reporter without preserving its style. Added the style to the Reporter to preserve it when set and pass it along to the clone.
=> Respect visual style settings on import

src/AppInstallerCLICore/Workflows/UpdateFlow.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/UpdateFlowTest_Exe_2.yaml, src/AppInstallerCLITests/WorkFlow.cpp
Fixes part of #794 
The code to select latest applicable upgrade version did not stop after it found the latest applicable version. The fix is to add a break once it did.
Tried out the scenario described in #794 and confirmed winget installs latest after the fix.
Added unit tests.
=> Make upgrade command correctly select latest applicable version

src/AppInstallerRepositoryCore/Microsoft/Schema/1_2/Interface_1_2.cpp
If a manifest has multiple localizations defined, and if the PackageName or Publisher values are duplicated across different localizations, the wingetutil indexing will fail with SQLITE_CONSTRAINT_UNIQUE.
=> Fix failure in indexing for duplicate PackageName or Publisher values

schemas/JSON/manifests/preview/manifest.0.1.0.json, schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json, schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json, schemas/JSON/manifests/v1.0.0/manifest.locale.1.0.0.json, schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json, src/AppInstallerCLITests/TestData/InstallFlowTest_NonZeroExitCode.yaml, src/AppInstallerCommonCore/Manifest/YamlParser.cpp, src/AppInstallerCommonCore/Public/winget/ManifestValidation.h
Previously the manifest input validation code does not check required fields existence before using them to determine manifest consistency. This will result in unhelpful error message saying "Expected node type does not match". This change checks those fields before using them to give a better error message for winget validate commands.
Also removed the format uri restriction per Union's ask.
=> Better error message for manifest input validation errors

src/AppInstallerCommonCore/DateTime.cpp
I noticed during a presentation that the date format for the exported JSON files wasn't formatted correctly (the space just before the `3` for March instead of a `0`):
This pull request updates the formatting to ensure that the day and month are padded with zeroes like the time already is.
Generating an export JSON locally, I get something similar to the following before and after the change.
```json
{
"CreationDate" : "2021- 3-31 13:18:58.648"
}
```
```json
{
"CreationDate" : "2021-03-31 13:17:55.408"
}
```
There's a test that the date is output below, but it doesn't validate anything beyond it being present. As the clock isn't injectable in some way, I wasn't sure on the best way to add a test for it that would verify the format was always correct, rather than just on days that should …
=> Fix date formatting

src/AppInstallerCLICore/PackageCollection.cpp, src/AppInstallerCLITests/PackageCollection.cpp, src/AppInstallerCommonCore/DateTime.cpp
This is a follow up to #836 
CreationDate in the package collection JSON schema is declared as a date-time but the file we generated when exporting didn't follow the requirements for the format. This wasn't a problem because valijson does not validate this format, so we would not reject it, and we don't need to because we don't use the field. Ensuring we use the proper format probably only has the benefit of it not showing up as an error when editing or otherwise processing the file with a tool that validates the schema.
The date should follow the format specified by RFC 3339 according to the JSON schema. What I missed before was using T as a separator and adding the time zone offset at the end. I wasn't able to easily get the time zone offset in the right format, so instead I'm adding …
=> Fix format of CreationDate on export

src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/WorkflowGroupPolicy.cpp, src/AppInstallerCommonCore/Public/winget/GroupPolicy.h
Adding the sources configured by Group Policy to the output of --info with the other policies. This is something I missed doing in #841
=> Output sources from policy with --info

.github/actions/spelling/allow.txt, src/AppInstallerCLI.sln, src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj, src/AppInstallerCLIE2ETests/Constants.cs, src/AppInstallerCLIE2ETests/GroupPolicy.cs, src/AppInstallerCLIE2ETests/GroupPolicyHelper.cs, src/AppInstallerCLIE2ETests/ImportCommand.cs, src/AppInstallerCommonCore/ExperimentalFeature.cpp
Adding E2E tests for Group Policy. These tests read the ADMX to get the registry key path and the value names, and use that to set the policy. This ensures that the client code matches what the policy definition says.
The changes include a helper for reading the ADMX and set the policy, and tests that use the helper to set the policy and validate that the client respects it.
Note that running these tests will edit (and remove) the registry keys controlling the policy in the machine. Although this should be temporary if there is any actual GP set.
Also in this change:
* Updated version used of Microsoft.Msix.Utils. Only difference is that it targets .NET Standard instead of .NET Framework, so it doesn't produce a warning when building.
* Renamed some error codes in tests for consistency.
=> Add Group Policy E2E tests

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/ExecutionProgress.cpp, src/AppInstallerCLICore/ExecutionProgress.h, src/AppInstallerCLICore/VTSupport.cpp, src/AppInstallerCLICore/VTSupport.h
This implements #869: if VT is enabled, OSC 9;4 sequences are printed in addition to the existing progress spinner and progress bar.
Whenever an indefinite spinner is printed, a corresponding OSC sequence with state "Indeterminate" is output. When the spinner is hidden, an OSC sequence to clear the progress is written. Analogously, OSC sequences for showing/updating/hiding determinate progress are printed.
I noticed that the implementation of the progress OSC sequences in Windows Terminal does not exactly match the implementation in ConEmu. In particular, ConEmu allows the progress value to be left out (e.g. to switch progress states without having to specify the current progress value again) but Windows Terminal does not recognize these sequences at the moment. It is not really an issue …
=> Implement VT-based progress reporting

src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp
Fixes part of #752
The default msi upgrade parameter we have works only on very specific minor version upgrade, and these parameter s are mostly for advanced user to control file over file installation. In common scenario msi upgrade/installation, direct invocation on the msi should be enough.
=> Remove incorrect msi upgrade parameter

doc/Settings.md
Correct the documentation on what happens when running `winget settings` without a configured default Json editor in Windows to match what actually happens.
Fixes #916 
-----
=> Correct doc'd behaviour for `winget settings`

src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp
-----
This avoids the blank line after short and long descriptions in `winget show` when the manifest uses the
```yaml
Description: >
REAPER is a complete...
REAPER supports...
```
syntax for multi-line values. See e.g. https://github.com/microsoft/winget-pkgs/blob/master/manifests/c/Cockos/REAPER/6.28/Cockos.REAPER.locale.en-US.yaml and the output of `winget show reaper`:
```
Gefunden REAPER [Cockos.REAPER]
Version: 6.28
Publisher: Cockos Incorporated
Description: REAPER is a complete digital audio production application for computers, offering a full  multitrack audio and MIDI recording, editing, processing, mixing and mastering toolset.
REAPER supports a vast range of hardware, digital formats and plugins, and can be comprehensively extended, scripted and modified.
Homepage: …
```
=> Trim ShortDescription and Description manifest fields

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Resources.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCommonCore/DODownloader.cpp, src/AppInstallerCommonCore/DODownloader.h, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerCommonCore/Public/AppInstallerDownloader.h
In response to a comment after the PR was merged, update the Delivery Optimization download code to be able to set the DisplayName property.  We always set it to `Windows Package Manager`.
As part of this, I changed the way this metadata flows in to make it easier to add more to this optional data in the future.
Confirmed that the display name was making it into DO by checking the logs using `> Get-DeliveryOptimizationLog | Set-Content doLogs.txt`
=> Make additional metadata for downloads more extensible and add display name

src/AppInstallerCLITests/CompositeSource.cpp, src/AppInstallerCLITests/TestSource.cpp, src/AppInstallerCommonCore/Public/winget/LocIndependent.h, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/CompositeSource.h, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_2/Interface.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_2/Interface_1_2.cpp, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySearch.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/Rest/RestSource.cpp, src/AppInstallerRepositoryCore/Rest/RestSource.h
This change leverages the normalized name and publisher to increase the number of packages that can be matched.  It also reworks the way the the correlation occurs internally, albeit only slightly.
All operations that rely on this data should now work better; this includes `import`, `list`, `upgrade`, and `uninstall`.
The existing tests cover a lot of the scenarios, and a test is added to ensure that we do in fact send the name and publisher along in the search.  In large part though, actually matching based on this data is a source responsibility.
=> Name an Publisher correlation in CompositeSource

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, src/AppInstallerCLICore/ExecutionReporter.cpp, src/AppInstallerCLICore/VTSupport.cpp, src/AppInstallerCLICore/VTSupport.h, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h, src/AppInstallerCLITests/Strings.cpp, src/AppInstallerCommonCore/AppInstallerStrings.cpp, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Public/AppInstallerStrings.h, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h, src/AppInstallerCommonCore/Registry.cpp, src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerRepositoryCore/Microsoft/ARPHelper.cpp
Fixes #723 and #728 , as well as an issue with what is displayed when multiple matches are found (add source) and anonymizes the error messages that can end up in telemetry.  Specifically, sometimes file paths are included in an STL exception message so we are replacing instances of the `%USERPROFILE%` path with that literal value.
=> Fix a few polish items

src/AppInstallerCLICore/Commands/ExportCommand.h, src/AppInstallerCLICore/Commands/ListCommand.h, src/AppInstallerCLICore/Commands/UninstallCommand.h, src/AppInstallerCLICore/Commands/UpgradeCommand.h, src/AppInstallerCLIE2ETests/FeaturesCommand.cs, src/AppInstallerCLIE2ETests/ImportCommand.cs, src/AppInstallerCLIE2ETests/ListCommand.cs, src/AppInstallerCLIE2ETests/UninstallCommand.cs, src/AppInstallerCLITests/Downloader.cpp, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/AppInstallerRepositoryCore/RepositorySource.cpp
Make `list`, `upgrade`, `uninstall`, and `export` commands no longer experimental.  Also make the REST source implementation not experimental, as well as making Delivery Optimization the default downloader.
=> Make a lot of experimental things release

src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLITests/main.cpp, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/binver/binver/version.h
Fixes a few crashes that were happening, increase the default DO timeout for no progress to 60 seconds, and bump the minor version for the previous command releases.
Force the telemetry event code to run by changing the global value to true.  This will cause more code to be exercised by the existing tests.
=> Fixes for a few crashes, change DO timeout to 60 seconds default, update version that I forgot

azure-pipelines.yml
Fix for build break caused by NuGet/Home#7796 now appearing in VS 16.10.  The only thing I found that worked was to manually restore each project that failed due to a missing project.assets.json in the pipeline after restoring the solution itself.
=> Fix nuget restore due to ADO build agents moving to VS 16.10

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/SourceFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/Synchronization.cpp, src/AppInstallerCLITests/TestSource.cpp, src/AppInstallerCLITests/TestSource.h, src/AppInstallerCommonCore/Public/AppInstallerSynchronization.h, src/AppInstallerCommonCore/Synchronization.cpp, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp, src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/Rest/RestSourceFactory.cpp, src/AppInstallerRepositoryCore/SourceFactory.h
The previous implementation (using a semaphore) was not resilient to unexpected process termination, as Windows does not track semaphore ownership.  This could lead to a deadlock in a waiting process, and at least one user even experienced an ongoing deadlock despite having killed all of the active processes (which should have destroyed and thus reset the named semaphore).
This version uses a set of named mutexes instead, which Windows will release for us in the event of abandonment.  As part of the change I have also added the ability to pass in an `IProgressCallback` to allow for cancellation of the wait.
On top of that change, I realized the the source management functions were not properly indicating that they were cancelled.  While a CTRL+C in the middle of a `source add` would in …
=> Make CrossProcessReaderWriteLock resilient to process termination

.github/actions/spelling/expect.txt, src/AppInstallerRepositoryCore/SQLiteWrapper.cpp
Despite likely being the default, there is no documentation to prove that winsqlite3.dll was compiled this way.  So always pass the flag to force full serialization of calls to the connection.
Existing tests.
=> Force connection serialization

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/DODownloader.cpp, src/AppInstallerCommonCore/DODownloader.h, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
Resolves #1060 and resolves #1076 (well, mitigates really but that isn't a verb that GitHub responds to).
There have been several issues caused by DO being disabled by policy, or failing to redirect properly.  Due to this, and to prevent other issues from impacting users, we will fall back to the WinINet download code path when DO fails.
Some error codes are intentionally excluded from falling back, largely those pertaining to metered networks.  We will add more cases as we find them.
=> Fall back to WinINet if DO download fails

src/AppInstallerCommonCore/Runtime.cpp
Fixes #189 , and maybe others with strange permissions errors.
Move the temp directory that is used from the package specific temp to the user's temp location.  This should prevent the Mandatory Low ACL that was apparently causing #189 from being inherited.  While this is more avoiding the problem than fixing it, given the relatively low rate of occurrence it might be hard to ensure that it was truly fixed by actually changing the ACLs (and would require much more time and code to write).
Additionally changes the behavior of `Runtime::GetPathTo` to delete non-directories when they are encountered rather than just erroring directly.
Manually validated that installers are downloaded to the new location; do not have a repro of #189 to try against, but given the root cause it is unlikely that …
=> Move Temp path to the user's location

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/ExecutionContext.h, src/AppInstallerCLICore/Workflows/ImportExportFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/UpdateFlow.cpp, src/Microsoft.Management.Deployment/PackageManager.cpp
Related to #1009 , fixes one of the problems but there are many listed.
Update the CTRL signal handler to be able to fan out to multiple contexts, and make all cases of using sub-contexts both connected to the signal handler and better handle cancellation.
Additionally, improve the COM API install method to properly cancel any in progress task rather than just terminating the context.
Manually ensured that CTRL+C cancels various multi-step commands.
=> Make CTRL signal able to take multiple contexts

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json
Added the "doProgressTimeoutInSeconds'' setting which is used to setup minimum, maximum timeout period for the progress bar.
- [x ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
-----
=> Added "doProgressTimeoutInSeconds" Setting

src/AppInstallerCLICore/Commands/HashCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/UninstallFlow.cpp, src/AppInstallerCLICore/pch.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/Deployment.cpp, src/AppInstallerCommonCore/Public/AppInstallerDeployment.h, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp, src/AppInstallerRepositoryCore/pch.h
Prior to this change, MSIX install (and upgrade) would forcibly shut down the application so that it could upgrade the package during the command.  After, the new package will be staged and the upgrade will complete when the application is restarted.
This is done by first attempting `RequestAddPackageAsync` if SmartScreen is necessary.  Then if it that fails due to the package being in use (or it is not needed at all), we stage (place files onto the machine) then register (install package for user).  If the package is in use at this point, we detect it and change the success message to indicate that the user must restart the application:
```
Successfully installed. Restart the application to complete the upgrade.
```
Manual validation of both SmartScreen and non-SmartScreen paths. …
=> Add deferred registration for MSIX

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLIE2ETests/FeaturesCommand.cs, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/WinGetServer/WinMain.cpp
Remove the experimental feature flag for the COM API.  In the future we will likely add new flags for each update to the API surface to place the new functionality behind.
=> Remove the packagedAPI experimental feature flag

.github/actions/spelling/expect.txt, src/AppInstallerCommonCore/Architecture.cpp
Support for x64 emulation on ARM64 was [added to Windows 10 Dev builds last year](https://blogs.windows.com/windows-insider/2020/12/10/introducing-x64-emulation-in-preview-for-windows-10-on-arm-pcs-to-the-windows-insider-program/).  In order for us to detect the presence of that support, a new API was needed.
This change fixes #666 by implementing dynamic loading of the API and invoking it specifically for x64 when the machine is ARM64.  The API can replace our current use of `IsWow64GuestMachineSupported`, but there is no need to take the additional risk of that change at this time.
As we do not have any automated test bed for ARM64, I was only able to test it manually on a local device.
=> Support for x64 on ARM64

.github/actions/spelling/allow.txt, doc/troubleshooting/README.md
-----
- Added the errors from CMD and PS that users can encounter in the troubleshooting guide for winget.
- Updated possible troubleshooting steps to resolve the issue.
=> Update winget trouble shooting steps 

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/SourceFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerRepositoryCore/Rest/RestSourceFactory.cpp
* Show source identifier when doing `source list <name>`. This can be useful for creating json files for import.
* Get the source identifier when adding a REST source to ensure it is added to the sources yaml. We were getting it only when opening the source so it wouldn't get saved and could not show it with source list. Existing sources are not updated.
=> Show source identifier with `source list`

src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters, src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Argument.h, src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Commands/SettingsCommand.cpp, src/AppInstallerCLICore/Commands/SettingsCommand.h, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/SettingsFlow.cpp, src/AppInstallerCLICore/Workflows/SettingsFlow.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/AdminSettings.cpp, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj.filters, src/AppInstallerCommonCore/Public/winget/AdminSettings.h, src/AppInstallerCommonCore/Public/winget/Settings.h
Due to security concerns, this change disables local manifest files by default. User can still turn on local manifest files through group policy, or through running 'winget settings --enable LocalManifestFiles' as administrator.
Added tests. Also tested manually.
=> Disable local manifest by default

src/Microsoft.Management.Deployment/PackageManager.cpp
-----
There is currently no way to remove the callbacks from the context which means the callbacks can continue to be fired after the cancel has caused the coroutine to return if the coroutine does not wait for the context to finish. This triggers a crash. In the packageManagement case, it always waits for the context to finish, but in the packageQuery case it tried to optimize that away. It would be best to eventually figure out how to bring the quicker cancel back, so I'll file a bug, but for now removing that optimization so that it no longer fails is the first priority. Cancel in the packageQuery case will now also wait until the context is finished. The operation will be marked as status == Cancelled, even though it may have still run to completion (either successfully or with an …
=> Remove cancel optimization for packageQuery caller

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt
I've seen a few issues mentioned by the spell checker. I'm attempting to clean some of those issues up with this PR.
-----
=> Minor tweaks to spelling to fix issues

src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
This makes `list` show the correlated source of the latest available package even when no upgrade is available.  This makes it easier to see when packages are correlating properly via list, rather than needing to be an expert and/or inspect the local system to see how the output compares.
Before:
```
> winget list
Name                                     Id                                       Version             Available Source
-----------------------------------------------------------------------------------------------------------------------
reSearch                                 84f93aee594a430d                         2.2106.10.0
AppInstallerCaller                       8b5526fe-0870-42b7-bde0-da8c4c7ea1aa_kw… 1.0.7.0
CodeFlow                                 CodeFlow_is1 …
```
=> Make list show correlated source even when no upgrade is available

src/AppInstallerRepositoryCore/Rest/RestSource.cpp
If a REST source returns a single version that is `Unknown`, look up all versions when the manifest is requested.
Unfortunately I moved the code around due to the implementation and this looks like a lot more change than it is.  Things I actually changed are:
1. Fold `PackageBase` into `AvailablePackage` as there are no other derived types.
2. Made `PackageVersion` hold a `std::shared_ptr<AvailablePackage>` rather than the info.
3. Put lock around access to package versions data in `AvailablePackage`.
4. Added method and calls to update versions in this case.
The update is triggered by a `GetManifest` call that meets the criteria (version is `Unknown` and manifest is missing).  When we see that, and the version info in the package is consistent, we perform an optimized search that should …
=> Handle single unknown version from REST source

src/AppInstallerCommonCore/JsonSchemaValidation.cpp, src/AppInstallerCommonCore/MsixInfo.cpp, src/AppInstallerRepositoryCore/Microsoft/ConfigurableTestSourceFactory.cpp
=> Fix debug build failure

src/AppInstallerCommonCore/AppInstallerLogging.cpp, src/AppInstallerCommonCore/FileLogger.cpp, src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp, src/AppInstallerCommonCore/Public/AppInstallerFileLogger.h, src/AppInstallerCommonCore/Public/AppInstallerLogging.h, src/AppInstallerCommonCore/Public/winget/TraceLogger.h, src/AppInstallerCommonCore/TraceLogger.cpp, src/AppInstallerRepositoryCore/Rest/Schema/HttpClientHelper.cpp
Fixes a few debuggability issues with REST installers.
1. Wait for full HTTP response before logging it
2. Output duplicate installer info to make finding it easier
=> Fix logging of large REST response

src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/Commands/FeaturesCommand.cpp, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/GroupPolicy.cpp, src/AppInstallerCommonCore/Settings.cpp, src/AppInstallerCommonCore/UserSettings.cpp
Create the ability to disable experimental features in the build.  Also causes the `features` command to inform the user.
Also made the default logs a bit less verbose around settings because I was tired of seeing that all the time.
=> Create machinery for disabling experimental features

src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerCommonCore/Public/AppInstallerDownloader.h
This fixes the "winget downloaded installers do not honor url zone settings" issue brought up in #797
IAttachmentExecute::Save() api does not clear existing Motw if the url is in trusted zone. This change puts the downloaded file in a clean state before calling the IAttachmentExecute::Save() method.
Manually set break points and inspect Motw values are as expected and url zone settings are honored.
=> Remove motw before calling IAttachmentExecute::Save

src/AppInstallerCLICore/Workflows/ImportExportFlow.cpp, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp
Update the name of the `SupportCorrelation` field to better reflect the intention and correct the use to not allow available source searching when installed only semantics are being used.
Intentionally does allow available/all package searching to correlate against local packages to enable `import` to detect when packages are already present.  Also updates `import` to work better with the REST optimized search path.
=> Fix correlation issue

src/AppInstallerCLICore/Commands/SourceCommand.cpp, src/AppInstallerCLIE2ETests/BaseCommand.cs
Use the current set of experimentals in the tests.
Fix a bug that would cause the "Done" string to be output in certain cases where the `source add` failed (requiring elevation for instance).
=> Minor bug fixes

.github/actions/spelling/allow.txt, doc/troubleshooting/README.md
-----
- Updated troubleshooting.md with error 0x80070490 information and possible solution found by the community. 
- Issue link: https://github.com/microsoft/winget-pkgs/issues/25765
=> Update troubleshooting doc with recent error and findings

src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Per recommendation of the internal localization team, the product name should be localized.
=> Localize the product name per recommendation

src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Runtime.cpp
We already had a single retry after a 250ms wait for our `rename` of the installer to make it shell actionable with the correct extension.  This change makes it try every 100ms for 500ms, then use `copy_file` with a hard link option as a fall back.
The hard link is better than a true copy, as it won't take up more space.  But it won't get cleaned up on a successful install either.
Long term we should put in some background cleanup to remove old installers that were abandoned due to failures.
=> Make rename retry more frequently for longer, then try making a hardlink

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/ExecutionContext.h, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/GroupPolicy.cpp
Fixes to allow building with `AICLI_DISABLE_TEST_HOOKS` defined.  Specifically:
1. Exclude some function definitions whose declarations were already excluded.
2. Refactor `Context::ShouldExecuteWorkflowTask` to not be virtual as any virtual function or member field being inside `AICLI_DISABLE_TEST_HOOKS` could lead to an ODR violation if not all projects properly apply it.
=> Disable test hooks fixes

src/AppInstallerCommonCore/Manifest/Manifest.cpp
If the default localization is good enough, then exit the locale choice loop even if we do not find a better localization choice.
=> Exit the locale choice loop if the default localization is good enough

src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h, src/AppInstallerRepositoryCore/CompositeSource.cpp
When searching for installed packages matching an available package, if there were multiple matches we would create multiple results for the search. This caused commands that require a single match, like import or upgrade, to fail. Modified to select a single installed package as match if it has a strong match (product code or package family name).
This partially fixes #983 in that import and upgrade now won't fail for packages like Teams, but does not address the underlying issue of how we should deal with packages that have multiple ARP entries.
---
Also, modified dependencies code to check the experimental feature only once.
=> Ensure available packages match with a single installed package

src/AppInstallerCLICore/ExecutionContextData.h, src/AppInstallerCLICore/Workflows/ImportExportFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/UpdateFlow.cpp, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
-----
Issue:
- During import and upgrade flows, the sub execution id that was being used was not consistent for all events belonging to the same package as new ids were being generated in different phases.
Fix:
- This PR has changes that stores the sub execution id that was introduced for each package in search phase and re-uses it in the install phase, so that all events belonging to the same package have the same sub execution id.
Tests:
- Manually tested and verified the events sent for import and upgrade scenarios. Here are the sub exec ids used for upgrade events:
```
Console output when finding the package:
Upgrade App name: Microsoft.VisualStudio.2019.Enterprise Sub exec id: 2
Upgrade App name: Microsoft.WingetCreate Sub exec id: 55
Upgrade App name: Microsoft.Teams Sub exec id: 81 …
```
=> Use correct Subexecution id when working on multiple packages

.github/actions/spelling/allow.txt, tools/SampleWinGetUWPCaller/AppInstallerCaller/App.cpp, tools/SampleWinGetUWPCaller/AppInstallerCaller/App.h, tools/SampleWinGetUWPCaller/AppInstallerCaller/App.xaml, tools/SampleWinGetUWPCaller/AppInstallerCaller/AppInstallerCaller.vcxproj.filters, tools/SampleWinGetUWPCaller/AppInstallerCaller/InstallingPackageView.cpp, tools/SampleWinGetUWPCaller/AppInstallerCaller/InstallingPackageView.h, tools/SampleWinGetUWPCaller/AppInstallerCaller/MainPage.cpp, tools/SampleWinGetUWPCaller/AppInstallerCaller/MainPage.h, tools/SampleWinGetUWPCaller/AppInstallerCaller/MainPage.idl, tools/SampleWinGetUWPCaller/AppInstallerCaller/MainPage.xaml, tools/SampleWinGetUWPCaller/AppInstallerCaller/Package.appxmanifest, tools/SampleWinGetUWPCaller/AppInstallerCaller/pch.cpp, tools/SampleWinGetUWPCaller/AppInstallerCaller/pch.h
Some miscellaneous improvements for the sample COM caller project:
* Added some help labels and status messages to the UI
* Changed toggle button for using WinGetDev  to a toggle switch
* Rearranged UI elements in screen to separate elements visually and prevent them from jumping around when resizing
* Set window size to get rid of all the unneeded whitespace
* Set some global UI styles to reduce styling on individual controls
* Deleted some unused code and renamed some things to be more consistent
* Added needed capability to app manifest
* Added copyright headers to files
=> Changes for sample COM caller project

src/AppInstallerCLICore/Workflows/InstallFlow.cpp
-----
I noticed that in the latest build, the package name wouldn't print during `winget upgrade` (well, it'd print with the agreements portion, but it would not print after that when the package was actually being installed) :
I figured it was easy enough to fix myself, and it was! `package.PackageVersion->GetManifest())` was being used where `package.Manifest` should've been used (so that the locale info would be available).
Look at it now:
Let me know if there are any issues!
=> Fixed bug where the package name wouldn't be written during upgrade.

src/AppInstallerCLITests/WorkFlow.cpp
Fix test context to always use the task overrides, not only after cloning the context.
=> Fix test task overrides

src/AppInstallerCLITests/CustomHeader.cpp, src/AppInstallerCLITests/Run-TestsInPackage.ps1, src/AppInstallerCLITests/TestRestRequestHandler.cpp, src/AppInstallerCLITests/main.cpp
This fixes:
- REST tests that were deadlocking due to not setting the response body in the test helpers.
- The `-logto` unit test argument to now properly be the actual log path again.
- The test script to fail on timeout rather than simply ending.
=> Fix unit tests in pipeline

schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json, schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json, schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json, schemas/JSON/manifests/v1.1.0/manifest.singleton.1.1.0.json
Resolves an issue where the installer success codes for some manifests were larger than the range of an int datatype, which can cause issues for winget-create's model as it is expecting a valid int. 
https://github.com/microsoft/winget-create/issues/155
Changes the integer format to long in the v1.0 and v1.1 schema to increase the range of values.
Verification:
- Passes all unit tests
=> Change format to long for installer success codes

.github/actions/spelling/allow.txt, src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/SearchRequestSerializer_1_0.cpp, src/AppInstallerRepositoryCore/Rest/Schema/1_1/Interface.h, src/AppInstallerRepositoryCore/Rest/Schema/1_1/RestInterface_1_1.cpp
The names used in PackageMatchFields in rest spec is different from the default names in winget code, so we have to create a separate method to convert PackageMatchFields in rest client.
=> Fix incorrect processing of PackageMatchFields in rest client

src/Microsoft.Management.Deployment.Client/Client.CreateCompositePackageCatalogOptions.h, src/Microsoft.Management.Deployment.Client/Client.FindPackagesOptions.h, src/Microsoft.Management.Deployment.Client/Client.InstallOptions.h, src/Microsoft.Management.Deployment.Client/Client.PackageMatchFilter.h
-----
Client dll change only, no effect on the packaged winget server. Due to this bug Microsoft.Management.Deployment.Client dll users would receive interface cast failure when using the non-PackageManager classes.
=> Fix interface casting in client dll.

src/AppInstallerCLICore/Workflows/UpdateFlow.cpp, src/AppInstallerCLITests/WorkFlow.cpp
Check duplicates before adding to package install list in winget upgrade all.
Added tests.
=> Prevent duplicate installations in winget upgrade all

src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/UninstallFlow.cpp, src/AppInstallerCLITests/CompositeSource.cpp, src/AppInstallerCLITests/PackageTrackingCatalog.cpp, src/AppInstallerCLITests/TestSource.cpp, src/AppInstallerCLITests/TestSource.h, src/AppInstallerCLITests/main.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/CompositeSource.h, src/AppInstallerRepositoryCore/ISource.h, src/AppInstallerRepositoryCore/PackageTrackingCatalog.cpp, src/AppInstallerRepositoryCore/PackageTrackingCatalogSourceFactory.h, src/AppInstallerRepositoryCore/Public/winget/PackageTrackingCatalog.h, src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/SourceFactory.h
This change leverages the tracking data that is stored per source to correlate installed packages to available packages.  This will currently provide no additional benefit with the `winget` source, as we aren't doing the work yet to determine the best fit system artifact when none of our current correlation attempts succeed.  It will help the `msstore` source to correlate as that is currently lacking in support to search system references.
Existing regression tests and new tests added for the tracking catalog.  Modified the tracking catalog to enable the existing test infrastructure to inject custom data.
=> Use package tracking data to correlate in CompositeSource

src/Microsoft.Management.Deployment/Converters.cpp, src/Microsoft.Management.Deployment/Helpers.cpp, src/Microsoft.Management.Deployment/PackageManager.idl, tools/SampleWinGetUWPCaller/AppInstallerCaller/Package.appxmanifest
Add `ProductCode` and `PackageFamilyName` values to enum to enable the existing search capabilities through COM.
Also updates the sample caller to have the `packageQuery` capability as I found that it did not during some manual testing.
Manual update to sample app to try it out.
=> Add product code and PFN to enable existing searches

src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
-----
Related to #906.
This PR adds a option, `--architecture`, to `winget install`. This option allows the user to (you guessed it) tell winget what architecture they want to install. If the architecture isn't available, winget does the same thing it would do if there wasn't a installer entry for the user's platform (No applicable installer error). The user is only allowed to provide architectures their system can run (if they ask for arm64 on x64, a `CommandException` is thrown). 
This may have implications for upgrades (I'm not 100% sure on whether upgrade checks the architecture of the currently installed version. If it doesn't, winget might upgrade a 32-bit version to a 64-bit version even if the user didn't want that). If it breaks too much stuff I can close this.
Tested: manually. …
=> Added an option to select architecture to install.

.github/actions/spelling/expect.txt, schemas/JSON/packages/packages.schema.2.0.json, src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Runtime.cpp, src/binver/binver/version.h
Adds the ability for determining release/preview status at build time.  This is then used to change the client version and product name that we output in help.
Also bumped the client version to 1.2 as this is appropriate for preview.
```
> wingetdev
Windows Package Manager (Preview) v1.2.2-preview
Copyright (c) Microsoft Corporation. All rights reserved.
> wingetdev -v
v1.2.2-preview
```
=> Add preview concept to allow build time determination

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h, src/AppInstallerCommonCore/Public/winget/ThreadGlobals.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/ThreadGlobals.cpp, src/AppInstallerCommonCore/TraceLogger.cpp, src/AppInstallerCommonCore/UserSettings.cpp, src/WinGetUtil/Exports.cpp
Currently there is a potential circular dependency between the telemetry object and the logger object due to the need to open settings to finish telemetry construction.
=> Prevent circular dependency in global telemetry logger creation

src/AppInstallerCommonCore/Public/AppInstallerLogging.h
Use SFINAE to stop any `std::filesystem::path` from using the generic template function and force them to use the function that outputs the `u8string` instead.  This allows the non-const method to be deleted.
Verified that the recently added `std::optional<std::filesystem::path>::value_or` call is appropriately going to the `path` function.
=> Use SFINAE to stop paths from logging without using u8string

schemas/JSON/settings/settings.schema.0.2.json
remove "plain" as documentation does not show it, and is a invalid settings option in winget, removal as it's a non-functional option and would benefit confused text editor users to match the options shown in the documentation and available settings in the actual winget.
This proposal can be canceled if the implementation of "plain" is planed further down the road.
- [Y ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [N ] Are you working against an Issue?
-----
"Are you working against an issue?" No issue has been filed for this, in fact the fix might be a little bit premature as it was filed _before_ a issue.
=> remove plain

src/AppInstallerCLICore/ChannelStreams.cpp, src/AppInstallerCLICore/ChannelStreams.h, src/AppInstallerCLICore/ExecutionReporter.cpp, src/AppInstallerCLICore/ExecutionReporter.h
Move the VT state ownership fully into `BaseStream`, where it already really lived.  The bool in `ExecutionReporter` was not being initialized before use and could result in VT being disabled-ish (based on memory state going in), so this fixes that issue.
=> Make VT enablement/disablement work properly

src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters, src/AppInstallerCLICore/Workflows/DownloadFlow.cpp, src/AppInstallerCLITests/Strings.cpp, src/AppInstallerCommonCore/AppInstallerStrings.cpp, src/AppInstallerCommonCore/Public/AppInstallerStrings.h
Change the installer download file from:
```
%TEMP%\WinGet\<ID>.<Version>.<Installer Extension>
```
to
```
%TEMP%\WinGet\<ID>.<Version>\<Installer URL File Stem>.<Installer Extension>
```
Example:
```
"%TEMP%\WinGet\Notepad++.Notepad++.8.1.9.1.exe"
```
becomes
```
"%TEMP%\WinGet\Notepad++.Notepad++.8.1.9.1\npp.8.1.9.1.Installer.x64.exe"
```
In addition, this change uses:
```
%TEMP%\WinGet\<ID>.<Version>\<Installer SHA256 hash>
```
as the name of the file before hash validation.  This prevents the potential for any user input to create an executable file name since the SHA256 hash must be a hexadecimal string.
Existing regression tests and manual runs to ensure consistency for golden path.
=> Change download file name to match the installer URL

src/AppInstallerCLI/AppInstallerCLI.vcxproj, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/Workflows/ImportExportFlow.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/NameNormalization.cpp, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerTestExeInstaller/AppInstallerTestExeInstaller.vcxproj, src/JsonCppLib/JsonCppLib.vcxproj, src/Microsoft.Management.Deployment.Client/Microsoft.Management.Deployment.Client.vcxproj, src/Microsoft.Management.Deployment.Server.Test/Microsoft.Management.Deployment.Server.Test.vcxproj, src/Microsoft.Management.Deployment/Microsoft.Management.Deployment.vcxproj, src/WinGetServer/WinGetServer.vcxproj, src/WinGetUtil/WinGetUtil.vcxproj, src/WinGetYamlFuzzing/WinGetYamlFuzzing.vcxproj, src/WindowsPackageManager/WindowsPackageManager.vcxproj, src/YamlCppLib/YamlCppLib.vcxproj, src/cpprestsdk/cpprestsdk.vcxproj, tools/SampleWinGetUWPCaller/AppInstallerCaller/AppInstallerCaller.vcxproj
-----
This PR ended up being way bigger than I thought it would be, but in general, it makes the necessary changes for winget to build using Visual Studio 2022's toolchain (MSVC v143). 
Here's what I did:
- Changed all of the project files to conditionally use the v143 compiler if you're using Visual Studio 2022 (same way that v142 was conditionally used for many of the project files for 2019).
- ~~Updated Valijson to version 0.6. This is the vast majority of the changes, and maybe should be a separate PR (up to y'all). The reason for this is that Valijson made a change to their CMake configuration [here](https://github.com/tristanpenman/valijson/commit/cb778b6bb60d609a18a0ebc48c79e8ee6d4bd92d#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) to allow it to work …
=> Updated solution to build under Visual Studio 2022

.github/actions/spelling/allow.txt, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
There's been feedback item filed claiming the source agreement market message is not clear enough so making explicit that we are sending the geographic region info to the source's backend server.
=> Update source agreement market message to be more clear

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
-----
Resolves #906.
This is the other half of #906, adding settings to select a preferred or required architecture. The required architecture behaves exactly like the `--architecture` flag, where `AllowedArchitectures` only contains the architecture that is in the setting. The preferred architecture behaves much like the preferred scope setting, where the installer entry with the preferred architecture is selected over all others, but if there isn't an installer entry with the preferred architecture, the normal rationale is used.
The fields are validated by determining if the architecture selected is compatible with the current system. By default the setting is set to `neutral`. (although if there is a reason we need to allow users to require neutral manifests, that could just as easily …
=> Added settings to select preferred/required architecture.

src/AppInstallerCLITests/PackageTrackingCatalog.cpp, src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/DependenciesTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/Interface_1_4.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/ISQLiteIndex.h, src/AppInstallerRepositoryCore/PackageTrackingCatalog.cpp
**PackageTrackingCatalog**:
When dependency nodes are not found in the index, an attempt to add or update manifest by the catalog tracking feature causes a failure. In some scenarios this might be valid as the dependencies of a package might already be present in the user's machine. This fix totally disable dependencies for catalog tracking feature by adding an option to not create dependencies table and also checking for the presence of the table when there is an attempt to perform any operation on the table.  
**SQLiteIndexUpdate**:
Bug in dependencies udpate manifest causes the method to always return true even if the index wasn't modified. This pull request fixes the issue, and also extends the update manifest tests to capture 1_4 schema update.
=> Bug fix: PackageTrackingCatalog and SQLiteIndexUpdate

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj
* Updated dependency of WingetUtilInterop.UnitTests on Microsoft.Msix.Utils to version 2.0.3. The version previously used (1.0.*) targeted .NET Framework and caused a build warning as that project uses .NET Core. Updated version targets .NET Standard and does cause the same warning.
* Fixed outstanding spellchecking warning about "archs".
* Rearranged some items in the tests' project file to follow alphabetical order, and moved the multifile manifest v1_1 test data to its own filter.
=> Fix some build warnings

src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLITests/ManifestComparator.cpp
Adding support for `UnsupportedOSArchitectures` manifest entry by extending `MachineArchitectureComparator` to add a check that the system architecture is not listed as unsupported.
Closes #993
=> Add support for UnsupportedOSArchitectures manifest element

src/AppInstallerCLICore/Workflows/DownloadFlow.cpp
-----
Resolves #1808.
This PR adds a check to GetInstallerPostHashValidationFileName that ensures that the filename in the URL does not exceed 260 characters (the maximum ~~path size~~ file name size in Windows). If it does, then the "older" naming style (`manifest.version.ext`) is used for the downloaded file. Technically this could still fail if the full length of the path is 260 instead of just the file name, but I thought that was fairly unlikely. If it isn't I can adjust for that too.
Tested: manually via the manifest given in the issue. As always, I'm happy to add tests if needed.
Edit: corrected explanation, thanks.
=> Added check for maximum size of downloaded file names

src/AppInstallerCLI.sln, src/AppInstallerCommonCore/Architecture.cpp
Load and call `IsWow64GuestMachineSupported()` dynamically only if it is available, instead of calling it directly. This prevents a DLL load error when running on RS1, as happens on the Azure Functions of the service.
This is based on the existing pattern to call `GetMachineTypeAttributes()`.
=> Fix DLL load error in WinGetUtil

src/AppInstallerCLICore/Workflows/DependenciesFlow.cpp
-----
Small change to make sure that the "Installing Dependencies: " string only prints if there are actually dependencies installing. The way it was, if all of the dependencies were already installed it looked like the package the user requested *was* a dependency.
```
PS C:\Users\easton> wingetdev install handbrake
Found HandBrake [HandBrake.HandBrake] Version 1.5.1
This package requires the following dependencies:
- Packages
Microsoft.dotnetRuntime.5-x64
Downloading https://github.com/HandBrake/HandBrake/releases/download/1.5.1/HandBrake-1.5.1-x86_64-Win_GUI.exe
██████████████████████████████  19.4 MB / 19.4 MB
Successfully verified installer hash …
```
=> Moved "Installing Dependencies" message to only print if there are dependencies to install.

doc/troubleshooting/README.md
Was the solution to #1840. With thanks to @ItzLevvie
-----
Apologies for my conduct on the ticket. It looks like I'd been working around this PATH entry missing with a few windows installer packages. No idea why it was not added.
=> Adds experiment to know if PATH is common issue.

schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json, schemas/JSON/manifests/v1.1.0/manifest.singleton.1.1.0.json
Changes:
- Adding a title description for ExpectedReturnCode and UnsupportedOSArchitecture so that WingetCreate can process those enum values when generating the model.
=> Add titles to 1.1 schema for ExpectedReturnCode and UnsupportedOSArchitecture

.github/actions/spelling/allow.txt, azure-pipelines.yml, src/AppInstallerCLICore/pch.h, src/AppInstallerCLIE2ETests/SetUpFixture.cs, src/PackagedTests/PackagedTests.csproj
This changes the CI build pipeline to build/test x86 and x64 in two separate parallel jobs.
On #1813 the build failed because the build machine was running out of space. We are using Microsoft Hosted agents for running the pipelines, which have only 10GB free space (according to docs; in practice it seems to be around 12GB). Upon investigation, building the solution was already taking about 9GB since we are building both x86 and x64 at the same time. Out of these, about 4GB were from pre-compiled headers; the biggest offender was the one for CommonCore, with over 800MB for each x86,x64.
I also considered trying to reduce the size of the pre-compiled headers or delete them after compilation (but didn't know how); or setting up a custom agent pool with more space (but setting it up and …
=> Split pipeline build job into x86 and x64

src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/UpdateFlowTest_Exe_ARPInstallerType.yaml, src/AppInstallerCLITests/WorkFlow.cpp
* Modified the applicability check in `InstalledTypeComparator` to also consider the installer types listed under `AppsAndFeaturesEntries`
* Extended string returned from `ExplainInapplicable` to also mention the installed type and other types accepted by the manifest.
Closes #1242. Validated that upgrading PowerToys (mentioned in that issue) worked correctly using a local manifest edited to include the `AppsAndFeaturesEntries` and installed type `msi`.
=> Allow upgrades in packages that register a different installer type

src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/UpdateFlow.cpp
-----
Resolves #1858.
This PR changes the `upgrade --all` flow to print the table of available upgrades before running the upgrades, giving the user a more friendly list of upgrades (as opposed to several lines of `Workflow::ReportManifestIdentityWithVersion`). 
I had to make a change to `EnsurePackageAgreementsAcceptanceForMultipleInstallers`, namely, that it now gets the manifest and checks to see if there are any agreements before printing anything. ~~This is less efficient if there is an agreement, but since most packages don't have agreements right now, it shouldn't (on average) change performance.~~ (Edit: this doesn't change performance really at all, see below).
I reused the upgrade table from `winget upgrade` for this too, if a different appearance would be better then I can make …
=> Print the upgrade table during `upgrade --all`

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerStrings.h
Previously on Watson...
These pointers can apparently be null, leading to a crash trying to read them.  So don't do that.
=> Fix crash that can occur when failure pointers are null

src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
-----
Resolves #1869.
This PR adds a extra validation for arguments in `winget upgrade`, making sure that arguments that require a package search (`--accept-package-agreements` for example) don't cause a empty package search to run.
Tested: manually.
=> Added extra check for valid arguments in `upgrade`.

src/binver/binver/version.h
Because I forgot to do it when we branched the 1.2 RC.
=> Bump version to 1.3

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCLITests/UserSettings.cpp, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
Resolves #1940
This is my first time really digging into the codebase, so I wouldn't be surprised if this is entirely incorrect.
This PR allows users to set their preferred logging level to any of the levels available with the default remaining `Info`. This preference is overridden by the use of `--verbose-logs`
Tested: Manually + Unit Tests
-----
=> Setting for Logging Level

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
-----
Here is how it was before:
```console
➜ winget upgrade
Nenhum pacote instalado foi encontrado que corresponda aos critérios de entrada.
10 packages have version numbers that cannot be determined. Use "--include-unknown" to see all results.
➜ winget upgrade --include-unknown
Nenhum pacote instalado foi encontrado que corresponda aos critérios de entrada.
```
The current message gives the impression that using `--include-unknown` could potentially show all the 10 packages mentioned, which is a mistake. In fact, it would only show packages who have candidates in the WinGet repo.
So, I'm addressing this with this PR.
But honestly, I would prefer that this was transparent to the user, i.e. not show any message at all about unknown packages.
Refs …
=> Improve `--include-unknown` message

src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/Architecture.cpp, src/AppInstallerCommonCore/Public/AppInstallerArchitecture.h
-----
Resolves https://github.com/microsoft/winget-cli/issues/1925 (yes, I know it was my issue. just had to leave myself a reminder :D)
This PR adds the system architecture to `winget --info`, cutting out the first question we usually ask when troubleshooting.
=> Added system architecture to `winget --info`.

src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
- Resolves #1939 
This also will only include packages which can be / have been disambiguated
cc @jedieaston
-----
=> Fix: Only include unknown packages which exist in source

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/Manifest-Good-PackageFamilyNameOnExe-Ver1_2.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp
To support nested installers, allow PackageFamilyName to be declared with non msix installers starting from manifest version 1.2
Added unit tests.
Validated manually install, upgrade and uninstall works correctly.
=> Allow PackageFamilyName to be declared with non msix installers

azure-pipelines.yml, src/AppInstallerCLITests/Strings.cpp
Currently unit test failure does not fail the pipeline because incorrect test result path is used in publish test results task. Fixing the path makes the pipeline checking results correctly.
=> Make build pipeline task fail on unit tests failure

src/AppInstallerCLICore/Workflows/UpdateFlow.cpp
-----
It turns out that this message is displayed twice, without a reason. Example:
```console
$ winget upgrade --all
Name  Id             Version Available Source
---------------------------------------------
gsudo gerardog.gsudo 1.0.2.0 1.1.0     winget
1 upgrades available.
10 packages have version numbers that cannot be determined. Use "--include-unknown" to see all results.
(1/1) Found gsudo [gerardog.gsudo] Version 1.1.0
Downloading https://github.com/gerardog/gsudo/releases/download/v1.1.0/gsudoSetup.msi
██████████████████████████████   364 KB /  364 KB
Successfully verified installer hash
Starting package install...
Successfully installed
10 …
```
=> Remove duplicated message about unknown versions

src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/Microsoft.Management.Deployment/PackageManager.idl, src/Microsoft.Management.Deployment/PackageVersionInfo.cpp, src/Microsoft.Management.Deployment/PackageVersionInfo.h
Exposes a simple check of applicable installer for install. This does not consider installed version during the check. To check against installed version for upgrade, we might want to expose something on the package level when asks come(enhanced version of IsUpgradeAvailable).
Manually verified the code works as expected.
=> Expose simple applicable installer check in Com api

src/AppInstallerCommonCore/Public/winget/Registry.h, src/AppInstallerRepositoryCore/SQLiteWrapper.h
-----
For some reason[^1], Visual Studio 2022's newest update (17.1.0) made source breaking changes to the C++ compiler. In two instances, these prevented winget from compiling. I believe @yao-msft was running into these issues in #1990, but here's the fix.
Basically, there was a conformance change to the compiler where if you had a `static_assert` that could be evaluated without knowing the type, then the compiler would always evaluate it to the same value. Many of the `static_assert` calls that were checking to see if a type had an override had to be made dependent on the type so the compiler wouldn't optimize the check away.
More reading here: https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=msvc-170#error-on-a-non-dependent-static_assert
[^1]: Most …
=> Fixed issues preventing compilation on VS 2022 17.1.

doc/admx/DesktopAppInstaller.admx, doc/admx/en-US/DesktopAppInstaller.adml
Adding a group policy definition for ms-appinstaller to the ADMX/ADML.
This is not directly related to winget, but to App Installer. Adding here as the same policy definition is used for both.
=> Add policy definition for ms-appinstaller to ADMX

.github/actions/spelling/allow.txt, src/AppInstallerCLIE2ETests/SourceCommand.cs, src/AppInstallerCLITests/Sources.cpp, src/AppInstallerRepositoryCore/SourceList.cpp
Update to our new official DNS name.
=> Change to official DNS

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
* #2033
```raw
PS > wingetdev  -?
Windows Package Manager (Preview) v1.3.2-preview
Copyright (c) Microsoft Corporation. All rights reserved.
The winget command line utility enables installing applications and other packages from the command line.
usage: winget [<command>] [<options>]
The following commands are available:
install    Installs the given package
show       Shows information about a package
source     Manage sources of packages
search     Find and show basic info of packages
list       Display installed packages
upgrade    Shows and performs available upgrades
uninstall  Uninstalls the given package
hash       Helper to hash installer files
validate   Validates a manifest file
settings   Open settings or set administrator settings
features   Shows the status of experimental …
```
=> Make upgrade help inform of list ability

src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.cpp
Fixes #2016 
(Really, mitigates, but github likes fixes)
A crash is showing up in the installed version of the installed package being null.  While this doesn't make sense, bugs don't have to!  We need a live debug repro (or time travel trace) to get to the bottom of this, so for now we will just do our best to log details and skip the offending package.  This is better than a crash for the user, but could lead to whatever is causing it to be missing in results.  Reports of that will potentially lead us to the culprit, if it isn't a system state issue.
=> Mitigate crash occuring in CompositeSource

src/AppInstallerCLI.sln, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_2/Interface_1_2.cpp
Places the values from the `AppsAndFeaturesEntries` into the index, and uses them in the post-install ARP entry detection.
Added a test to ensure that the values were added and searched in a simple case.
=> Use AppsAndFeatures name and publisher

Localization/Policies/de-DE/DesktopAppInstaller.adml, Localization/Policies/es-ES/DesktopAppInstaller.adml, Localization/Policies/fr-FR/DesktopAppInstaller.adml, Localization/Policies/it-IT/DesktopAppInstaller.adml, Localization/Policies/ja-JP/DesktopAppInstaller.adml, Localization/Policies/ko-KR/DesktopAppInstaller.adml, Localization/Policies/pt-BR/DesktopAppInstaller.adml, Localization/Policies/ru-RU/DesktopAppInstaller.adml, Localization/Policies/zh-CN/DesktopAppInstaller.adml, Localization/Policies/zh-TW/DesktopAppInstaller.adml, Localization/Resources/de-DE/winget.resw, Localization/Resources/es-ES/winget.resw, Localization/Resources/fr-FR/winget.resw, Localization/Resources/it-IT/winget.resw, Localization/Resources/ja-JP/winget.resw, Localization/Resources/ko-KR/winget.resw, Localization/Resources/pt-BR/winget.resw, Localization/Resources/ru-RU/winget.resw, Localization/Resources/zh-CN/winget.resw, Localization/Resources/zh-TW/winget.resw
This patch has 100% of the localizations for the strings up to commit 0f4d66e122d38a775c189c37d03aaabd74f8c36f.
This includes the changes from #1846 and the localizations for the updated ADML in #2038. The patch also removed the outdated localizations for the strings changed in #2034, which we should get next time we run the pipeline as they were already submitted.
=> Apply latest loc patch

src/AppInstallerCLICore/ExecutionProgress.cpp, src/AppInstallerCLICore/ExecutionProgress.h, src/AppInstallerCLICore/VTSupport.cpp, src/AppInstallerCLICore/VTSupport.h
-----
This enhances the progress bar to use more fine-grained blocks, in steps of 1/8 of the width of a block, by leveraging the [Block Element](https://www.fileformat.info/info/unicode/block/block_elements/list.htm) Unicode characters.
E.g. before:
After:
=> Display fine-grained blocks in progress bars

.github/actions/spelling/allow.txt, doc/specs/#182 - Support for installation of portable standalone apps.md
The changes in this PR add specifications regarding the usage of symlinks to support installing portable apps. This is a change from our initial design which originally wrote to the "App Paths" registry as a means of registering/installing portable apps. However, this was determined to be insufficient as this would not support execution from the command prompt.
=> Update portable spec with symlink solution design

.github/actions/spelling/expect.txt, azure-pipelines.nuget.yml, azure-pipelines.yml, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerCommonCore/UserSettings.cpp, src/Microsoft.Management.Deployment.Client/Client.PackageManagerSettings.h, src/Microsoft.Management.Deployment.Client/Microsoft.Management.Deployment.Client.vcxproj, src/Microsoft.Management.Deployment.Client/PackageManagerSettings.cpp, src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.dll.manifest, src/Microsoft.Management.Deployment/ComClsids.cpp, src/Microsoft.Management.Deployment/Microsoft.Management.Deployment.vcxproj, src/Microsoft.Management.Deployment/Microsoft.Management.Deployment.vcxproj.filters, src/Microsoft.Management.Deployment/PackageManager.cpp, src/Microsoft.Management.Deployment/PackageManager.h, src/Microsoft.Management.Deployment/PackageManager.idl, src/Microsoft.Management.Deployment/PackageManagerSettings.cpp, src/Microsoft.Management.Deployment/PackageManagerSettings.h, src/Microsoft.Management.Deployment/PackageVersionInfo.cpp, src/Microsoft.Management.Deployment/PackageVersionInfo.h, src/Microsoft.Management.Deployment/Public/ComClsids.h, src/Microsoft.Management.Deployment/pch.h, src/WinGetServer/WinMain.cpp, src/WindowsPackageManager/main.cpp
Added a process global PackageManagerSettings Com object to support better state separation for in-proc Com invocations.
Also make the package applicability check take in InstallOptions to give better results.
Added back unpackaged tests run under system context.
Manually tried calling the PackageManagerSettings and see logs, etc are saved under state specific folder.
Next is the Com e2e test.
=> Add support for in-proc Com state separation

src/AppInstallerCLICore/Workflows/InstallFlow.cpp
Fixes #1442
Wrap the subexecution with a try/catch to prevent exceptions from breaking out of the mult-package install loop.
=> Fix exceptions breaking out of the multi-package install loop

tools/PowerShell/Microsoft.WinGet.Client/src/Library/Install-WinGetPackage.ps1, tools/PowerShell/Microsoft.WinGet.Client/src/Microsoft.WinGet.Client.psd1
-----
This PR enables all cmdlets in the module and makes Install-WinGetPackage actually work. There may be other stuff wrong with the other cmdlets but I didn't test the other ones thoroughly.
=> fix passing null parameters to Find-WinGetPackage

src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp
- Resolves #1585 
-----
- Updates comment when `enr.Status() == GetEntitlementStatus::NoStoreAccount` to indicate it is okay to not have a store account.
- Updates the return statement of `GetFreeUserEntitlement` to return true if `enr.Status() == GetEntitlementStatus::NoStoreAccount`
=> Allow winget to install MS Store packages without account

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Argument.h, src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/Commands/SearchCommand.cpp, src/AppInstallerCLICore/Commands/SearchCommand.h, src/AppInstallerCLICore/Commands/ShowCommand.cpp, src/AppInstallerCLICore/Commands/ShowCommand.h, src/AppInstallerCLICore/Commands/UninstallCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIE2ETests/GroupPolicy.cs, src/AppInstallerCLIE2ETests/SearchCommand.cs, src/AppInstallerCLIE2ETests/ShowCommand.cs, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Fixes #1131 
For `install`, `show`, `search`, and `uninstall` commands, require that one of the selection arguments be provided.  These are (where appropriate per command):
```
-q, --query [default positional argument]
-m, --manifest
--id
--name
--moniker
--tag
--command
```
I intentionally did not provide a way to override this behavior (like an `--all` for `search`), because I don't see a good use case for it.  If there is one, please explain it below.
=> Require selection argument on install/show/search/uninstall

src/AppInstallerCLIE2ETests/ListCommand.cs, src/AppInstallerCLITests/ARPChanges.cpp, src/AppInstallerCLITests/Correlation.cpp, src/AppInstallerRepositoryCore/ARPCorrelation.cpp, src/AppInstallerRepositoryCore/Public/winget/ARPCorrelation.h
* For ARP matching we had a rule that would consider something a match if it was the only ARP change, but that is likely to give us false matches. This change removes that rule.
* For the string matching confidence algorithm, we would only consider matching package name with ARP name, and package publisher with ARP publisher, but sometimes the publisher would be included in the name and that would decrease confidence. For example, for package name = "Microsoft PowerToys"  and ARP name = "PowerToys". This change makes the string matching also consider the string publisher+name.
* Also made the matching requirements for the unit tests stricter
=> Remove ARP matching for single ARP change, and consider publisher+name for matching

src/AppInstallerCLICore/Workflows/PortableInstallFlow.cpp, src/AppInstallerCommonCore/PortableARPEntry.cpp, src/AppInstallerCommonCore/Public/winget/PortableARPEntry.h
Fixes a bug where the portable install flow should be checking whether ARP entry does NOT match the packageId or sourceId before blocking install.
=> Fix packageId and sourceId match check for portable install

src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp, src/AppInstallerCommonCore/Public/winget/ManifestValidation.h
=> Treat manifest localization validation error as warning for non full validation(manifest reading)

src/AppInstallerCommonCore/GroupPolicy.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/ManifestTable.h
-----
For those of us who ~~keep forgetting minor VS version bumps change the compiler~~ enjoy living on the bleeding edge, Visual Studio 2022 was updated to version 17.2 this week, again breaking winget builds. This PR resolves the errors, by adding a missing `typename` keyword in a couple places.
The kicker is, I can't find a changelog (publicly) that mentions what changed to cause this. Nothing in the [STL changelog](https://github.com/microsoft/STL/wiki/Changelog#vs-2022-172) looks to be it, and the [conformance changes](https://docs.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=msvc-170) don't mention it either. This seems more correct anyway, so I think it is fine, but if anyone could shed some more light that would be great!
(My daily builds broke because …
=> Fixed builds on VS 2022 version 17.2.

.github/actions/spelling/expect.txt, doc/specs/#980 - Apps and Features entries version mapping.md
=> Doc for ARP version mapping change

src/AppInstallerCLITests/ARPChanges.cpp, src/AppInstallerCLITests/Correlation.cpp, src/AppInstallerCLITests/NameNormalization.cpp, src/AppInstallerCLITests/Strings.cpp, src/AppInstallerCLITests/TestData/InputARPData.txt, src/AppInstallerCommonCore/AppInstallerStrings.cpp, src/AppInstallerCommonCore/NameNormalization.cpp, src/AppInstallerCommonCore/Public/AppInstallerStrings.h, src/AppInstallerCommonCore/Public/winget/NameNormalization.h, src/AppInstallerRepositoryCore/ARPCorrelation.cpp, src/AppInstallerRepositoryCore/ARPCorrelationAlgorithms.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/Public/winget/ARPCorrelation.h, src/AppInstallerRepositoryCore/Public/winget/ARPCorrelationAlgorithms.h
This improves the ARP matching heuristic by replacing the match confidence algorithm that used the edit distance between strings with an algorithm based on the words on each string.
Code changes:
* Moved the specific match confidence algorithms to a separate header from the overall ARP matching to reduce the recompilation needed when adding new heuristics.
* Added a new version to the normalizer that preserves the whitespace in the input strings. The existing version would remove all whitespace, which would prevent us from normalizing before splitting a string into words.
* Added a helper to split a string into words using ICU breaks.
Changes in the heuristic (and some notes):
* The algorithm was changed to be based on words on the strings instead of individual characters, which were more …
=> Improve ARP matching heuristic

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/TestData/InstallFlowTest_ExpectedReturnCodes.yaml, src/AppInstallerCLITests/WorkFlow.cpp
Resolves:  #1889
- Adds support for displaying an expectedReturnCode's returnResponseUrl if present. 
- Added a test to verify that the returnResponseUrl is correctly displayed
=> Display ReturnResponseUrl if present

schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/InstallFlowTest_InstallationNotes.yaml, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
Resolves #607
- Adds support for displaying the installation notes after a successful installation
- Adds the `--display-notes` flag and the `--suppress-notes` flag to control the default behavior of displaying the install notes
- Adds the setting `suppressInstallNotes` which is set to false by default 
- Adds a unit test to verify that installationNotes are displayed when the `--display-notes` flag is present
=> Display InstallationNotes after a successful install

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ShowFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Resolves: #1984
- Adds support for displaying the documentation label and url provided in the manifest when invoking the show command
=> Display documentations in show command

src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp
Fixes #2218
Add the missing "treat errors as warnings" bool for the root level localization validation.  It was previously applied to the other non-root localizations, but the root was missed.
Fixed the reported bug (manually verified), unit tests continue to pass.
=> Add missing localization error handling for root level localization info

schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Workflows/PortableFlow.cpp, src/AppInstallerCLIE2ETests/BaseCommand.cs, src/AppInstallerCLIE2ETests/FeaturesCommand.cs, src/AppInstallerCLIE2ETests/InstallCommand.cs, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
Changes:
- Makes support for portable apps stable and removes all code related to portable as an experimental feature.
=> Portable Support as Stable Feature

tools/CorrelationTestbed/Process-CorrelationResults.ps1
This changes the script that processes correlation results to produce simple stats of how many packages were correlated successfully. This can be used to easily evaluate if the correlation heuristic is doing well.
It also fixes an issue when running the script on powershell instead of pwsh, where a path join didn't use the full path and resulted in not being able to find the result JSON files.
=> Add simple stats to correlation result processing script

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Argument.h, src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLITests/Command.cpp
This change allows for argument aliases to be more than 1 character
=> Enable long aliases

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/PortableFlow.cpp, src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj, src/AppInstallerCLIE2ETests/UninstallCommand.cs, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Resolves #2190 
Changes:
- Checks the target of the portable symlink to verify that it matches the target exe path that is stored in ARP.
Tests:
- Upgraded E2E tests to .NET6.0 to use File.CreateSymbolicLink()
- Added Uninstall Test to verify that the symlink will not be deleted if it does not match the target exe path.
=> Check symlink target before removal

schemas/JSON/manifests/v1.2.0/manifest.singleton.1.2.0.json
Removes an extra space in the UnsupportedArg definition in the 1.2 singleton schema
=> Fix spacing in 1.2 singleton schema

src/AppInstallerCLITests/TestData/MultiFileManifestV1_2/ManifestV1_2-MultiFile-Installer.yaml, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCLITests/YamlManifest.cpp
Fixes several unit tests that were previously broken but didn't appear until a 1.2 schema typo was fixed.
=> Fix unsupported args unit tests

src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface_1_0.cpp
Mitigates #2273 for 1.3, but another change will hopefully be able to fully fix it.
Protect against the installed package returning a null installed version.  This should prevent crashes, while hiding the package from view.
I suspect that embedded nulls in the registry strings are causing the issues, and a future change will try to address that more comprehensively.
=> Mitigate crash that can occur when installed version is null

src/AppInstallerCLI/AppInstallerCLI.vcxproj, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerTestExeInstaller/AppInstallerTestExeInstaller.vcxproj, src/Microsoft.Management.Deployment.Client/Microsoft.Management.Deployment.Client.vcxproj, src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj, src/Microsoft.Management.Deployment.Server.Test/Microsoft.Management.Deployment.Server.Test.vcxproj, src/Microsoft.Management.Deployment/Microsoft.Management.Deployment.vcxproj, src/WinGetServer/WinGetServer.vcxproj, src/WinGetUtil/WinGetUtil.vcxproj, src/WindowsPackageManager/WindowsPackageManager.vcxproj
This change adds extra compiler flags to ensure we have appropriate information in the debug symbols for some compliance static analysis.
New compiler flags: `/Zi`
New linker flags: `/debug:full /debugtype:cv,fixup /incremental:no`
=> Add extra compilation flags for debug info

src/WinGetUtil/Exports.cpp
=> Fix WinGetUtil WinGetCreateManifest result

src/AppInstallerCLICore/Argument.cpp
When merge conflicts were resolved in #2216 it removed the alternate name from the usage string; This PR adds it back in
=> Add alternate name to Usage String

src/AppInstallerCLI/AppInstallerCLI.vcxproj, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/Microsoft.Management.Deployment.Client/Microsoft.Management.Deployment.Client.vcxproj, src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj, src/Microsoft.Management.Deployment.Server.Test/Microsoft.Management.Deployment.Server.Test.vcxproj, src/Microsoft.Management.Deployment/Microsoft.Management.Deployment.vcxproj, src/WinGetServer/WinGetServer.vcxproj, src/WinGetUtil/WinGetUtil.vcxproj, src/WindowsPackageManager/WindowsPackageManager.vcxproj
I added some extra compilation flags on #2281 for debug information. One of them was `/Zi` globally. `/ZI` (add debug symbols compatible with VS's Edit and Continue) is already added by default for Debug builds (on x86 and x64), and `/Zi` (add debug symbols) is added by default for Release or ARM builds, so this flag wasn't needed on Release (what we needed) and on Debug it would cause a warning due to using both `/Zi` and `/ZI`.
This flag can be set in VS with the property "Configuration Properties > C/C++ > General > Debug Information Format", which has the default value.
=> Remove /Zi compilation flag

tools/CorrelationTestbed/Test-CorrelationInSandbox.ps1
Update the hash for the VCLibs package to the latest version. See microsoft/winget-pkgs#65810
=> Update VCLibs file hash in correlation test script

src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/DependenciesTable.cpp
There is no reason to fail fast if these statements fail.
=> Don't fail fast

schemas/JSON/manifests/v1.2.0/manifest.singleton.1.2.0.json, schemas/JSON/manifests/v1.3.0/manifest.installer.1.3.0.json, schemas/JSON/manifests/v1.3.0/manifest.singleton.1.3.0.json, src/AppInstallerCLITests/TestData/ManifestV1_3-Singleton.yaml, src/AppInstallerCLITests/TestData/MultiFileManifestV1_3/ManifestV1_3-MultiFile-Installer.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp, src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp, src/AppInstallerCommonCore/Public/winget/ManifestCommon.h, src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h, src/AppInstallerCommonCore/Public/winget/ManifestYamlPopulator.h
Also fixed v1.2 schema where DisplayInstallWarning is used in multi-file schema but missing in singleton schema.
=> Add InstallationMetadata to manifests for future deep installation detection

.github/actions/spelling/expect.txt, src/AppInstallerCLITests/SQLiteWrapper.cpp, src/AppInstallerRepositoryCore/SQLiteWrapper.cpp
Use `sqlite3_errmsg` to get an error message with actual context as opposed to the string for the error code.  We can always look up the error code string if needed, and we will get the string for the HRESULT version in the logs as well.
For instance, the message for the new test is now:
```
Msg:[no such table: simpletest2]
```
Rather than the prior "Bad SQL" type default value.
All unit tests pass, manually confirmed more useful error messages in at least some cases.
=> Move to using sqlite3_errmsg to extract a contextual error for SQLite failures

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/FolderFileWatcher.cpp, src/AppInstallerCommonCore/pch.h, src/AppInstallerRepositoryCore/CompositeSource.cpp
Remove a correlation block that was put in place to make things consistent, but was also preventing things like `winget uninstall PREINSTALLED-THING-THAT-IS-IN-STORE`.
Also fixes a build warning and test cases from an unrelated checkin.
Can now `list` things using the Store ID even though you did not explicitly install them from the Store with `winget`.
=> Remove correlation blocker for remote->local in some cases

src/AppInstallerCLICore/Workflows/PortableFlow.cpp, src/AppInstallerCLIE2ETests/InstallCommand.cs, src/AppInstallerCLIE2ETests/TestCommon.cs
Fixes #2327 
Changes:
Fixes a big where the file overwrite warning was shown on every install including clean first installs. Modified the logic so that the warning only shows if a file is removed.
Tests:
Added an E2E test that installs a portable package twice. Verifies that the warning is only shown during the second install and not the first.
=> Fix file overwrite warning displayed on clean first install

.github/actions/spelling/expect.txt, src/AppInstallerCommonCore/FileLogger.cpp, src/AppInstallerRepositoryCore/SQLiteWrapper.cpp, src/AppInstallerRepositoryCore/SQLiteWrapper.h
Add a connection identifier and log it when opening the connection and with each statement.  This makes it somewhat easier to follow the (extremely) verbose SQLite logging.
Also changes the file logger to append by default, enabling logging to the same file repeatedly a possibility (a util scenario mostly).
=> Logging improvements

src/AppInstallerCLITests/Runtime.cpp, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Runtime.cpp
Fixes #2365 (Hopefully... it actually worked fine on my machine before this change.)
Add support for `SYSTEM` to the explicit ACLs, and give `SYSTEM` full control on the `Temp` directory.
`ApplyACL` and the data that it uses are basically re-written to support a more dynamic list of ACEs.  Also ensures that if the process is running as `SYSTEM`, it doesn't attempt to write the same ACE multiple times.
Existing tests and a new unit test for this scenario.  Manually ran as `SYSTEM` to ensure that it does the correct thing.
=> Add SYSTEM to explicit ACLs

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/PowerShell/Microsoft.WinGet.Client/Properties/Resources.Designer.cs
=> Standardize 'Show' labels to manifest fields

src/AppInstallerCLICore/ExecutionContextData.h, src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLIE2ETests/Interop/InstallInterop.cs, src/AppInstallerCLITests/ManifestComparator.cpp, src/Microsoft.Management.Deployment/Converters.cpp, src/Microsoft.Management.Deployment/Converters.h, src/Microsoft.Management.Deployment/PackageManager.cpp, src/Microsoft.Management.Deployment/PackageManager.idl
Adds two new scope options for COM; `UserOrUnknown` and `SystemOrUnknown`.  These will allow the installer selection to consider both the specific scope, as well as an unknown scope.
Unit tests and COM E2E tests are added for the scenario.
=> Add the ability to specify "scope or unknown" via COM

src/AppInstallerCLITests/InstallerMetadataCollectionContext.cpp, src/AppInstallerRepositoryCore/InstallerMetadataCollectionContext.cpp, src/AppInstallerRepositoryCore/Public/winget/InstallerMetadataCollectionContext.h
Include the installed scope during metadata collection.  This uses the current detection method, which is "HKLM or HKCU?"
When there us a mismatch, the value will be explicitly set to `Unknown`.
New unit tests added, mostly for the mismatch cases.
=> Collect scope in installer metadata

src/AppInstallerCLIE2ETests/Constants.cs, src/AppInstallerCLIE2ETests/ListCommand.cs, src/AppInstallerCLIE2ETests/README.md, src/AppInstallerCLIE2ETests/TestCommon.cs
E2E tests copy the winget logs to a location that is published as artifacts in the pipeline, but only for when winget runs packaged. When winget runs unpackaged, the logs are placed in a different location and are not copied.
This PR changes to also copy the logs from unpackaged runs.
=> Copy winget unpackaged logs in E2E tests

src/AppInstallerCLICore/Commands/HashCommand.cpp
=> Update Labels from Hash Command

README.md, doc/specs/#140 - ZIP Support.md, doc/specs/#182 - Support for installation of portable standalone apps.md, doc/specs/#888 - Com Api.md, doc/troubleshooting/README.md
Removed `en-US/` in all links excluding the `/src` folder. I know not every link has different languages, but some do, so it's better to have the standard use of Microsoft links to not force English if another language is previously selected. If the user selected language is not available for that page, it will just display it in English.
-----
=> Removed en-US in links

src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp
-----
Issue: 
- #229 
Problem: 
- Every WinGet installation using `msiexec` may restart the computer suddenly if any of the affected files are in use.
Solution: 
- Add '/norestart' flag by default.
=> Suppress reboot by default on msiexec based installers

src/AppInstallerRepositoryCore/InstallerMetadataCollectionContext.cpp, src/AppInstallerRepositoryCore/RepositorySource.cpp
- Fixed installer metadata collection crash by delay initializing SourceList
- Fixed issue with parsing input json be removing trailing null characters
=> Fix installer metadata collection

src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp
-----
Issue:
- https://github.com/microsoft/winget-cli/issues/229
Problem:
- Every WinGet installation for Inno Setup based installers may restart the computer suddenly if any of the affected files are in use.
Solution:
- Add '/NORESTART' flag by default.
https://jrsoftware.org/ishelp/index.php?topic=setupcmdline
=> Suppress reboot by default on Inno Setup based installers

src/AppInstallerCLICore/Workflows/DownloadFlow.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/InstallFlowTest_EncodedUrl.yaml, src/AppInstallerCLITests/WorkFlow.cpp
=> Fix installer renaming failure from encoded url

src/AppInstallerCLICore/PortableInstaller.cpp
When issues arise, additional logging here is helpful - See #2561
-----
=> Additional logging when validating portable file fails

src/AppInstallerCommonCore/Filesystem.cpp
=> Make Symlink Target Canonical

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/Commands/ShowCommand.cpp, src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLITests/CompositeSource.cpp, src/AppInstallerCLITests/ManifestComparator.cpp, src/AppInstallerCommonCore/Architecture.cpp, src/AppInstallerCommonCore/Public/AppInstallerArchitecture.h, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/PackageTrackingCatalog.cpp, src/AppInstallerRepositoryCore/Public/winget/PackageTrackingCatalog.h, src/AppInstallerRepositoryCore/Public/winget/RepositorySearch.h, src/AppInstallerRepositoryCore/RepositorySearch.cpp
- Record installed architecture and locale as preference and corresponding passed in args as requirement
- Populate these info as installed metadata and use them during installer selection
- Fixed PinnedState not working issue along with above metadata population
- Added tests for tracking catalog and manifest comparator
=> Improve installer selection during upgrade

src/AppInstallerCommonCore/Manifest/MsixManifestValidation.cpp, src/AppInstallerCommonCore/Public/winget/MsixManifestValidation.h
- MSIX manifest validation fails to read information about certain packages from the installer URL
- https://github.com/microsoft/winget-pkgs/issues/79677 
- Added a step for downloading the installer if reading the information directly from the installer URL failed.
=> Download MSIX installer during manifest validation (if necessary)

src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp, src/AppInstallerCommonCore/Manifest/MsixManifestValidation.cpp, src/AppInstallerCommonCore/Public/winget/MsixManifestValidation.h
Remove MSIX installers _after validation is done_ in order to ensure that the information used during validation is available when needed.
=> Remove MSIX installers after validation is done

tools/CorrelationTestbed/Process-CorrelationResults.ps1
The correlation results processing script fails if every test case fails.  Things are already going poorly, so let's not add on to that with a script error...
=> Fix error when everything fails

src/IndexCreationTool/IndexCreationTool.csproj, src/LocalhostWebServer/LocalhostWebServer.csproj, src/PowerShell/Microsoft.WinGet.Client/Common/BaseClientCommand.cs, src/PowerShell/Microsoft.WinGet.Client/Copy-PlatformBinaries.ps1, src/PowerShell/Microsoft.WinGet.Client/Microsoft.WinGet.Client.csproj, src/PowerShell/Microsoft.WinGet.Client/README.md, src/UndockedRegFreeWinRT/UndockedRegFreeWinRT/UndockedRegFreeWinRT.vcxproj, src/UndockedRegFreeWinRT/detours/detours.vcxproj
Changes:
- Fixes a bug where the release configuration build for the PowerShell module was throwing a type initialization error. 
- Updates the build output for Detours and UndockedRegFreeWinRT to the appropriate location
- Added an post-build event to copy the modules files into its own directory so that it can be run directly
- Added a README with instructions on how to run the powershell module locally.
=> Fix PowerShell module for release configuration

doc/troubleshooting/README.md
Added hints how to reinstall App Installer
Are you working against an Issue? 
- no, improving documentation (in consequence of following hints from some issues)
-----
=> Added info about reinstalling App Installer to troubleshooting README.md

schemas/JSON/manifests/v1.4.0/manifest.installer.1.4.0.json, schemas/JSON/manifests/v1.4.0/manifest.singleton.1.4.0.json
Related to: #2600 
Updates the max item number of protocols from 16 to 64.
=> Update protocols max items to 64

src/AppInstallerCLICore/PortableInstaller.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
- #2516
There is a slight technicality with this in that it prints the alias has been added when the symlink/file is created before the path has been modified. This is because the alias should be printed for each portable package installed. From my perspective, I don't believe this matters since there isn't any case in the code where adding to path would fail. 
-----
=> Print command aliases added on portable install

.github/ISSUE_TEMPLATE/config.yml
Add an issue option so that people who encountered package-related issues would post them to winget-pkgs instead of winget-cli, just like "WinGet Client issues" in <https://github.com/microsoft/winget-pkgs/issues/new/choose>.
-----
=> Add an issue option to guide users to winget-pkgs for package issues

src/AppInstallerCLICore/Workflows/InstallFlow.cpp
This fixes an issue where default arguments are not being passed to nested installers
=> Get arguments when using archive type package

doc/admx/DesktopAppInstaller.admx, doc/admx/en-US/DesktopAppInstaller.adml, doc/troubleshooting/README.md, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/GroupPolicy.cpp, src/AppInstallerCLITests/Sources.cpp, src/AppInstallerCLITests/TestSettings.h, src/AppInstallerCommonCore/AdminSettings.cpp, src/AppInstallerCommonCore/GroupPolicy.cpp, src/AppInstallerCommonCore/Public/winget/GroupPolicy.h, src/AppInstallerCommonCore/Public/winget/Resources.h
- Added Group policy control for BypassCertificatePinningForMicrosoftStore
- Added tests
=> Group policy control for BypassCertificatePinningForMicrosoftStore

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/Manifest-Bad-MsixInstaller-PackageVersion.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/MsixManifestValidation.cpp, src/AppInstallerCommonCore/Public/winget/MsixManifestValidation.h
- Report an error message if the package version could not be parsed to UINT64 during the manifest (Msix) installer validation, instead of throwing an exception.
- Added unit test
=> Manifest (Msix) installer validation - Try parsing package version

src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj, src/Microsoft.Management.Deployment.Projection/Microsoft.Management.Deployment.Projection.csproj, src/PowerShell/Microsoft.WinGet.Client/Microsoft.WinGet.Client.csproj, src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj, src/WinGetUtilInterop/WinGetUtilInterop.csproj
As far as I could tell, these changes don't cause any build issues. But, knowing my luck, I'm probably missing something. Lets just see where this lands. 
This doesn't update all NuGet packages, just the ones that seemed like they were close in version and were unlikely to have breaking changes.
=> Update NuGet Packages

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/SettingsFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/AdminSettings.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCommonCore/AdminSettings.cpp, src/AppInstallerCommonCore/Public/winget/AdminSettings.h
- If an admin setting was disabled by a group policy, and user attempts to enable it using `winget settings --enable`, then report an error message.
- Similarly, if an admin setting was enabled by group policy, and user attempts to disable it using `winget settings --disable`, then report an error message.
- Added tests covering the various state combinations.
=> Don't enable/disable admin settings if group policy prevents it

src/AppInstallerCLICore/Workflows/DownloadFlow.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/InstallFlowTest_InvalidFileCharacterUrl.yaml, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/Downloader.cpp
=> Fix renaming issue with invalid file character url

src/AppInstallerCLICore/Commands/SourceCommand.h
Adding alias for consistency with the `ls` alias for the `list` command.
=> Add `source ls` alias for `source list`

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
This standardizes how we use arguments in resource strings and adds comments so that the localization team does not change them. We had different styles, like `"--argument"`, `argument`, `--argument`. This standardizes all to `--argument` for consistency.
=> Standardize how arguments are used in resource strings

src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_AddRemoveSource.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_EnableSettings.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_FindPackage.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_GetPackage.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_GetVersion.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_InstallPackage.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_UninstallPackage.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_UpdatePackage.ps1, src/PowerShell/Microsoft.WinGet.Client/Microsoft.WinGet.Client.psd1, src/PowerShell/Microsoft.WinGet.Client/Microsoft.WinGet.Client.psm1
- Updates the help text with the proper information.
- Add example scripts for each supported cmdlet.
- Adds [CmdletBinding(SupportsShouldProcess)] to pass PSScriptAnalyzer checks
=> Add PowerShell cmdlet help text and examples

src/PowerShell/Microsoft.WinGet.Client/Copy-PlatformBinaries.ps1, src/PowerShell/Microsoft.WinGet.Client/Examples/Sample_FindPackage.ps1, src/PowerShell/Microsoft.WinGet.Client/Microsoft.WinGet.Client.csproj
Updates the target desktop .NET framework for the powershell module project from 4.6 to 4.8 since version 4.6 is no longer supported.
=> Update powershell module target framework to 4.8

src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/InstallFlowTest_UnknownVersion.yaml, src/AppInstallerCLITests/WorkFlow.cpp
Fixes: #2714
Changes:
- Fixes an issue where the --include-unknown argument was unable to be combined with query arguments (--id, --name etc.)
- Added unit tests for verifying the behavior of the --include-unknown argument.
=> Allow upgrade for unknown version packages

doc/Settings.md, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters, src/AppInstallerCLICore/Commands/PinCommand.cpp, src/AppInstallerCLICore/Commands/PinCommand.h, src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Commands/SourceCommand.h, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/PinFlow.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
This change adds an empty `pin` command. Actual implementation of the command will come as a separate PR. This change includes:
* Definition of the `pin` command and its sub-commands `add`, `remove`, `list`, `reset`. These definitions contain only the definition of arguments but are missing the actual execution code.
* A new experimental feature flag to hide this command.
* All the help resource strings for the command. Still pending all the resources that will be shown during actual execution.
* Adds a `source ls` alias for the `source list` command.
* Changes an existing string to make it consistent with the rest.
=> Add empty `pin` command

src/AppInstallerCLICore/Workflows/DependenciesFlow.cpp, src/AppInstallerCLICore/Workflows/DependencyNodeProcessor.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.h, src/AppInstallerCLICore/Workflows/ShowFlow.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/Dependencies.cpp, src/AppInstallerCLITests/DependenciesTestSource.h, src/AppInstallerCLITests/TestData/InstallFlowTest_MultipleDependencies.yaml, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp, src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp, src/AppInstallerCommonCore/Public/winget/ManifestCommon.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/DependenciesTable.cpp, src/AppInstallerRepositoryCore/PackageDependenciesValidation.cpp
Added tests. Also verified locally.
=> Fix issue that only 1 dependency package is installed

src/PowerShell/Microsoft.WinGet.Client/Commands/InstallPackageCommand.cs, src/PowerShell/Microsoft.WinGet.Client/Common/Utilities.cs, src/PowerShell/Microsoft.WinGet.Client/Helpers/ComObjectFactory.cs
Suppresses CA1416 warnings that require windows-only apis to be identified in the AppInstaller build.
=> Suppress warnings for CA1416 in PowerShell module

src/nuget.config
Related to: #2756
Adds back the nuget.config file for public dependencies. This file was causing an issue in the AppInstaller build pipeline because it points to a public feed. This file will be removed in the AppInstaller repository rather than here since it is needed in the winget-cli repository.
=> Restore nuget.config file for public dependencies

src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Command.h, src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Commands/SettingsCommand.h, src/AppInstallerCLICore/Commands/SourceCommand.h, src/AppInstallerCLICore/Workflows/SettingsFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/UserSettings.cpp, src/AppInstallerCommonCore/Filesystem.cpp, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Public/winget/Filesystem.h, src/AppInstallerCommonCore/Public/winget/Resources.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerCommonCore/UserSettings.cpp
Fix bug introduced by #2719
Using `Runtime::GetPathTo` uses `PathDetails` which creates a directory when PathDetails.Create is true (which is the default). When `winget settings export` is called, that makes the code create a directory named the same as the settings file. Now, next winget run will try to open the file but it will find out it is a path and give up on life.
Since `Runtime::GetPathTo` is more related to path, getting the user settings json file path is not the best option. Move logic to UserSettings.cpp. Also catch the exception when trying to parse the fail to not make winget fail but use the default settings is something happens.
=> Fix winget after a call to winget settings export

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Argument.h, src/AppInstallerCLICore/Workflows/ArchiveFlow.cpp, src/AppInstallerCLICore/Workflows/DownloadFlow.cpp, src/AppInstallerCLITests/WorkFlow.cpp, src/AppInstallerCommonCore/AdminSettings.cpp, src/AppInstallerCommonCore/Public/winget/AdminSettings.h
Added corresponding admin settings for InstallerHashOverride and LocalArchivemalwareScanOverride
Also added tests.
=> Add additional admin setting to match security related group policies

src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Command.h, src/AppInstallerCLICore/ContextOrchestrator.cpp, src/AppInstallerCLICore/ContextOrchestrator.h
Calls to COM install/upgrade were logging the distinct steps (download/install) as separate commands under the same activity.  This was leading to an incorrect success metric due to the method of processing.
This change treats the `OrchestratorQueueItem` as the command for telemetry purposes.  This aligns with the `winget.exe` method of counting success/failure.  It also moves to use the same command names as `winget.exe`, making it easier to join/slice the data.
Using an ETW event tracer, manually verified the current bad state.  Then verified that the change produces a single start/stop pair under the same activity for an install.
=> Don't treat the COM subcommands as distinct for telemetry

src/PowerShell/Microsoft.WinGet.Client/README.md
Resolves #2795 
Changes:
Updates the PowerShell module documentation to explicitly identify the required dependency on the Microsoft Visual C++ Redistributable package in order to run the cmdlets
=> Update PowerShell Module Dependency Docs

src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp
=> Adjust spacing and punctuation for manifest validation messages

Localization/Policies/de-DE/DesktopAppInstaller.adml, Localization/Policies/fr-FR/DesktopAppInstaller.adml
Applies the latest localized strings patch.
=> Apply latest localized strings patch

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
We were observing crashes in `TelemetryTraceLogger::LogFailure()` due to heap corruption. The root cause of this is that for many types of COM calls we don't have a thread local telemetry trace logger, but instead use a process global. If there are multiple simultaneous calls, there is a possibility for a race condition, specifically around writing to the `TelemetryTraceLogger`'s `m_summary`.
The long term solution would be to stop using a process globals there, but that is tricky. As a band-aid to prevent these crashes, disable the use of `m_summary` in the process globals.
Tested by creating a local repro of the crash and verifying it didn't crash after the change. Repro'd by adding an artificial `THROW_HR_MSG` to force going to `LogFailure()` and then using the sample COM caller …
=> Stop using `m_summary` in the global globals for telemetry

src/AppInstallerCLITests/ExportFlow.cpp, src/AppInstallerCLITests/ImportFlow.cpp, src/AppInstallerCLITests/InstallFlow.cpp, src/AppInstallerCLITests/ShowFlow.cpp, src/AppInstallerCLITests/UninstallFlow.cpp, src/AppInstallerCLITests/UpdateFlow.cpp, src/AppInstallerCLITests/WorkflowCommon.cpp, src/AppInstallerCLITests/WorkflowCommon.h
Another refactor that nobody asked for, for something that has been bothering me for a long time and I couldn't ignore while working on something else... (I swear I am also working on the stuff I'm supposed to!)
This change breaks up the huge `WorkflowTestCompositeSource::Search()` function, which was a long series of "if query is 'package' then add package to search results" (and which had a fun compilation warning about using too much space in the stack). I'm doing this by creating objects containing the matching query string and the modifications made to the search results in case of a match. Then, the search function can just iterate over these objects and modify the results when appropriate.
On each test, we now declare which results we want to get and we can use the query strings …
=> Refactor test workflow source search

doc/Settings.md
Fix typo in "installBehavior.defaultInstallRoot" value, in the "Settings.md" file.
-----
=> Fix typo in Settings.md

tools/CorrelationTestbed/Process-CorrelationResults.ps1
One of the correlation test scripts includes a line that makes a cmdlet use utf8BOM encoding, which doesn't exist in powershell.exe, only on pwsh.exe. Change this encoding to utf8 which is supported in both.
=> Make correlation test script work on powershell.exe

src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/ExecutionContext.h, src/AppInstallerCLITests/UpdateFlow.cpp, src/AppInstallerCLITests/WorkflowCommon.cpp
*Issue:*
When we install multiple packages in the same execution (`upgrade --all` and `import`), we create a sub-context to install each individual package but this sub-context does not respect the parent's install behavior flags, like `--silent`.
*Change:*
Added a step to the creation of a sub-context to copy the relevant flags from the parent context, so that the same behavior is used for all packages. Added a test to verify the new behavior.
---
This came from a user running `winget upgrade --all --silent` and expecting all the upgrades to be done silently. We need to either respect those flags (this PR) or change the argument validation to forbid that combination.
I figure the most contentious issue with this PR will be which args we should forward. I added basically everything that …
=> Copy install behavior flags on upgrade --all

azure-pipelines.yml, src/PowerShell/Microsoft.WinGet.Client/Microsoft.WinGet.Client.csproj
Since the PowerShell Module project targets multiple frameworks, all of the runtime binaries (including non-windows) are getting included from the Microsoft.PowerShell.SDK nuget package used in #2776 . It is possible that other runtimes may need to be included in the future but I only included the ones I thought were relevant as of right now.
Changes:
- Modified the Microsoft.WinGet.Client.csproj file so that only [win10-specific](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#windows-rids) runtime binaries get included in the module.
Before:
After:
=> Exclude non-Windows runtime binaries from PowerShell Module

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLIE2ETests/FeaturesCommand.cs, src/AppInstallerCLIE2ETests/WinGetSettingsHelper.cs, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
- #2355
-----
@yao-msft - I'm assuming this also needs to be added to COM and to PowerShell modules for feature parity? If so, I'm not sure how to go about implementing it. I tried to search for the Verbose logs implementation in the COM context but didn't find it, and wasn't able to think of a good way to create the common arguments implementations. Any guidance here is appreciated
=> Make --Open-Logs Stable

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/InstallFlow.cpp, src/Microsoft.Management.Deployment/InstallOptions.cpp, src/Microsoft.Management.Deployment/InstallOptions.h, src/Microsoft.Management.Deployment/PackageManager.cpp, src/Microsoft.Management.Deployment/PackageManager.idl, src/PowerShell/Microsoft.WinGet.Client/Commands/Common/BaseInstallCommand.cs
- #239
- #1403
-----
- I chose the argument based on what made sense to me and what was in the referenced issues. If a different name is desired, I'm open to suggestions. 
- Decided to name the arg type CustomSwitches to avoid future confusion; again, if there's a better name, feel free to suggest.
```raw
// Installation failure was expected as the '/?' argument brings up the MSI help menu
PS D:\Git\winget-pkgs> wingetdev install --manifest D:\Git\winget-pkgs\manifests\7\7zip\7zip\22.01 --custom /? --verbose --open-logs
Found 7-Zip [7zip.7zip] Version 22.01
Downloading https://www.7-zip.org/a/7z2201-x64.msi
██████████████████████████████  1.82 MB / …
```
=> Add --custom argument for passing additional installer arguments

src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp, src/AppInstallerCLICore/Workflows/UninstallFlow.cpp
- msix provision and deprovision apis under packaged context
- msstore provision apis under admin context
Related OS bugs have been filed.
=> Block msix provisioning api calls where known OS bugs exist

src/AppInstallerCLICore/Commands/SearchCommand.cpp, src/AppInstallerCLICore/Workflows/ShowFlow.cpp, src/AppInstallerCLICore/Workflows/ShowFlow.h, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h
- #520
-----
This PR moves the workflow for ShowAppVersions into the workflow base and makes it available to the search command.
Intentionally left the search command as `SearchSourceForMany` to retain the same searching behavior. 
```
PS C:\WINDOWS\system32> wingetdev search 7zip.7zip --versions
Multiple packages found matching input criteria. Please refine the input.
Name              Id                  Source
--------------------------------------------
7-Zip             7zip.7zip           winget
7-Zip Alpha (msi) 7zip.7zip.Alpha.msi winget
7-Zip Alpha (exe) 7zip.7zip.Alpha.exe winget
PS C:\WINDOWS\system32> wingetdev search -e 7zip.7zip --versions
Found 7-Zip [7zip.7zip]
Version
----------
22.01
22.00
21.07
21.06
19.00.00.0
16.04
```
=> Allow Version Listing through 'Winget Search'

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Argument.h, src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Commands/CompleteCommand.cpp, src/AppInstallerCLICore/Commands/ExportCommand.cpp, src/AppInstallerCLICore/Commands/ImportCommand.cpp, src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/Commands/ListCommand.cpp, src/AppInstallerCLICore/Commands/PinCommand.cpp, src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Commands/SearchCommand.cpp, src/AppInstallerCLICore/Commands/SettingsCommand.cpp, src/AppInstallerCLICore/Commands/ShowCommand.cpp, src/AppInstallerCLICore/Commands/SourceCommand.cpp, src/AppInstallerCLICore/Commands/UninstallCommand.cpp, src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/Argument.cpp, src/AppInstallerCLITests/Command.cpp, src/AppInstallerCLITests/Completion.cpp
This change adds a set of argument "categories" that tell us what an argument is used for and makes it easier to reason around which arguments can be used at the same time. For example, a manifest arg cannot be used at the same time as an arg related to sources.
The main change is adding a function to identify the categories of arguments used in an invocation, and a function to use those categories for validation.  Then, I used these new functions to replace the arg validation for commands that had similar rules.
This is what I wanted to do for #1788, and should make arg validation for #2861 easier to get right.
=> Refactor arg validation 

tools/PowerShell/Microsoft.WinGet/src/Microsoft.WinGet.psm1
=> chore: remove blank line

tools/CorrelationTestbed/InSandboxScript.ps1
We have a test script that uses Invoke-Expression to execute a command from a string we make up with string concatenation. This isn't good because the string gets parsed as Powershell code and it's easy to get it to inject other commands on it. This change replaces the use of Invoke-Expression by the use of the call operator & and passing the arguments as an array of strings, instead of a single string to be parsed. This script is only used on an internal pipeline where we supply all the input.
=> Remove use of Invoke-Expression in test script

src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/SettingsFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/AdminSettings.cpp, src/AppInstallerCommonCore/Public/winget/AdminSettings.h
- #2898
-----
This is only a partial implementation, as the user settings are much more complicated. The table is only output if there are AdminSettings enabled, and only shows the admin settings that are enabled
=> Show Enabled Admin Settings in --info

src/AppInstallerCommonCore/MsixInfo.cpp
PackageManager.FindPackages requires elevated context, the fix will be to revert to use previous FindPackagesByPackageFamily
=> Fix GetFullNameFromFamilyName for non-elevated context

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
- Fixed a duplicate summary event field and rename summary event to SummaryV2
- Make subcontext telemetry use a different activity id
=> Fix Summary telemetry event

.github/actions/spelling/expect.txt
When pinning spec pr was created, the spelling check was disabled.
I will send a follow up pr to update the pinning spec to match what is actually implemented in the end.
=> Fix spelling from pinning spec

schemas/JSON/settings/settings.schema.0.2.json
Add the "pinning" experimental feature to the settings file JSON schema to make it discoverable.
=> Update settings.schema.0.2.json to include pinning feature

src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSource.h, src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/SourceList.cpp
Sometimes bad things happen; even when you thought you had everything set up properly it might turn out that you didn't.  The best laid plans, etc.  If there is a way to continue functioning, even if it is less efficient, shouldn't we use that?
Adds an alternate base URL for the sources behind `cdn.winget.microsoft.com`.  In the event that the files hosted there are inaccessible or corrupted, the alternate URL will be used instead.  This mechanism does rely on the fact that these are basically two names for the exact same set of data, which is true as the alternate is the upstream store for the CDN itself.
Additionally, we now require preindexed packaged sources to contain the manifest hash, rather than just using it if present.
Finally, this change adds a setting that can be used to …
=> Add alternate url support for some predefined sources

schemas/JSON/manifests/v1.2.0/manifest.installer.1.2.0.json, schemas/JSON/manifests/v1.2.0/manifest.singleton.1.2.0.json
- Resolves #2532
-----
I've checked and don't believe that zip is implemented in any of the 1.2 interfaces, meaning it is safe to remove here.
If a 1.2 manifest does contain installer type zip, it will throw a validation warning but should not error
=> Remove zip from 1.2 schema

schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json, schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json, schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json, schemas/JSON/manifests/v1.1.0/manifest.singleton.1.1.0.json, src/AppInstallerCLITests/TestData/Manifest-Good-SystemReferenceComplex.yaml, src/AppInstallerCLITests/TestData/Manifest-Good.yaml, src/AppInstallerCLITests/TestData/ManifestV1-Singleton.yaml, src/AppInstallerCLITests/TestData/ManifestV1_1-Singleton.yaml, src/AppInstallerCLITests/TestData/ManifestV1_2-Singleton.yaml, src/AppInstallerCLITests/TestData/ManifestV1_4-Singleton.yaml, src/AppInstallerCLITests/TestData/MultiFileManifestV1/ManifestV1-MultiFile-Installer.yaml, src/AppInstallerCLITests/TestData/MultiFileManifestV1_1/ManifestV1_1-MultiFile-Installer.yaml, src/AppInstallerCLITests/TestData/MultiFileManifestV1_2/ManifestV1_2-MultiFile-Installer.yaml, src/AppInstallerCLITests/TestData/MultiFileManifestV1_4/ManifestV1_4-MultiFile-Installer.yaml, src/AppInstallerCLITests/YamlManifest.cpp
Continuation of #2996
Removes zip installer type from 1.0 and 1.1 manifests as zip is not supported until 1.4 client.
Also fixes the unit tests accordingly so that they do not rely on the zip installertype.
=> Remove zip installer type from 1.0 and 1.1 manifests

doc/Settings.md
"default install root" is an install behavior setting, but it has been wrongly put under uninstall behavior section.
-----
=> docs: fix "default install root" location

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, src/AppInstallerCLICore/Workflows/PromptFlow.cpp, src/AppInstallerCLITests/FolderFileWatcher.cpp, src/AppInstallerCLITests/InstallerMetadataCollectionContext.cpp, src/AppInstallerCommonCore/Filesystem.cpp, src/AppInstallerCommonCore/FolderFileWatcher.cpp, src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Public/winget/Filesystem.h, src/AppInstallerCommonCore/Public/winget/FolderFileWatcher.h, src/AppInstallerCommonCore/Public/winget/ManifestCommon.h, src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/InstalledFilesCorrelation.cpp, src/AppInstallerRepositoryCore/InstallerMetadataCollectionContext.cpp, src/AppInstallerRepositoryCore/PackageInstalledStatus.cpp, src/AppInstallerRepositoryCore/Public/winget/InstalledFilesCorrelation.h, src/AppInstallerRepositoryCore/Public/winget/InstallerMetadataCollectionContext.h, src/AppInstallerRepositoryCore/pch.h, src/AppInstallerSharedLib/AppInstallerStrings.cpp, src/AppInstallerSharedLib/Public/AppInstallerStrings.h
Tested manually and added unit tests for merging related logic.
=> Add installed files and startup link metadata collection in Installer Metadata collection util

src/AppInstallerCLICore/PortableInstaller.cpp, src/AppInstallerCLICore/PortableInstaller.h, src/AppInstallerCLICore/Workflows/PortableFlow.cpp, src/AppInstallerCLITests/InstallFlow.cpp, src/AppInstallerCLITests/UpdateFlow.cpp
Fixes:
- #2909 
- #2949 
Description:
When failing to create a symlink (non-developer mode or non-admin), we should be adding the package install directory directly to PATH. However, the default root directory for portable packages was always being added instead. This has been causing issues when users attempt to execute the command alias, which fails to recognize the portable executable/symlink. This is especially problematic for portable(s) in zips as their `RelativeFilePath` was being ignored. 
Changes:
- If we fail to create a symlink, the InstallDirectoryAddedToPath key value is set to true and the portable target directory is added directly to PATH for all portables. 
- Modified the AddToPathVariable method to take in a value to add to PATH instead of predetermining the value to add …
=> Fix PATH behavior of non-symlink installations for Portables/Zip

schemas/JSON/configuration/configuration.schema.0.1.json
Changes:
- Defines an enclosing `properties` object that contains all of the fields, which is what is expected based on the configuration implementation. 
- Changes the default value of `configurationVersion` to `0.1.0` to align with semantic versioning.
Validated test yamls with these schema changes.
=> Define properties object in configuration schema

src/AppInstallerCLICore/ConfigurationSetProcessorFactoryRemoting.cpp, src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCLITests/TestConfiguration.cpp, src/AppInstallerCLITests/TestConfiguration.h, src/AppInstallerSharedLib/AppInstallerLogging.cpp, src/AppInstallerSharedLib/Public/AppInstallerLogging.h, src/Microsoft.Management.Configuration.Processor/Exceptions/FindDscResourceNotFoundException.cs, src/Microsoft.Management.Configuration.Processor/Exceptions/GetDscResourceMultipleMatches.cs, src/Microsoft.Management.Configuration.Processor/Exceptions/InstallDscResourceException.cs, src/Microsoft.Management.Configuration.Processor/Exceptions/InvokeDscResourceGetException.cs, src/Microsoft.Management.Configuration.Processor/Exceptions/InvokeDscResourceSetException.cs, src/Microsoft.Management.Configuration.Processor/Exceptions/InvokeDscResourceTestException.cs, src/Microsoft.Management.Configuration.Processor/Helpers/ConfigurationUnitAndResource.cs, src/Microsoft.Management.Configuration.Processor/Helpers/ConfigurationUnitInternal.cs, src/Microsoft.Management.Configuration.Processor/ProcessorEnvironments/HostedEnvironment.cs, src/Microsoft.Management.Configuration.Processor/Public/ConfigurationSetProcessorFactory.cs, src/Microsoft.Management.Configuration.Processor/Set/ConfigurationSetProcessor.cs, src/Microsoft.Management.Configuration.Processor/Unit/ConfigurationUnitProcessor.cs, src/Microsoft.Management.Configuration.UnitTests/Helpers/TestConfigurationProcessorFactory.cs, src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp, src/Microsoft.Management.Configuration/ConfigurationProcessor.h, src/Microsoft.Management.Configuration/DiagnosticInformation.cpp, src/Microsoft.Management.Configuration/DiagnosticInformation.h, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.idl
This change adds the same diagnostics event to the `IConfigurationSetProcessorFactory` as the `ConfigurationProcessor` already has.  It also adds a property to control the minimum level of events, enabling filtering to be done at event publishing rather than consumption.
All of the public facing methods in the processor component are enlightened to send any escaping exceptions to the diagnostics before letting them generate an error.  Additionally, verbose logs are added throughout to enable a better understanding of what/when things are happening.
Manual runs, including with verbose logging enabled.  Verified output in log file.
=> Add diagnostics to the processor component

src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
In attempting to diagnose issues with search results, it's helpful to have the number of matches in the search result. This information is sent to telemetry, but is not ever put into the log.
=> Add logging around specific number of matches

README.md
This PR fixes the link for the privacy statement in the README currently it directs to a page that does not exists this PR fixes that.
-----
=> Update the privacy statement link in README to link to correct page

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
=> Remove one unnecessary lock per localization team suggestion

.github/actions/spelling/expect.txt, src/AppInstallerCLICore/COMContext.cpp, src/AppInstallerCLICore/COMContext.h, src/AppInstallerCLICore/ChannelStreams.cpp, src/AppInstallerCLICore/ChannelStreams.h, src/AppInstallerCLICore/ExecutionProgress.cpp, src/AppInstallerCLICore/ExecutionProgress.h, src/AppInstallerCLICore/ExecutionReporter.cpp, src/AppInstallerCLICore/ExecutionReporter.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/TableOutput.h, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.h, src/AppInstallerCLICore/Workflows/UninstallFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCLITests/InstallFlow.cpp, src/AppInstallerCLITests/Synchronization.cpp, src/AppInstallerCLITests/TestCommon.cpp, src/AppInstallerCLITests/TestCommon.h, src/AppInstallerCLITests/WorkflowCommon.cpp, src/AppInstallerCommonCore/Progress.cpp, src/AppInstallerCommonCore/Public/AppInstallerProgress.h, src/AppInstallerCommonCore/Public/AppInstallerSynchronization.h, src/AppInstallerCommonCore/Synchronization.cpp
This change uses a named mutex to enforce a single install/uninstall operation is occurring for the entire session.  The current behavior is that every process was able to install a single thing at a time, but as we have more usage this could lead to a potential issue.
The mutex is acquired and held for the workflow task that routes out to the installer type specific tasks.  Some installer types are explicitly excluded, as they are known to contain their own synchronization internally.
In addition to the mutex, the ability to set a message to show with the indefinite progress (spinner) was added.  This allows for the message to be removed when the wait is over.  The message was not implemented into the progress bar, nor is it being sent to COM progress.
The COM scheduling was not made …
=> Enforce single install across winget processes

src/AppInstallerCLIE2ETests/ListCommand.cs, src/AppInstallerCLIE2ETests/TestData/Manifests/TestMappingWithArchitectureX64.yaml, src/AppInstallerCLIE2ETests/TestData/Manifests/TestMappingWithArchitectureX86.yaml, src/AppInstallerCLITests/NameNormalization.cpp, src/AppInstallerCommonCore/NameNormalization.cpp, src/AppInstallerCommonCore/Public/winget/NameNormalization.h, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/Microsoft/ARPHelper.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_1/Interface_1_1.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_2/Interface_1_2.cpp, src/AppInstallerRepositoryCore/Public/winget/RepositorySearch.h
=> Improve correlation by keeping arch info declared in manifest arp DisplayName entry

.vsconfig
Tested importing the .vsconfig file to the VSinstaller on a clean vm and when I tried building winget, the `Microsoft.Management.Configuration` project failed due to this missing component. I added the component and retried it and I was able to build successfully. 
Changes:
Added: `Microsoft.VisualStudio.Component.Windows10SDK.19041` to .vsconfig file.
=> Add Windows10SDK 19041 Workload Component to VSConfig File

src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/Node-Types.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerSharedLib/AppInstallerStrings.cpp, src/AppInstallerSharedLib/Public/AppInstallerStrings.h, src/AppInstallerSharedLib/Public/winget/Yaml.h, src/AppInstallerSharedLib/Yaml.cpp, src/AppInstallerSharedLib/YamlWrapper.cpp, src/Microsoft.Management.Configuration.Processor/Extensions/PowerShellExtensions.cs, src/Microsoft.Management.Configuration.Processor/Extensions/ValueSetExtensions.cs, src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj, src/Microsoft.Management.Configuration.UnitTests/Tests/OpenConfigurationSetTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ValueSetExtensionsTests.cs, src/Microsoft.Management.Configuration/ConfigurationSetParser_0_1.cpp
- Add support to winget's YAML wrapper parser to assign a bool or int type for unquoted scalar values if can be converted. If a string is desired, then our recommendation will be to quote it.
- Fix configuration show output to print non string settings values, specifically ints and bools.
- Processor now handles arrays by checking if a value set contains a "treatAsArray" key.
- Add tests.
=> Add support for bool, strings and arrays in Configuration settings

src/AppInstallerCLITests/TestConfiguration.h, src/Microsoft.Management.Configuration.Processor/Unit/ConfigurationUnitProcessorDetails.cs, src/Microsoft.Management.Configuration.UnitTests/Helpers/TestConfigurationUnitProcessorDetails.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationDetailsTests.cs, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.idl
Add a new property IsPublic to IConfigurationUnitProcessorDetails.
Set it to true if the repository source location is one of the public repositories. For now, it's only the PSGallery source.
=> Add isPublic to IConfigurationUnitProcessorDetails

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/Filesystem.cpp, src/AppInstallerCLITests/Runtime.cpp, src/AppInstallerCLITests/TestCommon.cpp, src/AppInstallerCLITests/TestCommon.h, src/AppInstallerCLITests/main.cpp, src/AppInstallerCLITests/pch.h, src/AppInstallerCommonCore/Filesystem.cpp, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Runtime.cpp
This change fixes two bugs with display paths:
1. The recent change to use case insensitive ICU for directory name equality inverted the comparison, making the replacement not happen correctly.
2. The recent change to enable display paths generically left them marked for creation, resulting in errors if directories that required administrator privileges to create did not exist and were requested from an unelevated context (ex. run `winget --info` from medium IL process when the portable machine links location(s) did not exist).
In addition, I tried to generally make `forDisplay` apply broadly since it is now allowed to be requested on any path.
`winget --info` now contains the expected output instead of an error (2) or the full paths containing the user's account name (1).
A few unit …
=> Fix bugs with display paths

src/Microsoft.Management.Configuration/Telemetry/Telemetry.cpp
Mark the configuration system telemetry events as critical for now, as this increases the sampling rate.  This is only needed in the short term to help collect more data on how well the experimental feature is doing and can be changed back once the usage is high enough to not be concerned about the sampling rate any more.
=> Mark events as critical for now

src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSCatalogPackage.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSFoundCatalogPackage.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSInstalledCatalogPackage.cs, src/PowerShell/Microsoft.WinGet.Client/ModuleFiles/Format.ps1xml
In `Update-WinGetPackage`, the pipeline can set the `PSCatalogPackage` can be set by value or property name and the `Version` by property name.
The result of `Get-WinGetPackage` piped to `Update-WinGetPackage` results in both properties being set. In this case, the version is not the desired version to update but the installed version. Internally, when we iterate through all the available versions of the catalog package object we will throw InvalidVersionException because well the version is not available...
To fix it, I renamed the `Version` property of the `PSInstalledCatalogPackage` to `InstalledVersion` to mimic what the underlying catalog package property actually is. This way the version will not be piped into `Update-WinGetPackage` but the caller can also specify which one it wants …
=> Fix PSInstalledCatalogPackage being piped to Upgrade-WinGetPackage

src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/Common/PackageCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/Common/FinderCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/Common/PackageCommand.cs
Change the single package targeting commands in the client PS module to operate like the single package targeting commands in `winget.exe`.  That is to say, use case-insensitive equality and the Id/Name/Moniker fields only for the search.
=> Fix a few issues with the single package targeting commands

src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/WinGetPackageManagerCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Common/WinGetIntegrity.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/GitHubRelease.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/TempFile.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Microsoft.WinGet.Client.Engine.csproj
`Add-AppxPackage -Path <vclibs urls>` fails in Windows Sandbox. This change detects it and download the package and installs is from a file path. 
Add more debug information to Repair and Assert cmdlets.
=> Repair-WinGetPackage download VCLibs if needed

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Fixes #2052 
Make entitlement acquisition best effort rather than required. A recent change caused some issues for us regarding the entitlement process, and since the entitlement isn't actually required to install, just attempt to get it and log if it failed.  Even if the underlying issue is resolved, this change will prevent future issues from having the same level of impact.
This may lead to an issue where the entitlement acquisition fails, the package is installed, but attempting to run it fails because the entitlement cannot be acquired then either (by the OS in the background).  Given the choice between the two failure modes though, it seems far better to remove these false negatives and create the (my gut says fewer) false positives that will result.
Manually verified that I can get …
=> Make entitlement best effort

src/AppInstallerCLICore/Commands/ConfigureCommand.cpp
Adds `configuration` as an alias for the `configure` command.
=> Add configuration alias

.github/actions/spelling/expect.txt, src/AppInstallerCLITests/Strings.cpp, src/AppInstallerSharedLib/AppInstallerStrings.cpp, src/Microsoft.Management.Configuration.Processor/Constants/DirectiveConstants.cs, src/Microsoft.Management.Configuration.Processor/Constants/PowerShellConstants.cs, src/Microsoft.Management.Configuration.Processor/Helpers/ConfigurationUnitAndResource.cs, src/Microsoft.Management.Configuration.Processor/Helpers/ConfigurationUnitInternal.cs, src/Microsoft.Management.Configuration.Processor/Helpers/PowerShellHelpers.cs, src/Microsoft.Management.Configuration.Processor/Helpers/SemanticVersion.cs, src/Microsoft.Management.Configuration.Processor/ProcessorEnvironments/HostedEnvironment.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationUnitInternalTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/PowerShellHelperTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/SemanticVersionTests.cs
This PR allows a configuration file to have a boolean allowPrerelease directive to use prerelease DSC resources.
```
properties:
configurationVersion: 0.2
resources:
- resource: FakeModule/FakeResource
directives:
version: '1.0.0-preview'
allowPrerelease: true
settings:
Args: 'args'
```
Internally, allow prerelease is used only for a module that it needs to get install. When is enabled, the processor will use `-AllowPrerelease` to the Find-DscResource command. 
It also fixes and infinite loop in `SplitIntoLines`. If the found offset is the one of "\r\n", it uses the same offset for `pos` in `find_first_of`, so it keeps returning the offset making `nextOffset - currentOffset = 0`
I don't know why VisualStudio decided to change a character...
=> Allow prerelease modules for configuration

.github/actions/spelling/expect.txt, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/CompleteWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/GetWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/GetWinGetConfigurationDetailsCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/InvokeWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/StartWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Helpers/Utilities.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Commands/AsyncCommand.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Commands/ConfigurationCommand.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSConfigurationProcessor.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSConfigurationSet.cs
When a Start-* cmdlet starts its operation it won't write to any PowerShell stream because control is returned back to the user almost immediately.  This changes queue messages to be then displayed at Continue-* time. This way, we will have all the messages in the appropriate order. It applies for WriteDebug, WriteVerbose, WriteWarning, WriteError and WriteProgress. 
WriteProgress will only be called when the activity hasn't been completed. A caller must use `AsyncCommand.GetNewProgressActivityId` to generate a new activity id.
=> Queue write operations for Start-* cmdlets and hook up diagnostics

src/AppInstallerSharedLib/Errors.cpp
Not all the error codes had a friendly message associated. This PR adds them.
-----
=> Add Friendlier Messages for Error Codes

src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Microsoft.WinGet.Client.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/FinderPackageCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/InstallerPackageCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/SourceCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/UninstallPackageCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Properties/Resources.Designer.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Properties/Resources.resx
These cmdlets are not suported on Windows PowerShell
- Find-WinGetPackage
- Get-WinGetPackage
- Get-WinGetSource
- Install-WinGetPackage
- Uninstall-WinGetPackage
- Update-WinGetPackage
=> Explicity not support cmdlets in Windows PowerShell

src/Microsoft.Management.Configuration.Processor/Constants/PowerShellConstants.cs, src/Microsoft.Management.Configuration.Processor/DscModules/DscModuleV2.cs, src/Microsoft.Management.Configuration.UnitTests/Fixtures/UnitTestFixture.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/DscModuleV2Tests.cs
Update to [PSDesiredStateConfiguration  2.0.7](https://www.powershellgallery.com/packages/PSDesiredStateConfiguration/2.0.7).
With this change, winget configure will download the 2.0.7 automatically.
This version contains a fix where Invoke-DSCResource failed when a class based resource is going to be invoke and it lives in a path with spaces on it. [Bug details](https://github.com/PowerShell/PSDesiredStateConfiguration/issues/73)
=> Update PSDesiredStateConfiguration module min version to 2.0.7

src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Acl/WinGetAssemblyLoadContext.cs
Microsoft.WinGet.Client throws `System.InvalidOperationException:“Attempt to update previously set global instance.”` when used in winget configure with a resource from Microsoft.WinGet.DSC
This is because the custom AssemblyLoadContext implemented by the client module loads WinRT.Runtime.dll into the same processes where the configuration server already have WinRT.Runtime.dll loaded. When there are multiple versions of WinRT.Runtime.dll loaded in process this exception gets thrown. [More info](https://github.com/microsoft/CsWinRT/issues/623)
The fix is to always load WinRT.Runtime.dll into the default assembly context, if its not loaded by the time our handler is executed and always return null in the Load implementation of the custom ALC. 
This is a problem any PowerShell module that …
=> Microsoft.WinGet.Client throws System.InvalidOperationException: Attempt to update previously set global instance

src/AppInstallerCLICore/ContextOrchestrator.cpp, src/AppInstallerRepositoryCore/Microsoft/PredefinedWriteableSourceFactory.cpp
Packages with dependencies were not being indexed into the database (unless one also happened to install the dependency tree ahead of them).  This was causing both an error to install and future installation attempts to fail.
Disable dependency indexing for the installing database, and on a failure to index the manifest, remove the item from the queue.
=> Fix packages with dependencies being installed via COM

Localization/Resources/de-DE/winget.resw, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
The spelling mistake on the screenshot will be fixed with this pull request.
There was a missing space.
=> Fix spelling mistake in german

src/JsonCppLib/JsonCppLib.vcxproj, src/PureLib/PureLib.vcxproj, src/Xlang/UndockedRegFreeWinRT/src/UndockedRegFreeWinRT/UndockedRegFreeWinRT/UndockedRegFreeWinRT.vcxproj, src/Xlang/UndockedRegFreeWinRT/src/UndockedRegFreeWinRT/detours/detours.vcxproj, src/YamlCppLib/YamlCppLib.vcxproj, src/cpprestsdk/cpprestsdk.vcxproj
Disabling compilation warnings from external projects as we're probably not going to do anything about them and they hide other warnings we do care about, like static analysis results.
=> Disable warnings in external projects

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLITests/UserSettings.cpp, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerCommonCore/UserSettings.cpp
Some users may not want their paths to be replaced with environment variables when displayed. This PR adds a setting to control whether the paths are tokenized or not. 
-----
=> Add User Setting controlling Path Tokenization

src/AppInstallerCommonCore/pch.h, src/AppInstallerRepositoryCore/pch.h, src/AppInstallerSharedLib/pch.h, src/WinGetUtil/pch.h
An uninitialized variable warning from a buffer that is intentionally not initialized for performance reasons.
=> Fix new warning C26495 from wil header in VS 17.6

.configurations/configuration.dsc.yaml, .github/actions/spelling/expect.txt, README.md
Added .configurations/configuration.dsc.yaml
Update README.md
-----
=> Add WinGet configuration

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLIE2ETests/FeaturesCommand.cs, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
=> Make --uninstall-previous argument stable

src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
Build pipeline had a recent update that started treating CS8785 as an error instead of warning. Modified .csproj file so that the warning does not break the build.
=> Treat warning not as error for CS8785

src/AppInstallerCLITests/Downloader.cpp, src/AppInstallerCommonCore/HttpStream/HttpClientWrapper.h, src/AppInstallerCommonCore/HttpStream/HttpLocalCache.cpp, src/AppInstallerCommonCore/HttpStream/HttpLocalCache.h, src/AppInstallerCommonCore/Public/AppInstallerDownloader.h
Fixes #3297 (based on crash reports + code review + issue report alignment)
There is a bug in this stream implementation that allows it to attempt to read past the end of the stream if requested.  That aligns with the issue reports, which appear to be crashes in the attempt to update the source information, which uses this code.  It also aligns with the crash reports, which show an access violation on a page boundary when reading from the stream.
Ensures that the trim start location is at least not past the end of the given buffer.  Ensures that the `array_view` will not reference bytes past the end of the given buffer.
Added a new test to ensure that we get the number of bytes expected based on the stream size (the 0 byte file issue persists, so I put a retry loop on the test).
=> Don't read past the end of the HTTP stream

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Commands/PinCommand.h, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLIE2ETests/Pinning.cs, src/AppInstallerCLITests/CompositeSource.cpp, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/AppInstallerRepositoryCore/CompositeSource.cpp
This removes the experimental feature gating the use of pinning to make it a stable feature. Credit to @ryfu-msft for this piece
It also adds a missing check for an edge case that the tests check. It wasn't being hit before because the pinning feature wasn't enabled for that test. Specifically, `CompositeSource_NullAvailableVersion` checks that we don't fail if the available version of a package is null; the pinning feature added checking for the pins after search, and when doing that it would access the available version without checking if it existed. This shouldn't have that much of an effect on users since we always keep populate the available version/source when we have an available package in the composite.
=> Make pinning a stable feature

src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj, src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
Update references from packages used by Microsoft.PowerShell.SDK 7.2.8 because of Component Governance alerts.
- System.Security.Cryptography.Pkcs 6.0.1 -> 6.0.3
- Microsoft.Windows.Compatibility 6.0.1 -> 6.0.6
=> Fix Component Governance alerts

src/AppInstallerCLITests/TestSource.cpp, src/AppInstallerCLITests/TestSource.h, src/AppInstallerRepositoryCore/Microsoft/ConfigurableTestSourceFactory.cpp, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp, src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp, src/AppInstallerRepositoryCore/Microsoft/PredefinedWriteableSourceFactory.cpp, src/AppInstallerRepositoryCore/PackageTrackingCatalog.cpp, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/Rest/RestSourceFactory.cpp, src/AppInstallerRepositoryCore/SourceFactory.h
* Group Policy for disabling the default sources was not respected when getting the catalogs through COM. Added missing check for GP.
* When we add a source and there is a Group Policy for allowed sources, we check the source details against the list of allowed sources. In this check we compare the types, but do a direct comparison without considering that an empty type defaults to the preindexed type. Meaning that if we had preindexed source S as allowed, we would accept `winget source add --type Microsoft.PreIndexed.Package S ...` but not `winget source add S ...`. Fixed this by resolving the source type name before getting to this point.
=> Respect Group Policies for sources

doc/troubleshooting/README.md
=> Network troubleshooting

WinGetUtil.nuspec, azure-pipelines.nuget.yml
Nuget publish pipeline failed with out of disk space. Modified to use the same strategy as the build pipeline (build each arch separately).
Sample run without actual publishing is at https://dev.azure.com/ms/winget-cli/_build/results?buildId=471734&view=results
=> Fix wingetutil nuget publish pipeline

.github/actions/spelling/expect.txt, azure-pipelines.yml, src/AppInstallerCLICore/COMContext.cpp, src/AppInstallerCLICore/ConfigurationSetProcessorFactoryRemoting.cpp, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCLIE2ETests/TestCommon.cs, src/AppInstallerCLIE2ETests/WinGetSettingsHelper.cs, src/AppInstallerCommonCore/FileLogger.cpp, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/AppInstallerSharedLib/Public/winget/SharedThreadGlobals.h, src/AppInstallerSharedLib/SharedThreadGlobals.cpp, src/Microsoft.Management.Configuration.OutOfProc/Collect-ConfigurationOOPTests.ps1, src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj, src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj.filters, src/Microsoft.Management.Configuration.OutOfProc/Prepare-ConfigurationOOPTests.ps1, src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp, src/Microsoft.Management.Configuration/ConfigurationProcessor.h, src/Microsoft.Management.Configuration/ConfigurationSet.h, src/Microsoft.Management.Configuration/ConfigurationUnit.h, src/WindowsPackageManager/ConfigurationStaticFunctions.cpp
Collect all of the logs from the E2E test runs, rather than just the logs from the last one of them run.
Re-enable crash dumps on E2E tests runs.
Collect logs and crash dumps from OOP configuration tests as well.
Fixes for the following issues:
1. Asynchronous functions in OOP configuration need to keep a reference to the object
a. Done using `get_strong` at the top of each async function
2. Thread globals being set and then switching threads in `OpenConfigurationSetAsync` (via `co_await`)
a. Done by not using `co_await` and instead polling the operation and cancelling it if we are cancelled
3. `Diagnostics` delegates need to keep a reference to the processor
a. Done by capturing `get_weak` into the lambda that we pass along to the factory
4. Diagnostics failures can lead to a recursion …
=> Improve packaged test log collection and fix crash

src/AppInstallerCommonCore/FileLogger.cpp
The issue was found during the work to pull latest wingetutil to winget service. Winget service has unit tests that reuse a same log file. After the fix, winget service unit tests passed.
=> Explicitly close file stream on FileLogger destruction

src/AppInstallerCLITests/Certificates.cpp, src/AppInstallerCLITests/GroupPolicy.cpp, src/AppInstallerCLITests/HttpClientHelper.cpp
StoreLeaf1.cer expired today. This is a band-aid until 3/22/24.
Real fix should be using certs that expire in a long long time, but I don't want to keep PRs broken.
=> Fix using expired cert in tests

schemas/JSON/manifests/v1.6.0/manifest.defaultLocale.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.installer.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.locale.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.singleton.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.version.1.6.0.json
- Resolves #3475
This does not upgrade the Settings Schema as it is not reliably versioned
* #2963 
and it also does not upgrade the packages schema, as I felt it was not appropriate to create an entirely new schema version just for a base schema upgrade
The reason for changing to `defs` is based on the semi-incompatibility from draft 2019-09 and for better adherence to the standard.
> The old syntax for these keywords is not an error (and the default meta-schema still validates them), so implementations can therefore offer a compatibility mode. However, migrating to the new keywords is straightforward and should be preferred.
-----
=> Upgrade 1.6 schema to 2020-12

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Argument.h, src/AppInstallerCLICore/Commands/ListCommand.cpp, src/AppInstallerCLICore/Commands/ListCommand.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Allow using `--include-unknown` and `--include-pinned` when using `winget list --upgrade-available`. Also block those args from being used without `--upgrade-available`
Solves #3456
=> Allow `--include-unknown` in list `--upgrade-available`

src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
AppInstallerCLICore requires just the Microsoft.Management.Configuration.Processor.winmd to compile, but in order to find it in the build server the Microsoft.Management.Configuration.Processor project needs to be a dependency of AppInstallerCLICore because we can't edit the build order. Because of that, the output binaries are copied into the core project and when the package is created, all the files are incorrectly in the root of the package.
This change address that by explicitly not copying the output binaries via project references.
=> Don't copy processor's output binaries

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
We have been getting reports of heap corruption crashes on `AppInstaller::Logging::TelemetryTraceLogger::InitializeInternal` in calls to the COM API, with a recent spike in number of hits.
This is probably due to trying to initialize the trace logger from two places at the same time ~~, so I'm adding synchronization there.~~
I was unable to get a repro to confirm this was the issue and test that the change fixed it, so it may not actually do anything. See https://task.ms/38253096
Edit: Changed per @johnmcpms suggestion.
* Made `m_isSettingEnabled` a `CopyConstructibleAtomic<bool>`
* Changed `m_isSettingEnabled` default value to `false`, so that we only set it to `true` after successfully readin the settings
* Moved `m_userProfile` to be a static in `AnonymizeString()`. This function is …
=> Attempt to prevent crash in `TelemetryTraceLogger::InitializeInternal()`

src/Microsoft.Management.Configuration.Processor/Constants/PowerShellConstants.cs, src/Microsoft.Management.Configuration.Processor/Helpers/IPowerShellGet.cs, src/Microsoft.Management.Configuration.Processor/Helpers/PowerShellGetV2.cs, src/Microsoft.Management.Configuration.Processor/ProcessorEnvironments/HostedEnvironment.cs, src/Microsoft.Management.Configuration.Processor/ProcessorEnvironments/IProcessorEnvironment.cs
- Creates new `IPowerShellGet` and provide a 2.2.5 implementation. This will make it easier for us to move to v3 when released.
- Use `Import-CliXml` instead of `Get-InstalledModule`. We will now get the information we need for modules that were installed via `Install-Module` and `SaveModule`.
=> PowerShellGet 

src/AppInstallerCLICore/Workflows/PortableFlow.cpp, src/AppInstallerCLIE2ETests/Helpers/TestCommon.cs
* Partially #3437
This should work for renaming whenever the portable is a loose binary, or when it is not inside of a directory in a zip file. With the way directory extraction works with Zip files, I wasn't able to add just a file entry to move the file since the Desired State entries are not guaranteed to process in order. I'd like some guidance on how that should be handled, perhaps that should be a separate PR?
-----
=> Rename file in single portable installs

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/Commands/ShowCommand.cpp, src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLIE2ETests/Constants.cs, src/AppInstallerCLIE2ETests/Helpers/WinGetSettingsHelper.cs, src/AppInstallerCLIE2ETests/InstallCommand.cs, src/AppInstallerCLIE2ETests/Interop/InstallInterop.cs, src/AppInstallerCLIE2ETests/ShowCommand.cs, src/AppInstallerCLIE2ETests/TestData/Manifests/TestMultipleInstallers.yaml, src/AppInstallerCLITests/ManifestComparator.cpp, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/Microsoft.Management.Deployment/InstallOptions.cpp, src/Microsoft.Management.Deployment/InstallOptions.h, src/Microsoft.Management.Deployment/PackageManager.cpp, src/Microsoft.Management.Deployment/PackageManager.idl
Resolves #1166 
Changes:
- Adds the `--installer-type` argument to the Install, Upgrade, and Show command.
- Modifies settings schema to allow for installer type preferences and requirements.
- Added the corresponding argument to the COM InstallOptions.
- Updated the manifest installer comparator to handle both installer type preferences and requirements.
Tests:
- Unit tests to verify the manifest comparator when providing the installerType arg, preference, and requirements.
- E2E tests to verify the behavior for COM install, Install, and Show.
=> Add support for `--Installer-Type` argument for commands

src/AppInstallerCommonCore/MSStore.cpp, src/Microsoft.Management.Configuration/ConfigurationStaticFunctions.cpp, src/Microsoft.Management.Configuration/ConfigurationStaticFunctions.h, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.idl, src/Microsoft.Management.Deployment/PackageManager.cpp, src/WindowsPackageManager/ConfigurationStaticFunctions.cpp
Winget configuration is not going to be enabled by default. The user needs to opt-in by calling `winget configuration --enable`.  Callers that are interested in using the OOP Microsoft.Management.Configuration APIs need a way to ensure configuration is enabled and enable it if not. This PR address that.
- `IsConfigurationEnabled` - Checks if the configuration is enabled by checking if the current AppInstaller package is the stub or full package.  Inproc implementation always returns true.
- `EnableConfigurationAsync` - Asynchronously enables configuration. This changes the stub preference to full package and calls our own APIs to install AppIntaller. By design, this also updates AppInstaller to the newest version.
Callers need to understand that this is effectively saying "winget please …
=> Enable configuration via IConfigurationStatics

.github/actions/spelling/allow.txt, src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Commands/ValidateCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIE2ETests/TestData/Manifests/TestWarningManifest.yaml, src/AppInstallerCLIE2ETests/ValidateCommand.cs, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
- Resolves #3405
I wasn't sure whether or not to go with a new exit code, or keep it as a 0 exit code as mentioned in the linked issue. I ended up deciding to go with what was written in the issue as it seemed like a very specific use case. If a non-zero exit code would be a better option, I was thinking that `--suppress-warnings` could be separated from `--ignore-warnings` where ignoring completely ignores them and suppressing will hide the output but return a new exit code if there were warnings that were suppressed.
-----
=> Add argument for ignoring warnings

.github/actions/spelling/expect.txt, src/AppInstallerCLIE2ETests/Helpers/TestCommon.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/Common/OpenConfiguration.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/CompleteWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/GetWinGetConfigurationDetailsCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/InvokeWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/StartWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Commands/ConfigurationCommand.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Exceptions/ApplyConfigurationException.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Exceptions/ErrorCodes.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Exceptions/ErrorRecordErrorId.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Exceptions/GetDetailsException.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Exceptions/OpenConfigurationSetException.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Helpers/ApplyConfigurationSetProgressOutput.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Helpers/ConfigurationSetProgressOutputBase.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Helpers/GetConfigurationSetDetailsProgressOutput.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Helpers/OpenConfigurationParameters.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Helpers/Utilities.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSApplyConfigurationSetResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSApplyConfigurationUnitResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSConfigurationApplyUnitResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSConfigurationJob.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSConfigurationSet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSConfigurationUnitState.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSGetConfigurationDetailsResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSUnitResult.cs, src/PowerShell/tests/Microsoft.WinGet.Configuration.Tests.ps1
- Add tests for Microsoft.WinGet.Configuration cmdlets.
- Make parameters positional parameters
- Return an object with the Apply results for Invoke-WinGetConfiguration and Complete-WinGetConfiguration using Write-Error or returning the same PSConfigurationSet object.
=> Microsoft.WinGet.Configuration E2E Pester tests

doc/admx/en-US/DesktopAppInstaller.adml
**[WHY:]**
The previous GPO description for "Set App Installer Source Auto Update Interval In Minutes" was not clear and it was often confused with auto-update of application in the connected sources.
**[WHAT:]**
The GPO Policy description for "Set App Installer Source Auto Update Interval In Minutes" has been updated to make it clearer.
Related to 46419598
**[How Validated:]**
- Patched updated AMDL (adn AMDX) on a test machine
- Launched gpedit
- Confirmed the updated description in reflecting on the GPO
-----
=> SourceAutoUpdateInterval - Group Policy Description update.

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Workflows/DependenciesFlow.cpp, src/AppInstallerCLIE2ETests/FeaturesCommand.cs, src/AppInstallerCLIE2ETests/InstallCommand.cs, src/AppInstallerCLITests/WindowsFeature.cpp, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
Enabling a windows feature does not work in packaged context. Making this feature experimental again until a workaround is implemented.
=> Make windows feature experimental

src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/CompleteWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/ConfirmWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/GetWinGetConfigurationDetailsCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/InvokeWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/StopWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Cmdlets/TestWinGetConfigurationCmdlet.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Commands/AsyncCommand.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Commands/ConfigurationCommand.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Exceptions/OpenConfigurationSetException.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Extensions/IAsyncOperationExtensions.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Helpers/TestConfigurationSetProgressOutput.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Helpers/Utilities.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSConfigurationTestResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSTestConfigurationSetResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSTestConfigurationUnitResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSValidateConfigurationSetResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/PSObjects/PSValidateConfigurationUnitResult.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Resources/Resources.Designer.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Resources/Resources.resx, src/PowerShell/Microsoft.WinGet.Configuration/ModuleFiles/Microsoft.WinGet.Configuration.psd1, src/PowerShell/tests/Microsoft.WinGet.Configuration.Tests.ps1
- `Test-WinGetConfiguration` to test a configuration. Equivalent of `winget configure test`
- `Confirm-WinGetConfiguration` to validate a configuration. Equivalent of `winget configure validate` except it just calls the configuration APIs without the extra validation winget does.
- Support cancellation via CTRL-C for blocking cmdlets and `Stop-WinGetConfiguration` for configuration stated with `Start-WinGetConfiguration`
- Add tests for `Test-WinGetConfiguration` and `Confirm-WinGetConfiguration` cmdlets.
- Add more tests for `Open-WinGetConfiguration`
- Cancellation verified manually
=> Add new cmdlets and cancellation support for Microsoft.WinGet.Configuration

src/AppInstallerRepositoryCore/Microsoft/ARPHelper.cpp
Despite the look of the diff on github, this change only adds two try/catch blocks to the upgrade code parsing code to prevent failures from propagating out.  The upgrade codes are just additional data to help with correlations and should not cause additional user impact beyond not being present.
The outer block protects against the primary key throwing, as well as the subkey enumeration.
The inner block protects against a single upgrade code key throwing, while allowing the loop to potentially continue.
Code inspection only.
=> Add try/catch when reading upgrade codes

src/AppInstallerSharedLib/GroupPolicy.cpp, src/AppInstallerSharedLib/Public/winget/Registry.h, src/AppInstallerSharedLib/Registry.cpp
When enumerating registry keys, move the code that reads the registry value data to be on request rather than during the iterator advancement.  This enables code that doesn't need the data to simply skip it, and code that does to better handle the error if desired.
Regression only.
=> Read registry value data on demand

src/AppInstallerCommonCore/HttpStream/HttpClientWrapper.cpp
Manually verified user agent is set in http range requests
=> Set default user agent for http range requests

.github/actions/spelling/expect.txt, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerCommonCore/Public/AppInstallerDownloader.h, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp, src/AppInstallerSharedLib/Public/AppInstallerVersions.h, src/AppInstallerSharedLib/Versions.cpp
This change refactors the index package updating to enable an optimization; using an HTTP header to determine the available version rather than reading the package contents remotely.  If the header is present, containing a valid package version string, it will be used as the available version.  If not, the existing package content examination will be used.
The refactoring was required to do all package inspection steps after downloading the package, rather than before.  This enables the single version value to be sufficient until we decide to update, and then in the very unlikely event of the package not meeting criteria we will delete it after having downloaded it.
This also implemented the `TODO` of checking the origin of the package before deploying it rather than after.
Manually …
=> Improve packaged source updating

src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/pch.h
When we fail to add/update a source, make the retry time random rather than fixed.
Manually tried adding an invalid URL a few times to observe the effective wait time via logs.  Was always in the distribution specified.
=> Add a bit of randomness to the wait time after source update failure

.github/actions/spelling/expect.txt, src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.h, src/AppInstallerRepositoryCore/Microsoft/SQLiteStorageBase.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteStorageBase.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface_1_0.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToManyTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToManyTable.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/OneToOneTable.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_1/Interface.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_1/Interface_1_1.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_2/Interface_1_2.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_6/Interface_1_6.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_7/Interface.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_7/Interface_1_7.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/MetadataTable.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/MetadataTable.h, src/AppInstallerRepositoryCore/SQLiteStatementBuilder.cpp, src/AppInstallerRepositoryCore/SQLiteStatementBuilder.h, src/AppInstallerRepositoryCore/pch.h
This change seeks to reduce the size of the index in two ways:
1. Better schema design for the 1:N mapping tables
2. Dropping some of the mapping data that is not particularly interesting per manifest (aka per version)
This is achieved by the map table having no `rowid` and using a primary key with the value first.  This makes the table already sorted by the value, thus the reverse lookups are fast.  It also drops a fair amount of the data in the table itself to remove the `rowid`, given that it was ~1/3 of the rows.
We don't actually use the fact that we know that different versions have different tags (or any other data).  Thus, we can simply have one manifest entry per package identifier have all of the values and maintain the same functionality.  There is a slight loss of fidelity if …
=> Reduce the size of the index

.github/actions/spelling/expect.txt, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h, src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/Microsoft.Management.Deployment/Helpers.cpp, src/Microsoft.Management.Deployment/Helpers.h, src/Microsoft.Management.Deployment/PackageCatalogReference.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.h, src/Microsoft.Management.Deployment/PackageManager.cpp, src/Microsoft.Management.Deployment/PackageManager.h, src/Microsoft.Management.Deployment/PackageManager.idl, src/Microsoft.Management.Deployment/pch.h
- Add telemetry event for PackageManager class creation
- Delay source update time to 7 days by default when invoked from explorer
- Also fixes Source agreements related crash found when doing the above work
=> Log Com invocation startup telemetry and delay auto update time when invoked from explorer

src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.h, src/Microsoft.Management.Deployment/PackageManager.idl
This change adds a flag that lets the caller specify that they are only interested in the installed tracking data, not the available packages.  With it set, one can correlate to the catalog via the tracking database without ever needing to access the remote source information.
Code inspection and manually confirmed that remote search results are not required to have a correlated package signature.
=> Enable COM API access to correlate with the tracking database only

src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp
I have seen the header detection fall back exactly one time unexpectedly.  It did not fail (no throw in the try/catch block), and I was running Fiddler and saw the header present.
Because it happening to me once could me happening in the wild thousands or millions of times, this change folds the case of the headers to ensure that they are in fact lower case and adds logging to dump the headers to make it easier to diagnose in case it ever happens again.
Still works, but since I have no idea why it failed the one time, I can't really say it has been resolved.  Hopefully that means it was a special case.
=> Improve the version header detection and logging

.github/actions/spelling/expect.txt, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerCommonCore/Public/AppInstallerDownloader.h, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp, src/AppInstallerSharedLib/Public/AppInstallerVersions.h, src/AppInstallerSharedLib/Versions.cpp
=> Cherry pick 3657 to 1.6

src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp
=> Cherry pick 3680 into 1.6

src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.h, src/Microsoft.Management.Deployment/PackageManager.idl
Decided we don't need this currently.
=> Revert 3670

src/AppInstallerCommonCore/AppInstallerTelemetry.cpp, src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h, src/Microsoft.Management.Deployment/PackageManager.cpp, src/Microsoft.Management.Deployment/PackageManager.h
Verified correct caller name is used from inspecting the log.
=> Use correct caller name in Com startup telemetry event

src/AppInstallerCLITests/Sources.cpp, src/AppInstallerRepositoryCore/SourcePolicy.cpp
Validation: verified locally with the fix, AppInstaller was able to open external dependency source and test package can be successfully installed.
=> Platform source should not be blocked by policy check

src/AppInstallerCLITests/CompositeSource.cpp, src/AppInstallerCLITests/TestSource.cpp, src/AppInstallerCLITests/TestSource.h, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/ISource.h, src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp, src/AppInstallerRepositoryCore/Rest/RestSource.cpp, src/AppInstallerRepositoryCore/Rest/RestSource.h
This change lets the source implementation indicate whether manifests might contain more information than the search results.  It then only applies that to REST, as the implementation is not under our control.  This should have no net effect on the results quality, but should not attempt to retrieve manifests from the winget source when they are not providing any additional value currently.
Manually ensured no manifest retrieved for winget based package lookup in dev when one was done for the current release.
=> Make manifest retrieval choice more dynamic

src/AppInstallerCLICore/Commands/InstallCommand.cpp
- Resolves #3578
Since the argument is only applicable when the install flow is converted to the upgrade flow, added as a hidden argument to avoid confusion
-----
=> Allow --include-unknown with install

.github/actions/spelling/expect.txt, src/AppInstallerCommonCore/PathVariable.cpp
When the Path variable is updated, the changes are not always picked up by the shell. Even when all CMD, Terminal, Powershell, and Bash windows are closed, it may rarely happen that the new values of the environment variable are not used. There is a workaround for this where users can go to edit the Path variable, make no changes, and click "Okay" to force the refresh.
According to [Microsoft Learn](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-settingchange?wt.mc_id=WDIT-MVP-5005084) - the `WM-SETTINGCHANGE` message should be broadcast when policy settings have changed. And, looking specifically at the page on [Environment Variables](https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables?wt.mc_id=WDIT-MVP-5005084) it says -
> To programmatically add …
=> Broadcast WM_SETTINGCHANGE on change of path

src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs, src/PowerShell/scripts/Initialize-LocalWinGetModules.ps1
Rather than looking for the explicit version of the VCLibs dependency, this change allows any version greater than or equal to satisfy the installed check.
This does not resolve the fact that we are using a hardcoded version, nor that we are not checking for the same set of architectures that we would install.
Also fixes the helper script to import the dev modules directly so that it can be used even when the release modules are present in the module path.
Stepped through to confirm, added debug output as well.
=> Allow higher versions to satisfy the VCLibs dependency in Repair

src/JsonCppLib/JsonCppLib.vcxproj
The .vcxproj file is missing a conditional property to use the toolset v143 when building with VS v17.0 for arm. This causes the build to always use v142 for arm, which would fail if we only have VS v17.0 available and we don't have toolset v142.
Added the conditional property following the same pattern as all other architectures.
=> Add missing condition for using toolset v143 when building JsonCppLib for arm

src/AppInstallerCLICore/Workflows/DependenciesFlow.cpp, src/AppInstallerCLITests/InstallDependenciesFlow.cpp
=> Skip dependency evaluation with `--skip-dependencies`

src/AppInstallerCLICore/Commands/InstallCommand.cpp, src/AppInstallerCLICore/Commands/UpgradeCommand.cpp, src/AppInstallerCLICore/Workflows/ImportExportFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.h, src/AppInstallerCLICore/Workflows/PromptFlow.cpp, src/AppInstallerCLICore/Workflows/PromptFlow.h, src/AppInstallerCLICore/Workflows/UpdateFlow.cpp
=> Download and install Workflow patches for skip dependencies

src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj, src/WinGetServer/WinGetServer.vcxproj, src/Xlang/UndockedRegFreeWinRT/src/UndockedRegFreeWinRT/UndockedRegFreeWinRT/UndockedRegFreeWinRT.vcxproj
Fixes the following errors related to binskim:
- Enables ControlFlowGuard for WinGetServer
- Links binaries for Microsoft.Management.Configuration and UndockedRegFreeWinRT projects with `/DEBUGTYPE:CV,FIXUP`
=> Fix binskim issues

schemas/JSON/manifests/v1.6.0/manifest.defaultLocale.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.installer.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.locale.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.singleton.1.6.0.json, schemas/JSON/manifests/v1.6.0/manifest.version.1.6.0.json
Reverts #3478 
The [library](https://github.com/RicoSuter/NJsonSchema/issues/1536#issuecomment-1618186985) that winget-create depends on to convert the json schema to C# model classes does not support json schema 2020-12, specifically the new `$defs` keyword.
Although we should be updating to the latest schema, we need to unblock winget-create in order to support updating 1.6 manifests. In the meantime, we will need to find an alternative library/solution that can be utilized by winget-create
=> Revert manifest schemas to json draft-07

src/AppInstallerCLICore/Commands/TestCommand.cpp, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLIE2ETests/AppShutdownTests.cs, src/AppInstallerCLIE2ETests/Helpers/TestCommon.cs, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/AppShutdown.cpp
There's bug in the OS where the WM_QUERYENDSESSION message is not send when a package is being updated if the package is running elevated. This makes `winget configure --enable` to stop at 95% and eventually get terminated by the system for an update. The update is successful, but the experience is not the best. It also makes it harder to use `IConfigurationStatics::IConfigurationStatics` in an elevated context.
The fix is to use the `PackageCatalog` APIs and register for `PackageUpdating` events when winget is running elevated and in a package context and signal the competition event if the progress is more than 0. Otherwise create the window and listen to messages.
Enable test where a new update is being registered since now it will work and move test to force the WM_QUERYENDSESSION to …
=> Fix signaling the app shutdown event running as admin

doc/windows/package-manager/winget/export.md, doc/windows/package-manager/winget/hash.md, doc/windows/package-manager/winget/import.md, doc/windows/package-manager/winget/index.md, doc/windows/package-manager/winget/install.md, doc/windows/package-manager/winget/list.md, doc/windows/package-manager/winget/search.md, doc/windows/package-manager/winget/show.md, doc/windows/package-manager/winget/source.md, doc/windows/package-manager/winget/uninstall.md, doc/windows/package-manager/winget/upgrade.md, doc/windows/package-manager/winget/validate.md
Added new command flags, aliases, and updated usage for winget commands. To match latest version of winget
-----
=> Update docs for winget commands

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/cpprestsdk/cpprestsdk.vcxproj
MSVC introduced a deprecation break in 17.8 for the `stdext::checked_array_iterator` used in cpprestsdk.  It can be removed when they actually pull the extension, but for now just ignore the warning.
=> Ignore deprecation warning

src/AppInstallerRepositoryCore/CompositeSource.h, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
This fixes the recent build errors in the pipelines. The compiler was complaining about re-throwing an exception with `throw e;` instead of `throw;`, which messes with the stack trace. Presumably it started because of a tool update in the agents.
This also fixes a compilation error I'm seeing locally from a member not being initialized.
=> Fix pipeline build error

src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/Common/PackageCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/InstallerPackageCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/UninstallPackageCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSInstallResult.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSUninstallResult.cs, src/PowerShell/Microsoft.WinGet.Client/ModuleFiles/Format.ps1xml, src/PowerShell/tests/Microsoft.WinGet.Client.Tests.ps1
Resolves: #3824 
Modifies the output of the install/update/uninstall result to display the id, name, and source of the package so that it is easier to correlate the result with the package. I wanted to also display the installed version but that would require calling the Get-WinGetPackage command and passing in the arguments.
=> Add package id, name, and source to install/update/uninstall result for PowerShell cmdlet

src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLICore/Workflows/ManifestComparator.h, src/AppInstallerCLITests/ManifestComparator.cpp, src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
Rather than a `bool`, the installer comparison function now returns one of three values: negative, weak positive, and strong positive.  The comparison functions are updated to choose between weak and strong positive results as appropriate.  For instance, matching the system architecture when the alternative does not is a strong positive result.  Simply being "better" in the list of emulated architectures is a weak positive result.
The function that used these comparators in our priority order is updated to effectively do multiple passes, one looking for strong results and then one looking for weak results (in reality it is implemented with one pass as an optimization).
Added a test to ensure that { System Architecture, Unknown Scope } is chosen over { Emulated Architecture, User Scope } …
=> Introduce strong and weak comparisons between installers

src/AppInstallerCLICore/Workflows/DownloadFlow.cpp
=> Update comment around MotW application

src/AppInstallerRepositoryCore/CompositeSource.h, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
This fixes the recent build errors in the pipelines. The compiler was complaining about re-throwing an exception with `throw e;` instead of `throw;`, which messes with the stack trace. Presumably it started because of a tool update in the agents.
This also fixes a compilation error I'm seeing locally from a member not being initialized.
=> Fix pipeline build error (#3937)

src/AppInstallerRepositoryCore/CompositeSource.h, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
This fixes the recent build errors in the pipelines. The compiler was complaining about re-throwing an exception with `throw e;` instead of `throw;`, which messes with the stack trace. Presumably it started because of a tool update in the agents.
This also fixes a compilation error I'm seeing locally from a member not being initialized.
=> Cherry-Pick from #3937 - Fix pipeline build error

schemas/JSON/manifests/v1.7.0/manifest.installer.1.7.0.json, schemas/JSON/manifests/v1.7.0/manifest.singleton.1.7.0.json, src/AppInstallerCLITests/TestData/ManifestV1_7-Singleton.yaml, src/AppInstallerCLITests/TestData/MultiFileManifestV1_7/ManifestV1_7-MultiFile-Installer.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp, src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp, src/AppInstallerCommonCore/Manifest/YamlWriter.cpp, src/AppInstallerCommonCore/Public/winget/ManifestCommon.h, src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h
Add YAML manifest entries for winget repair behavior
Manifest Entries includes:
- The `Repair `switch, within `InstallerSwitch,` allows for custom repair of a package.
- The `RepairBehavior` enum field, present in the Installer & root level field, determines the repair behavior for the source package used to repair a package.
- Updated the test manifest (ManifestV1_7-MultiFile-Installer.yaml) and the test code that validate the Repair switch and RepairBehavior fields.
**[How Validated:]**
- Made the necessary changes to the manifest
- Ran the ManifestValidation tests that are part of AppInstallerCLITests and verified that all the tests passed
**[Test Result:]**
```
Filters: [ManifestValidation]
===============================================================================
All tests …
```
=> Repair switch support for V1.7 YAML manifest

src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp, src/AppInstallerCommonCore/Public/winget/ManifestYamlPopulator.h, src/AppInstallerCommonCore/pch.h, src/WinGetUtilInterop.UnitTests/APIUnitTests/SQLiteIndexUnitTests.cs
This PR uses `std::variant` instead of member pointers to manifest structs to be references used by the processing functions. `std::variant` contains pointers to manifest structs to be populated and is passed to the `FieldProcessInfo.ProcessFunc`. Each processing function is responsible of calling `std::get` or `std::get_if` with the correct pointer type. `ValidateAndProcessFields` takes the `std::variant` and pass it to the processing functions.
Processing functions that required the member types now take a pointer to the manifest struct. Some of these can go in the anonymous namespace, but I didn't want to add more moves.
The change will make implementing shadow manifests easier.
=> Use std::variant in ManifestYamlPopulator

src/AppInstallerCLICore/Workflows/PromptFlow.cpp, src/AppInstallerCLICore/Workflows/ShowFlow.cpp, src/AppInstallerCLICore/Workflows/ShowFlow.h
This PR  cleans up the install flow to make it easier for a user to see the agreements of the package. It does this by changing the install flow to not show fields that are unrelated to package agreements such as
- Moniker
- Description
- PackageUrl
- ReleaseNotes
- ReleaseNotesUrl
- InstallationNotes
- Documentations
- Tags
-----
Screenshots included below to show difference between old and new
<details>
<summary>Old MSStore Agreements Shown</summary>
</details>
<details>
<summary>New MSStore Agreements Shown</summary>
</details>
<details>
<summary>Old Local Manifest Agreements Shown</summary>
</details>
<details>
<summary>New Local Manifest Agreements Shown</summary>
</details>
-----
=> Show only agreement related info during install

src/AppInstallerCLITests/RestInterface_1_7.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/ManifestJSONParser.cpp, src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer.h, src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer_1_0.cpp, src/AppInstallerRepositoryCore/Rest/Schema/1_7/Json/ManifestDeserializer.h, src/AppInstallerRepositoryCore/Rest/Schema/1_7/Json/ManifestDeserializer_1_7.cpp
=> Winget client rest source parsing for 1.7 manifest

src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj, src/WinGetUtil/WinGetUtil.vcxproj
Remove unnecessary debug flags to unblock utils nuget release
Cherry pick from #4030
=> Remove debug flags to unblock utils nuget release (#4030)

doc/specs/#658 - WinGet Download.md
There were miss-placed double quotes in the section titled 'WinGet Setting - Default Download Output', see commit patches for exact location of this typo.
-----
=> Fix typo in '#658 - WinGet Download.md' Spec File

.github/actions/spelling/expect.txt, azure-pipelines.coverage.yml, azure-pipelines.yml, src/WinGetYamlFuzzing/OneFuzzConfig.json
This pipeline will be triggered after a onefuzz job is completed. That way the code coverage results can be reported back to the one fuzz team for analysis. 
I will need to check this in first before I can create the corresponding ADO pipeline. Then update the onfuzzconfig to point to the correct pipeline id. Once that is completed, this pipeline should work and submit our code coverage results.
=> CodeCoverage pipeline for submission to onefuzz.

azure-pipelines.yml
Informed by fuzzing team that only one architecture is required for fuzzing. 
Also starting two fuzzing jobs at the same time seems to cause a conflict where one job cancels the other. This should resolve that issue.
=> Remove x86 platform from fuzzing pipeline

schemas/JSON/settings/settings.schema.0.2.json
-----
settings.schema.0.2.json does currently not validate against the JSON 2019-09 schema draft, although it claims it does.
uniqueItems should be a boolean, not a string: https://json-schema.org/draft/2019-09/json-schema-validation#rfc.section.6.4.3
maxLength should be an integer, not a string: https://json-schema.org/draft/2019-09/json-schema-validation#rfc.section.6.3.1
After these changes, it does validate.
Tested before/after with https://www.jsonschemavalidator.net/
=> Fix settings.schema.0.2.json not validating against schema

azure-pipelines.yml, src/AppInstallerCLITests/TestCommon.cpp
Fixes a test error that would crash the process due an exception from a destructor (in test code).
Changes the tasks that run these tests to use `condition: succeededOrFailed()` rather than `continueOnError: true`, as the latter results in a warning rather than the formers error.
=> Fix test error and change pipeline to properly report test crash

src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Microsoft.WinGet.Client.Engine.csproj, src/PowerShell/Microsoft.WinGet.Client.Engine/Properties/Resources.Designer.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Properties/Resources.resx
Fixes an issue with Repair-WinGetPackageManager not installing the correct version of Ui.Xaml (2.8.6) which is required by the latest release (1.7.10582)
Also I checked the commit history and the minimum version that has the update to v2.8.6 for UI.Xaml is our RC candidate 1.7.10514
=> Update Repair-WinGetPackageManager with UiXaml 2.8

src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Microsoft.WinGet.Client.Cmdlets.csproj
Forgot to declare semver as one of the copied dependencies which is required for Repair-WinGetPackageManager
=> Copy semver.dll to direct dependencies

src/AppInstallerRepositoryCore/CompositeSource.cpp
Related to #4217
Rather than only the first package that matches the source criteria, return the first version that exists on a package matching the source.
=> Allow all packages to check for a version

src/PowerShell/CommonFiles/PowerShellCmdlet.cs
A cmdlet can use `PowerShellCmdlet.ExecuteInPowerShellThread` to request operations to run in the PowerShell thread and wait for it to be completed. Internally, the action gets executed and we store the exception in the `ExceptionDispatchInfo` member object instead of throwing it immediately. This is to preserve the stack properly and facilitate diagnostics via Get-Error.
If the cmdlet catches that exception and attempts to use the PowerShell thread again, it will end up in a deadlock because the semaphore was never released. This PR release semaphore after throwing the stored exception.
This was the case in `AppxModuleHelper.AddAppxPackageAsUriAsync` when `Add-AppxPackage` failed installing the package from a url.
=> Fix PowerShellCmdlet

src/AppInstallerCLITests/Sources.cpp, src/AppInstallerRepositoryCore/SourceList.cpp
Rather than a failure here, we will treat corrupt source data as simply empty.  The only recourse the user currently has is to delete it anyway, and COM callers have no means to mitigate it.
 
Regression tests.
=> Ignore corrupted source data

.github/actions/spelling/allow.txt, azure-pipelines.yml, src/AppInstallerCLI.sln, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCLICore/pch.h, src/AppInstallerCommonCore/Debugging.cpp, src/AppInstallerCommonCore/Public/winget/Debugging.h, src/Microsoft.Management.Configuration.OutOfProc/Prepare-ConfigurationOOPTests.ps1, src/WinGetServer/Utils.cpp, src/WinGetServer/Utils.h, src/WinGetServer/WinGetServerManualActivation_Client.cpp, src/WinGetServer/WinMain.cpp
Improve this named event creation by having both sides try to create or open it.  The current version will almost always have to sleep at least once while the server sets up and can completely fail if it takes too long.  With this change, we should be able to properly wait for startup on the first attempt.
Manual verification of functionality with a sleep introduced to ensure failure of previous code.
=> Better server start coordination

src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/ExecutionArgs.h
- Resolves https://github.com/microsoft/winget-cli/issues/4284
-----
=> Remove duplicates from MultiQuery

src/AppInstallerCommonCore/Public/winget/AdminSettings.h
There was an issue with the AppInstaller build because the header definition for GetAdminSettingPolicy is not defined because of the macro. Removing the macro as this is the simplest fix to resolve this issue.
=> Remove macro condition for GetAdminSettingPolicy

src/AppInstallerCommonCore/Public/winget/AdminSettings.h
Overlooked this extra macro, verified in appinstaller build by disabling test macros
=> Fix header for AdminSettings

README.md, azure-pipelines.yml, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/ConfigurationSetProcessorFactoryRemoting.cpp, src/AppInstallerCLIPackage/AppInstallerCLIPackage.wapproj, src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj, src/ConfigurationRemotingServer/Program.cs, src/Microsoft.Management.Configuration.OutOfProc/Prepare-ConfigurationOOPTests.ps1, src/Microsoft.Management.Configuration.Processor/Extensions/ValueSetExtensions.cs, src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj, src/Microsoft.Management.Configuration.Processor/Properties/AssemblyInfo.cs, src/Microsoft.Management.Configuration.Processor/Public/PowerShellConfigurationSetProcessorFactory.cs, src/Microsoft.Management.Configuration.Processor/Set/ConfigurationSetProcessor.cs, src/Microsoft.Management.Configuration.Processor/Unit/ConfigurationUnitProcessor.cs, src/Microsoft.Management.Configuration.Projection/Microsoft.Management.Configuration.Projection.csproj, src/Microsoft.Management.Configuration.UnitTests/Helpers/Errors.cs, src/Microsoft.Management.Configuration.UnitTests/Helpers/OutOfProcAttribute.cs, src/Microsoft.Management.Configuration.UnitTests/Microsoft.Management.Configuration.UnitTests.csproj, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationProcessorFactoryTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationSetProcessorTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationUnitProcessorTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ValueSetExtensionsTests.cs, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Microsoft.WinGet.Configuration.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Properties/AssemblyInfo.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Microsoft.WinGet.Configuration.Engine.csproj, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Properties/AssemblyInfo.cs, src/PowerShell/scripts/Initialize-LocalWinGetModules.ps1, tools/SampleWinGetUWPCaller/AppInstallerCaller/AppInstallerCaller.vcxproj
Added support for optional limitation set in configuration remote server and processors. When running in limitation mode, incoming units would need to match units in limitation set. And units can only be asserted or applied once.
Added tests. And some hacky manual verification. E2E tests will come along when calling side is updated in separate pr.
Also updated .net target OS version to 22000 to match other parts. (I thought there was a bug in IInputStreamAdaptor for MemoryStream)
=> Add support for optional limitation set in configuration remote server and processors

README.md, azure-pipelines.yml, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/ConfigurationSetProcessorFactoryRemoting.cpp, src/AppInstallerCLIPackage/AppInstallerCLIPackage.wapproj, src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj, src/ConfigurationRemotingServer/Program.cs, src/Microsoft.Management.Configuration.OutOfProc/Prepare-ConfigurationOOPTests.ps1, src/Microsoft.Management.Configuration.Processor/Extensions/ValueSetExtensions.cs, src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj, src/Microsoft.Management.Configuration.Processor/Properties/AssemblyInfo.cs, src/Microsoft.Management.Configuration.Processor/Public/PowerShellConfigurationSetProcessorFactory.cs, src/Microsoft.Management.Configuration.Processor/Set/ConfigurationSetProcessor.cs, src/Microsoft.Management.Configuration.Processor/Unit/ConfigurationUnitProcessor.cs, src/Microsoft.Management.Configuration.Projection/Microsoft.Management.Configuration.Projection.csproj, src/Microsoft.Management.Configuration.UnitTests/Helpers/Errors.cs, src/Microsoft.Management.Configuration.UnitTests/Helpers/OutOfProcAttribute.cs, src/Microsoft.Management.Configuration.UnitTests/Microsoft.Management.Configuration.UnitTests.csproj, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationProcessorFactoryTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationSetProcessorTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationUnitProcessorTests.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/ValueSetExtensionsTests.cs, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Microsoft.WinGet.Configuration.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Properties/AssemblyInfo.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Microsoft.WinGet.Configuration.Engine.csproj, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Properties/AssemblyInfo.cs, src/PowerShell/scripts/Initialize-LocalWinGetModules.ps1, tools/SampleWinGetUWPCaller/AppInstallerCaller/AppInstallerCaller.vcxproj
Cherry pick for #4349 into 1.7 release branch
=> Add support for optional limitation set in configuration remote server and processors #4349

src/AppInstallerCommonCore/MSStore.cpp, src/AppInstallerSharedLib/AppInstallerStrings.cpp, src/AppInstallerSharedLib/Public/AppInstallerStrings.h
After calling to InstallProductAsync, try to check status of existing install items and call Restart or Cancel if applicable.
After our operation failed, clean up the installation queue by calling cancel.
I manually validated by opening Store app, install a test app and pause the installation. Then use winget to install the same app. App installation failed before the change and succeeded after the change.
=> Improve MSStore installation success rate by trying Restart or Cancel when applicable

src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Resolver/ModuleInit.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/OperationWithProgressBase.cs, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Commands/ConfigurationCommand.cs
This PR enables arm64 for the Microsoft.WinGet.Client module.
There's an OS bug that causes an AV (see https://github.com/microsoft/winget-cli/pull/4251#issuecomment-1989102892) in arm64 devices that was fixed in a newer Windows build. The AV message is just shown for PowerShell Core. In Windows PowerShell no error message is displayed but it won't display progress either. Regardless, the winget install/uninstall operation still happens as the progress is shown after we asked winget to install the app. The configuration module doesn't get affected by the OS bug, so there's no need to disable progress.
To keep showing progress the module now looks at the OS version. If the processor architecture is arm64 and the OS version is lower than 10.0.26068.0 progress is disabled in the module.
I …
=> Enable Microsoft.WinGet.Client arm64 support

src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Resolver/ModuleInit.cs, src/PowerShell/scripts/Initialize-LocalWinGetModules.ps1
- Resolves: #4169
-----
This PR addresses an issue that prevents the WinGet Cmdlets from loading in an Arm64 PowerShell 7.x environment.
=> Add Arm64 to list of architectures in Module Initialization.

src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp, src/ConfigurationRemotingServer/Program.cs, src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp, src/Microsoft.Management.Configuration/ConfigurationSet.cpp
This work is done together with @ryfu-msft 
Tested and validated on both Ryan and my machine.
The issue is when InMemoryRandomAccessStream is used in ConfigurationRemoteServer, marshalling will complain about setting rpc security status too late. We fixed it by not using winrt InMemoryRandomAccessStream. Instead, we'll use System.IO.MemoryStream. ###### Microsoft Reviewers: [Open in
CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/4413)
---------
-----
=> Fix mixed elevation integration issue by using MemoryStream (#4413)

src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj
There's some issue with the build toolchain in internal pipeline that deep dependencies (3 level deep) are not picked up by the build. Explicitly adding the dependency fixed the issue. Manually validated the release package produced by internal pipeline and mixed elevation works as expected.
=> Explicitly add Microsoft.Management.Configuration as remoting server dependency

src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj
There's some issue with the build toolchain in internal pipeline that deep dependencies (3 level deep) are not picked up by the build. Explicitly adding the dependency fixed the issue. Manually validated the release package produced by internal pipeline and mixed elevation works as expected.
=> Explicitly add Microsoft.Management.Configuration as remoting server dependency (#4418)

.vsconfig, README.md
=> Update instructions to build repo locally with vcpkg enabled

src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp, src/Microsoft.Management.Configuration.UnitTests/Tests/OpenConfigurationSetTests.cs
To be consistent with other field names in configuration file. We may want to improve to be case insensitive of all field names in the future.
Verified manually too.
=> Make SecurityContext field name camelCase

.github/actions/spelling/allow.txt, .github/actions/spelling/expect.txt, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/ExecutionContext.h, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerSharedLib/AppInstallerLogging.cpp, src/AppInstallerSharedLib/Public/AppInstallerLanguageUtilities.h, src/AppInstallerSharedLib/Public/AppInstallerLogging.h
Fixes #4425 
This adds a `Workflow` channel (disabled by default) that has the entry to tasks and the `Get`/`Add`/`Contains` calls logged to it.  This enables a view into a flow that can be collected by a third party.
It also fixes a behavior change with the side-by-side code path for selecting the installed version that would lead to no data item being inserted, when the previous behavior was that a `nullptr` would be inserted when no version is installed.
Manual validation of the workflow output, including using the windbg command to see the function name (for function pointer tasks).
Manual validation of at least one case of the `GetVariant(14)` issue being fixed.
=> Add Workflow logs and fix installed version workflow bug

README.md
-----
Update README.md based on [GitHub's built in markdown highlighting](https://github.com/orgs/community/discussions/16925)
=> Use GitHub's built in markdown highlighting to highlight notes in README

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Workflows/DownloadFlow.cpp, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
=> Make proxy feature stable

.github/actions/spelling/expect.txt, azure-pipelines.yml, src/WinGetYamlFuzzing/OneFuzzConfig.json
Removed usage of PAT tokens for submitting fuzzing artifacts. Verified manually by running the CI pipeline and checking that the artifacts were successfully submitted.
=> Remove PAT token for ADO fuzzing task

tools/CorrelationTestbed/InSandboxScript.ps1, tools/CorrelationTestbed/InstallAndCheckCorrelation/InstallAndCheckCorrelation/InstallAndCheckCorrelation.vcxproj, tools/CorrelationTestbed/Test-CorrelationInSandbox.ps1
Migrates the toolset for the correlation exe and moves the scripts to use `Repair-WingetPackageManager` rather than the "manual" download of package and dependencies.
=> Update the correlation tools

azure-pipelines.yml, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj, src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj, src/WinGetUtil/WinGetUtil.vcxproj
For the projects that we have found this to be detrimental on, allow a property to control the `/debugtype`.  Re-enable the tests that were impacted.
=> Allow a property to force the /debugtype override onto some projects

src/AppInstallerCLICore/COMContext.cpp, src/AppInstallerCLICore/COMContext.h, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCLICore/Public/AppInstallerCLICore.h, src/Microsoft.Management.Deployment/PackageManagerSettings.cpp, src/WindowsPackageManager/main.cpp
With Inproc invocation, logging was only enabled at context level (during an actual package operation). This change initializes the global logger for inproc invocations so package catalog, package search and package correlation can be logged too.
Manually validated logs exist after the change.
=> Initialize logging of global logger for inproc invocations

azure-pipelines.yml, src/Microsoft.Management.Configuration/ConfigurationSetSerializer.cpp, src/Microsoft.Management.Configuration/ConfigurationSetSerializer.h, src/Microsoft.Management.Configuration/ConfigurationSetSerializer_0_2.cpp
The serialization code should not be modifying the object that it is operating on.  Move it to instead skip the output of some values rather than removing them.
When the remoting server is operating in limited mode, the metadata must match between the initial limitation set and the incoming unit.  This removal was also breaking that, as the entry was now missing.
Manual confirmation that the limit mode works after the change.
=> Fix limit mode metadata blocking

src/AppInstallerCommonCore/NetworkSettings.cpp
Fix issue when calling WinGetDownload from Az Functions.
It is most likely caused by an attempt to create the directory while reading the admin settings. Instead of failing, catch the exception and use the default settings.
If we ever read more settings from WinGetUtil a more robust solution is required.
=> WinGetDownload E_ACCESSDENIED

.github/actions/spelling/expect.txt, src/AppInstallerCLITests/MSStoreDownloadFlow.cpp, src/AppInstallerCommonCore/MSStoreDownload.cpp, src/AppInstallerCommonCore/Public/winget/MSStoreDownload.h
=> Enable Microsoft Entra Id auth for displaycatalog and use enterprise offline sku

azure-pipelines.yml, src/AppInstallerCLIE2ETests/FeaturesCommand.cs, src/AppInstallerCommonCore/Public/winget/UserSettings.h
Enable the v2 index experimental feature by default as it seems to be functioning properly and this will increase coverage.
=> Make v2 index EF enabled by default

src/AppInstallerSharedLib/Versions.cpp
-----
When parsing a version, it may be possible that a publisher included one or more whitespace characters at the end of the DisplayVersion key. Since a folder name cannot end with a whitespace character, this means that any PackageVersion in the community repository cannot have a trailing whitespace character.
Due to the way versions are parsed, the trailing whitespace gets considered as an "other" of the version part during the version comparison. This means that `5.8 ` is considered a lower version than `5.8` when parsed. 
This PR makes it so that when a version is assigned, as is the case when parsing the installed versions, both the final version and the version parts are trimmed of whitespace. This means that `5.0.13` is now considered equal to `5.0 .13`, `5.0.13 `, or even ` 5 . …
=> Trim Version When Parsing

src/AppInstallerCLITests/Versions.cpp
- #4554
-----
When creating #4554 I tested that it functioned manually. After the PR merged, however, I figured I should probably add some tests for it. I'm not entirely certain I understand how version parsing truly works, but figured I'd take a stab at making the tests anyways
=> Add Tests for Parsing Versions with Whitespace

src/AppInstallerCLICore/ExecutionContextData.h, src/AppInstallerCLICore/Workflows/DownloadFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/Deployment.cpp, src/AppInstallerCommonCore/MsixInfo.cpp, src/AppInstallerCommonCore/Public/AppInstallerDeployment.h, src/AppInstallerCommonCore/Public/AppInstallerMsixInfo.h, src/AppInstallerCommonCore/pch.h, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp
When available (10.0.23504.0 according to MSDN), use the MSIX digest APIs to verify the package during streaming installation.  When not available, download instead.
Manual installation successful, with logs indicating usage of digest.  Manual installation with debugger memory change to invalidate the digest results in an error (although not the best error experience, it should also be extremely rare).
Existing regression tests should get some coverage as well.
=> Use digest verification APIs for MSIX when available

src/PowerShell/Microsoft.WinGet.Client.Engine/Common/ErrorCode.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/ManagementDeploymentFactory.cs, src/WinGetServer/WinGetServerManualActivation_Client.cpp
Leverage the feature that allows launching a packaged process via its packaged executable location as long as there is a matching alias.  This better ensures that we are launching the correct process.
While the dev usage can't use this path due to the way it and development deployed packages work, the code to find the executable is being run to ensure correct functionality.  It is then replaced with the alias path that was being used previously.
=> Launch COM server for elevated use via packaged path

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/Workflows/DownloadFlow.cpp, src/AppInstallerCLITests/MSStoreDownloadFlow.cpp, src/AppInstallerCLITests/TestCommon.cpp, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
=> Make Store package download stable

.github/actions/spelling/expect.txt, src/AppInstallerCLIPackage/Package.appxmanifest, src/WinGetServer/WinMain.cpp
Change:
- Explicitly set COM access permissions for packaged com invocations. Leave access permissions as default and do not register COM objects for manual invocation so that only RPC channel can be used for manual activation.
- Update LaunchAndActivationString to allow Everyone and AppContainer only, require at least LowIL.
- Move Configuration to a separate COM server, only allow Everyone (No AppContainer access), require at least MediumIL.
A separate pr will be sent to update AppInstaller manifest.
Validation:
Validated manually with Microsoft Store invocation, Powershell invocation (elevated and non elevated), test sample code and Devhome invocation (on package management and configuration).
Also specifically validated Store invocation with Built-in Administrator sign-in (previously …
=> Update winget server com security

cgmanifest.json, src/YamlCppLib/libyaml/.github/workflows/dist.yaml, src/YamlCppLib/libyaml/.github/workflows/main.yml, src/YamlCppLib/libyaml/.gitignore, src/YamlCppLib/libyaml/.makefile, src/YamlCppLib/libyaml/Makefile.am, src/YamlCppLib/libyaml/examples/strings.yaml, src/YamlCppLib/libyaml/include/yaml.h, src/YamlCppLib/libyaml/pkg/ReadMe.md, src/YamlCppLib/libyaml/pkg/docker/.gitignore, src/YamlCppLib/libyaml/pkg/docker/Dockerfile, src/YamlCppLib/libyaml/pkg/docker/Makefile, src/YamlCppLib/libyaml/pkg/docker/output/ReadMe, src/YamlCppLib/libyaml/pkg/docker/scripts/libyaml-dist.sh, src/YamlCppLib/libyaml/src/parser.c, src/YamlCppLib/libyaml/src/scanner.c, src/YamlCppLib/libyaml/tests/run-emitter-test-suite.c, src/YamlCppLib/libyaml/tests/run-parser-test-suite.c, src/YamlCppLib/libyaml/tests/run-parser.c, src/YamlCppLib/libyaml/tests/test-reader.c, src/YamlCppLib/readme.md
Component governance fix: update libyaml
Since a new release has not been created since after 0.2.5, pull to latest master. I reviewed the commits and they look safe.
=> Component Governance fix: Update libyaml

src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp
Fixes #4587 
Hold the tracking catalog object in a `shared_ptr` and use the atomic functions to ensure that only one thread can initialize it.
=> Use atomic functions to ensure single initialization of tracking catalog

.github/actions/spelling/expect.txt, azure-pipelines.nuget.yml
=> Fix service connection for ESRP codesigning for utils nuget package

src/AppInstallerSharedLib/Public/winget/SQLiteStatementBuilder.h, src/AppInstallerSharedLib/SQLiteStatementBuilder.cpp, src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationProcessorApplyTests.cs, src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp, src/Microsoft.Management.Configuration/ConfigurationSequencer.cpp, src/Microsoft.Management.Configuration/ConfigurationSequencer.h, src/Microsoft.Management.Configuration/Database/ConfigurationDatabase.cpp, src/Microsoft.Management.Configuration/Database/ConfigurationDatabase.h, src/Microsoft.Management.Configuration/Database/Schema/0_1/Interface.h, src/Microsoft.Management.Configuration/Database/Schema/0_1/Interface_0_1.cpp, src/Microsoft.Management.Configuration/Database/Schema/0_2/Interface.h, src/Microsoft.Management.Configuration/Database/Schema/0_2/Interface_0_2.cpp, src/Microsoft.Management.Configuration/Database/Schema/0_2/QueueTable.cpp, src/Microsoft.Management.Configuration/Database/Schema/0_2/QueueTable.h, src/Microsoft.Management.Configuration/Database/Schema/IConfigurationDatabase.cpp, src/Microsoft.Management.Configuration/Database/Schema/IConfigurationDatabase.h, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj.filters, src/Microsoft.Management.Configuration/pch.h
Adds a queue table to the configuration database and some code to synchronize the application of configurations.
Every apply in the queue puts a row in the table, with its instance identifier (it should also be in the history) and a named object that it will keep alive as long as it is in the queue.  This allows for other queued processes to check for dead queue items.
A global named mutex must be held in order to apply, or even check if one is at the front of the queue.  If not at the front of the queue, the waiting operation will release the mutex and wait for N * 100ms where N is their perceived position in the queue.  This should prevent repeated contention on the global mutex as the queued items sort themselves via the wait.
Manual use with a configuration that allowed control of …
=> Configuration apply queueing

src/AppInstallerCLICore/Workflows/PromptFlow.cpp
- Resolves #4233 
This PR makes it so that the prompt is actually shown when a dependency contains agreements.
<details>
<summary>Manually Tested</summary>
```
PS C:\Users\Trenly> wingetdev install -m E:\winget-pkgs\manifests\m\Microsoft\ServiceFabricSDK\7.0.1949.9590
Found Microsoft Azure Service Fabric SDK [Microsoft.ServiceFabricSDK] Version 7.0.1949.9590
This package requires the following dependencies:
- Packages
Microsoft.VCRedist.2015+.x64
Microsoft.PowerBI
Microsoft.ServiceFabricRuntime
Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.130.930.0
Version: 2.130.930.0
Publisher: Microsoft Corporation
Publisher Url: …
```
=> Ensure Agreements don't terminate in dependency flow

src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/WinGetPackageManagerCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
Fixes #4337 
Before registering the package for repair, ensure that the dependencies are present and in good standing.  Fortunately, the existing function to install the dependencies does this, so we just call it.
Successfully repaired a machine in the state described in #4337 (provisioned, "registered" for the user, but Xaml 2.8 missing).
[Was not 100% successful since I forgot to build the production version and it wanted to find `wingetdev.exe`, but verified manually that the repair succeeded.]
=> Attempt to update dependencies when not registered

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp
=> Remove experimental from index v2

src/WinGetServer/WinGetServer.vcxproj, src/WinGetServer/WinGetServer.vcxproj.filters
Related to #4589 
Applies the existing shared manifest to the COM server executable.
=> Use shared manifest in COM server

src/AppInstallerSharedLib/Public/winget/Security.h, src/AppInstallerSharedLib/Security.cpp, src/Microsoft.Management.Deployment/Helpers.cpp, src/Microsoft.Management.Deployment/pch.h
The `Windows::Security::Authorization::AppCapabilityAccess::AppCapability` class was not added until the release after the current minimum supported version.  This causes a failure when using the COM API on RS5.
Check for the existence of `Windows::Security::Authorization::AppCapabilityAccess::AppCapability`, and if it is not present, simply force the caller to be at least medium integrity level.
Successful from both in-proc and OOP cases on an RS5 VM.
=> Fix for attempted use of capability API before it was introduced

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SECURITY.md
- Resolves #4619 
- Resolves #4635
-----
Took the branch from Skanda's fork, rebased it and dropped all commits not related to documentation, then squashed all the commits related to documentation
-----
=> Update documentation errors

src/vcpkg.json
Fixes a component issue with 8.4.0 by updating to latest version available
=> update curl vcpkg version to 8.8.0

src/PowerShell/CommonFiles/PowerShellCmdlet.cs
When run in PowerShell with MTA (multi-threaded apartment) enabled, the `RunOnMTA` methods have an optimization to run directly rather than spinning up a new thread.  This optimization used a `finally` to call `Complete`, but a `Task` will be returned (and the finally executed) before the task is completed.  This resulted in a completed collection and errors when attempting to add more messages to it.
```
Invoke-WinGetConfiguration: The collection has been marked as complete with regards to additions.
```
Use `ContinueWith` and `ExecuteSynchronously` to effectively make a `finally` for the `Task` result object.  Convert the existing `finally` to only call `Complete` on exception.
Manually confirmed the -MTA case with `Invoke` and `Start`/`Complete` command use cases.
=> Use ContinueWith rather than finally for coroutine result types

tools/CorrelationTestbed/InstallAndCheckCorrelation/InstallAndCheckCorrelation/InstallAndCheckCorrelation.cpp, tools/CorrelationTestbed/Readme.md, tools/CorrelationTestbed/Test-CorrelationInSandbox.ps1
- Fix comment in script about release build requirement
- Add metadata parameters to README
- Update metadata output version to latest value
=> Update metadata collection tooling

src/AppInstallerCLICore/Workflows/UninstallFlow.cpp, src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj, src/AppInstallerCLIE2ETests/TestData/Manifests/TestUpgradeAddsDependency.1.0.yaml, src/AppInstallerCLIE2ETests/TestData/Manifests/TestUpgradeAddsDependency.2.0.yaml, src/AppInstallerCLIE2ETests/TestData/Manifests/TestUpgradeAddsDependencyDependent.1.0.yaml, src/AppInstallerCLIE2ETests/UpgradeCommand.cs
We are seeing crashes from the installed package version being null, but only during upgrades with a dependency when attempting to uninstall said dependency (either due to user request or manifest).
Simply exit the two workflow tasks involved with the uninstall if the installed package version is not present.
Added a new test to exercise an upgrade that adds a dependency that is not installed and that dependency has `UpgradeBehavior: uninstallPrevious`.
=> Skip uninstall attempt when installed package version is not present

src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationProcessorTelemetryTests.cs, src/Microsoft.Management.Configuration/Telemetry/Telemetry.cpp
Write the `ConfigUnitRun` event on success as well, which helps us better understand the configuration units in use.
=> Send unit telemetry on success

src/SfsClient/readme.md, src/SfsClient/sfs-client/cgmanifest.json, src/SfsClient/sfs-client/vcpkg.json
Pulls in the latest commit from SFS client: be733af
Change includes an update to the curl vcpkg package from 8.8.0 to 8.9.1 to address a component governance issue.
https://github.com/advisories/GHSA-97c4-2w4v-c7r8
cURL / libcURL contains an out-of-bounds read flaw in the GTime2str() function in lib/vtls/x509asn1.c that is triggered when parsing a syntactically incorrect ASN.1 Generalized Time field. This may allow a context-dependent attacker to crash a process linked against the library or potentially disclose memory contents.
=> Pull in latest SFS client

azure-pipelines.yml, src/PowerShell/Help/Microsoft.WinGet.Client/Disable-WinGetSetting.md
Builds the help doc xml and includes it in the Microsoft.WinGet.Client powershell module. 
`New-ExternalHelp` cmdlet does verify if the docs are formatted correctly so this is more of a sanity check. Will update AppInstaller pipeline to do the same before publishing.
=> Generate Microsoft.WinGet.Client help docs in cmdlet output

src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLITests/ManifestComparator.cpp
Fixes #2565 
Move (and rename) the `InstalledTypeComparator` from being a comparator to just a filter.  Given what we can (or rather, currently do) actually discern from system state, it doesn't make sense to give preference to the few types that we use to signify the compatibility sets.  If we truly want to preserve installer type selection within a compatibility set, we need to store the user selection into the tracking database similar to `UserIntentArchitecture`.
Add a test for the case as called out by the issue; regression tests cover it as well and the only one that needed updating was relying on the intentionally changed behavior.
While this change is arguably "correct", it will cause different choices to be made if there are packages with multiple compatible installers that are …
=> Remove preference for "installed" installer type

src/vcpkg.json
Forgot to update our own vcpkg.json with the updated curl package 8.9.1
Related to: #4725
=> Update curl to 8.9.1

src/PowerShell/Help/Microsoft.WinGet.Client/Assert-WinGetPackageManager.md, src/PowerShell/Help/Microsoft.WinGet.Client/Reset-WinGetSource.md, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/AssertWinGetPackageManagerCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/Common/WinGetPackageManagerCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/RemoveSourceCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/RepairWinGetPackageManagerCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/ResetSourceCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Common/Constants.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Microsoft.WinGet.Client.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/CliCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/GitHubClient.cs, src/PowerShell/Microsoft.WinGet.DSC/Microsoft.WinGet.DSC.psm1, src/PowerShell/tests/Microsoft.WinGet.Client.Tests.ps1
Issue:
Reset-WinGetSource required a name which does not match the current behavior of `winget source reset`. 
Changes:
- Added '-All' parameter so that Reset-WinGetsource will reset all sources. I also created two separate parameter sets so that they can only be used separately.
- Made the '-Name' parameter also positional=0 for Reset-WinGetsource and Remove-WinGetsource (recommended by PowerShell docs team)
- Fixed the naming of PreRelease -> Prerelease as recommended by PowerShell docs team
-
=> Fix Reset-WinGetSource behavior

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerSharedLib/Errors.cpp
Fixes #3982 
Add support for externally defined HRESULTs to have a custom message.  Use this to provide a message for the errors associated with a Microsoft Store package being unavailable for the current system.
Manually confirmed that `GetUserPresentableMessageForHR` will get the intended message.
=> External HR error message support

.github/actions/spelling/expect.txt, doc/specs/#148 - Repair Support.md
This PR introduces the Design specification for the repair functionality in Windows Package Manager. This new feature will allow users to repair installed packages using the Windows Package Manager.
Related to:
* #148
-----
=> [Spec] Windows Package Manager Repair functionality Design spec

.github/actions/spelling/expect.txt, README.md
We moved our pipelines to a new ADO organization; this moves the status badge to point to it.
=> Update build status badge

azure-pipelines.yml, templates/e2e-setup.yml, templates/e2e-test.template.yml
Add `condition: succeededOrFailed()` to the tasks run in the e2e templates that were missing them.
=> Run test tasks if succeededOrFailed

src/VcpkgCustomTriplets/arm-release-static.cmake, src/VcpkgCustomTriplets/arm-release.cmake, src/VcpkgCustomTriplets/arm64-release-static.cmake, src/VcpkgCustomTriplets/arm64-release.cmake, src/VcpkgCustomTriplets/x64-release-static.cmake, src/VcpkgCustomTriplets/x64-release.cmake, src/VcpkgCustomTriplets/x86-release-static.cmake, src/VcpkgCustomTriplets/x86-release.cmake
Fixes a binskim error where sfsclient dependencies (curl -> ares)  were not getting compiled with a warning level > 3 compiler flag. Added `/W3` to only the release triplets
Verified that of WindowsPackageManager.dll no longer shows an error when running with binskim.
=> Binskim error EnableCriticalCompilerWarnings

azure-pipelines.yml
Currently forked builds do not have the permission to access secure files. 
To workaround using PsExec from a secure file, we will use a stable release of winget to install the latest PsTools and try invoking unit tests from the PsExec executable that is installed as part of the zip package.
=> Run Unpackaged Unit Tests with winget-installed PsExec

src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
Ensure that any VCLibs framework that is present satisfies the architecture requirements.
Fix not passing any version specification (`Version` or `Latest`) when we are double checking the dependencies during `Register`.
Manually validated success of these portions using Sandbox.
=> Repair-WinGetPackageManager improvements

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Commands/ConfigureCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/ConfigurationRemotingServer/Program.cs
To prevent anything from outputting to our console, call `FreeConsole` in the configuration server.
To allow for output of primarily results, when `--accept-configuration-agreements` is passed, one can now also pass `--suppress-prologue` to prevent the initial details from being presented.  The only output (beyond the temporary progress spinner+text) will then be the disclaimer warning and the individual results.
Confirmed that both changes work manually.
=> Allow for smaller configuration outputs

src/AppInstallerCLIE2ETests/ConfigureCommand.cs, src/AppInstallerCLIE2ETests/ConfigureShowCommand.cs, src/PowerShell/tests/Microsoft.WinGet.Configuration.Tests.ps1
These tests that rely on the PowerShell Gallery are unreliable.  Disable them.
=> PS Gallery tests are unreliable

src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/Microsoft.Management.Deployment/PackageCatalogInfo.cpp, src/Microsoft.Management.Deployment/PackageCatalogInfo.h, src/Microsoft.Management.Deployment/PackageManager.idl, src/PowerShell/Help/Microsoft.WinGet.Client/Add-WinGetSource.md, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/AddSourceCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/PSObjects/PSSourceTrustLevel.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/CliCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSSourceResult.cs, src/PowerShell/Microsoft.WinGet.Client/ModuleFiles/Format.ps1xml, src/PowerShell/tests/Microsoft.WinGet.Client.Tests.ps1
Adds support for `-TrustLevel` and `-Explicit`. 
The pwsh tests can now use the Add-winGetsource cmdlet to modify the trust level. 
Updated Get-WinGetsource to report the TrustLevel and Explicit flag.
Updated tests and docs to reflect these changes.
=> Add pwsh support for trust level and explicit

schemas/JSON/manifests/v1.9.0/manifest.installer.1.9.0.json, schemas/JSON/manifests/v1.9.0/manifest.singleton.1.9.0.json, src/AppInstallerCLICore/PortableInstaller.cpp, src/AppInstallerCLICore/PortableInstaller.h, src/AppInstallerCLICore/Workflows/PortableFlow.cpp, src/AppInstallerCLIE2ETests/Helpers/TestCommon.cs, src/AppInstallerCLIE2ETests/InstallCommand.cs, src/AppInstallerCLIE2ETests/TestData/Manifests/TestZipInstaller_Portable_BinariesDependOnPath.yaml, src/AppInstallerCLITests/TestData/ManifestV1_9-Singleton.yaml, src/AppInstallerCLITests/TestData/MultiFileManifestV1_9/ManifestV1_9-MultiFile-Installer.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestSchemaValidation.cpp, src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp, src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp, src/AppInstallerCommonCore/Manifest/YamlWriter.cpp, src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h
Related to: #2711 
Changes:
Added a new boolean field to the installer manifest called ArchiveBinariesDependOnPath. This field only applies to nested portables in an archive. When set to true, the portable installer will skip creating a symlink and automatically add the install directory to path. 
No manifest validation was added since this field only affected Portables in Archive and should not be blocking even if it doesn't apply. Willing to add a manifest validation warning if needed. 
Verified with an E2E test to make sure that the install directory path is added instead of the symlink directory. 
Tested with this package before and after the change to make sure that the portable works as expected: https://github.com/microsoft/winget-pkgs/pull/173679
=> Fix PATH issue for archive containing nested portables with binary dependencies

src/PowerShell/Microsoft.WinGet.Client/ModuleFiles/Microsoft.WinGet.Client.psd1, src/PowerShell/Microsoft.WinGet.Configuration/ModuleFiles/Microsoft.WinGet.Configuration.psd1, src/PowerShell/Microsoft.WinGet.DSC/Microsoft.WinGet.DSC.psd1
We want to be able to publish both prerelease and release version of the PowerShell modules.  For ease of use, we will consistently have the modules marked as prerelease here and only mark them as release as needed in our official builds.
=> Revert PowerShell modules to alpha

.github/actions/spelling/expect.txt, src/AppInstallerCLICore/Commands/ConfigureCommand.cpp, src/AppInstallerCLICore/Commands/RepairCommand.h
=> Add a few more command aliases

src/AppInstallerCLICore/PortableInstaller.cpp, src/AppInstallerCLITests/PortableInstaller.cpp
Resolves #3312
Fixes an issue when creating a symlink with a target path that includes unicode characters by converting the symlink target path to a UTF16 string prior to creation. 
Added a test that includes unicode characters in the symlink target path and verified that install and uninstall are both supported.
=> Fix issue with unicode characters in symlink target path

src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.h, src/Microsoft.Management.Deployment/ConnectResult.cpp, src/Microsoft.Management.Deployment/ConnectResult.h, src/Microsoft.Management.Deployment/FindPackagesResult.cpp, src/Microsoft.Management.Deployment/FindPackagesResult.h, src/Microsoft.Management.Deployment/PackageCatalog.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.cpp, src/Microsoft.Management.Deployment/PackageManager.idl
Adds `HRESULT ExtendedErrorCode{ get; };` to the `FindPackagesResult` and `ConnectResult` classes that did not have them.  They work just like the other cases, exposing the raw `HRESULT` value from their respective operations.
=> Add extended error codes to results without them

src/AppInstallerCLICore/VTSupport.h
Change the name of this enum value to comply with internal policy.
30+ year old terminal manuals...
=> Change enum value name

src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
Adds a `UseProdCLSIDs` MSBuild property to `USE_PROD_CLSIDS` preprocessor definition to CommonCore.
=> Enable USE_PROD_CLSIDS switch in CommonCore

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/DependenciesTable.cpp
Fixes #3679 
Makes the dependency lookup case insensitive.
Adds a new test that exercises adding a package with a dependency that does not match the case of the original package identifier.
=> Make dependency lookup case insensitive

doc/windows/package-manager/winget/source.md
-----
On the winget source documentation page, there is a missing supported source type, namely `Microsoft.Rest`. 
E.g. see the Winget [troubleshooting page](https://learn.microsoft.com/en-us/windows/package-manager/winget/troubleshooting#:~:text=%3E%20winget%20source%20add%20%2Dn%20mysource%20%2Dt%20Microsoft.REST%20%2Da%20https%3A//www.contoso.org%20%2D%2Dverbose) which shows examples of `Microsoft.Rest` usage.
=> Documentation - added `Microsoft.Rest` as a supported source type

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_5/Interface.h, src/AppInstallerRepositoryCore/Microsoft/Schema/1_5/Interface_1_5.cpp, src/WinGetUtil/Exports.cpp, src/WinGetUtil/Source.def, src/WinGetUtil/WinGetUtil.h, src/WinGetUtilInterop.UnitTests/APIUnitTests/SQLiteIndexUnitTests.cs, src/WinGetUtilInterop/Api/WinGetSQLiteIndex.cs, src/WinGetUtilInterop/Interfaces/IWinGetSQLiteIndex.cs
Implements two independent but related changes:
1. Makes adding/updating an overlapping ARP range a hard error
2. Adds `AddOrUpdate` functionality to the index so that callers don't need to know if the manifest is already present
Added/updated unit tests for ARP overlap.
Added unit and interop test for AddOrUpdate.
=> Make adding overlapping ARP range a hard error

doc/admx/DesktopAppInstaller.admx, doc/admx/en-US/DesktopAppInstaller.adml
=> Add ADMX policies for security features in App Installer

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.h, src/WinGetUtil/WinGetUtil.h, src/WinGetUtilInterop.UnitTests/APIUnitTests/SQLiteIndexUnitTests.cs, src/WinGetUtilInterop/Interfaces/IWinGetSQLiteIndex.cs
The requestor of this new (1.10) API needs to know whether the operation was an add or an update.  At the same time, the "was the index modified" return value from Update has always been true for any changes since the manifest hash was added.
Return `true` when adding and `false` when updating.
Updated the unit tests to reflect this semantic shift.
=> Change meaning of AddOrUpdate return bool

src/AppInstallerCLICore/Workflows/SourceFlow.cpp, src/AppInstallerCLIE2ETests/SourceCommand.cs, src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h, src/AppInstallerRepositoryCore/RepositorySource.cpp
Fix for Source Argument Validation in SourceWorkflow for Default Source Type
[Issues:] The current validation in the source flow correctly detects duplicate source names. However, when the source argument is validated along with the source type, it allows different source names with the same arguments for the empty source type. This happens because, during source type comparison, if the source type is not provided, it defaults to an empty string, which is compared against the default type (Microsoft.PreIndexed). This allows multiple different source names with the same argument to be considered valid sources. For an empty source type, the default source type is assigned during the source add operation, not beforehand. Consequently, after the source add operation is finished, the source …
=> Fix for Source Argument Validation in SourceWorkflow for Default Source Type

src/WinGetUtilInterop/scripts/CreateLocalNuget.ps1, src/WinGetUtilInterop/scripts/WinGetUtilDev.nuspec
Bringing back the nuspec used for creating the Microsoft.WindowsPackageManager.Utils nuget package.
Fix CreateLocalNuget.ps1
=> Bring back WinGetUtil nuspec for dev development

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/RestClient.cpp, src/AppInstallerCLITests/RestInterface_1_9.cpp, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/ManifestJSONParser.cpp, src/AppInstallerRepositoryCore/Rest/RestClient.cpp, src/AppInstallerRepositoryCore/Rest/Schema/1_9/Interface.h, src/AppInstallerRepositoryCore/Rest/Schema/1_9/Json/ManifestDeserializer.h, src/AppInstallerRepositoryCore/Rest/Schema/1_9/Json/ManifestDeserializer_1_9.cpp, src/AppInstallerRepositoryCore/Rest/Schema/1_9/RestInterface_1_9.cpp, src/AppInstallerRepositoryCore/Rest/Schema/CommonRestConstants.h, src/WinGetUtilInterop.UnitTests/ManifestUnitTest/V1ManifestReadTest.cs, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_9ManifestMerged.yaml, src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj, src/WinGetUtilInterop/Manifest/V1/Manifest.cs, src/WinGetUtilInterop/Manifest/V1/ManifestInstaller.cs
=> Add support for 1.9 manifest in rest source parsing and winget utils interop 

README.md, doc/troubleshooting/README.md, doc/windows-package-manager-release-roadmap.md, doc/windows/package-manager/winget/index.md
- Closes #4924
The previous URL seems to be returning 503.
cc @denelon
-----
=> Fix Microsoft Store's App Installer URL

src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/CliCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/UserSettingsCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/VersionCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/WinGetPackageManagerCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Common/WinGetIntegrity.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Extensions/ReleaseExtensions.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/PackageDependency.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/WinGetVersion.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/WingetCLIWrapper.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/WingetDependencies.cs, src/PowerShell/scripts/Initialize-LocalWinGetModules.ps1
This change address an issue with Repair-WinGetPackageManager not installing the correct version of VCLibs before installing winget. The reason this issue came up was because the aka.ms links for the VCLibs package are deprecated and now point to an out of date package. 
The solution here is to include both a `DesktopAppInstaller_Dependencies.json` and  `DesktopAppInstaller_Dependencies.zip` asset along with each release. Repair-WinGetPackageManager will look for those files and check what dependencies are required from the json file. If any of those dependencies are missing, it will download the zip, extract, and install the required binaries based on the system architecture. 
Testing:
Verified with the fresh Windows Sandbox install and trying out the assets on an earlier prerelease. …
=> Fix Repair-WinGetPackageManager cmdlet by retrieving dependencies from GitHub assets

src/PowerShell/Microsoft.WinGet.DSC/Microsoft.WinGet.DSC.psm1
Removes the attribute `ValidateNotNullOrWhiteSpace` as it is only available starting in 7.4.  The attributes also only validate when the value is assigned, so enforcing that a value is set is more complete.
Loads in PS 7.2.8 now.
=> Remove attribute in DSC

src/PowerShell/Microsoft.WinGet.DSC/Microsoft.WinGet.DSC.psm1
Removes the attribute `ValidateNotNullOrWhiteSpace` as it is only available starting in 7.4. The attributes also only validate when the value is assigned, so enforcing that a value is set is more complete.
Loads in PS 7.2.8 now.
=> Remove attribute in DSC (#4932)

doc/Settings.md
Update default source update time, which occurred during a 1.8 servicing update.
Add missing progress visualization options and include more information about all of them.
=> Update settings docs

src/AppInstallerCLITests/PackageTrackingCatalog.cpp, src/AppInstallerRepositoryCore/PackageTrackingCatalog.cpp, src/AppInstallerRepositoryCore/Public/winget/PackageTrackingCatalog.h
A previous change was made to block overlapping ARP ranges being put into the index.  The fact that this was potentially impactful to the tracking catalog was put off until now.
This change removes ARP version information (when present) from the manifest before placing it into the tracking catalog.  We are not using this data, and I don't see a reason that we would.  Attempting to preserve it would probably require removing all existing ARP version information when adding/updating the tracking manifest.
Added a test that to insert an overlapping range into the tracking catalog.
=> Don't put ARP version data into tracking catalog

src/AppInstallerCLITests/Dependencies.cpp, src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp, src/AppInstallerCommonCore/Public/winget/ManifestCommon.h
Likely fix for #4972
Use `std::optional` overloaded operator to handle all of the comparisons in `DependencyList::Add`.  The operator already properly handles all of the cases, including treating `std::nullopt` as always less than a defined value.
Also optimize a few other places around a reference to `MinVersion`.
Added a unit test covering the cases where `Add` needs to merge the minimum version value.
=> Better handling of min version merging in DependencyList

src/AppInstallerCLICore/COMContext.cpp, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj, src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj.filters, src/AppInstallerCommonCore/OutputDebugStringLogger.cpp, src/AppInstallerCommonCore/Public/winget/OutputDebugStringLogger.h
The user settings (and then group policy) initialization happen before we get the file logger set up.  To be able to see into what is happening there more easily, this change creates a logger that uses `OutputDebugString` and uses it during the initial file logger creation.
Debugged and saw the group policy and settings logging come through the output.
=> Add ODS logger and use it during init

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerCLITests/Versions.cpp, src/AppInstallerSharedLib/Public/AppInstallerVersions.h, src/AppInstallerSharedLib/Versions.cpp
- Resolves #4998 
When versions are created, any empty parts are trimmed off. This means that `22.0.0` is stored as `[22]` in memory. This causes an issue when comparing to a version that had additional parts, but should be sorted lower than the version which is trimmed, such as `22.0.0-rc`.  This is due to the comparator seeing that `[22]` has no more parts to compare after the first iteration, while `[22, 0, 0-rc]` does, causing it to hit the condition where whichever version has more parts is considered to be greater.
This PR updates the logic so that the version comparison effectively contains as many empty parts as are needed to fully complete the comparison. This retains the logic that if a part is not equal to the part it is being compared against, the result of that comparison …
=> "Pad" shorter versions with empty parts when comparing

src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
- Resolves #4382 
This PR adds a new string for configuration units to give additional clarity between the configuration set being applied successfully and each individual configuration unit being applied successfully
-----
=> Add separate string for successful configuration units

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json, src/AppInstallerCLICore/ConfigurationCommon.cpp, src/AppInstallerCLIE2ETests/ConfigureCommand.cs, src/AppInstallerCLIE2ETests/Constants.cs, src/AppInstallerCLIE2ETests/ErrorCommand.cs, src/AppInstallerCLIE2ETests/Helpers/WinGetSettingsHelper.cs, src/AppInstallerCLITests/UserSettings.cpp, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp
Changes:
- Adds a new settings object for `configureBehavior`
- Adds a new field for `defaultModuleRoot` that determines the default directory where modules are installed to.
Tests:
- Verify settings value is parsed correctly
- Added E2E test to check that the module is installed to the directory specified from the settings.json file.
=> Add default module root setting for configuration

src/AppInstallerCLITests/Versions.cpp
I wasn't sure offhand if these versions would parse to be equal. I went to look at the test cases and found there were no tests that ensured that leading zeroes were parsed correctly. This PR adds the tests for clarity
-----
=> Add tests for ensuring integers are parsed correctly with leading zeroes

schemas/JSON/manifests/v1.10.0/manifest.defaultLocale.1.10.0.json, schemas/JSON/manifests/v1.10.0/manifest.installer.1.10.0.json, schemas/JSON/manifests/v1.10.0/manifest.locale.1.10.0.json, schemas/JSON/manifests/v1.10.0/manifest.singleton.1.10.0.json, schemas/JSON/manifests/v1.10.0/manifest.version.1.10.0.json, src/AppInstallerCLITests/YamlManifest.cpp
Forgot to update the version for the description.
=> Update description for 1.10 schema

src/WinGetUtilInterop.UnitTests/ManifestUnitTest/V1ManifestReadTest.cs, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_1ManifestMerged.yaml, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_6ManifestMerged.yaml, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_7ManifestMerged.yaml, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_9ManifestMerged.yaml, src/WinGetUtilInterop/Manifest/V1/InstallerExpectedReturnCode.cs
=> Add missing ReturnResponseUrl to WinGetUtilInterop manifest

src/AppInstallerCLICore/Commands/RootCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Runtime.cpp
Adds the WinGet configuration modules location to `--info` table
-----
=> Add configuration modules path to '--info'

src/AppInstallerCommonCore/MSStoreDownload.cpp, src/AppInstallerCommonCore/Public/winget/NetworkSettings.h
Allows setting WinGet proxy setting as the SFS Client Proxy.
Fixes the issue below
[WinGet download doesn't work through a proxy #5030](https://github.com/microsoft/winget-cli/issues/5030)
This PR requires SfsClient subtree updated to 1.1.0
[SfsClient update 1.1.0 for proxy support #5052](https://github.com/microsoft/winget-cli/pull/5052)
Which brings especially
[Adding support for a custom proxy input #218](https://github.com/microsoft/sfs-client/pull/218)
This PR replaces closed PR below
[Allows setting WinGet proxy setting as SFS Client Proxy #5032](https://github.com/microsoft/winget-cli/pull/5032)
-----
=> Allows setting WinGet proxy setting as SFS Client Proxy

schemas/JSON/settings/settings.schema.0.2.json
In VSCode, I don't get Intellisense for all user settings fields. This seems to be because all fields are not defined under `allOf:`. PR adds missing fields under `allOf:` to enable intellisense. The diffs may be weird as it seems the file contains mixed line endings. I just let everything be in `LF` to avoid showing the whole file changed in git diff. Moved Source field up in `allOf:` to follow the same ordering as defined under `definitions:`
Manually validated that I'm getting intellisense for missing fields against the URL in my branch
-----
=> Enable intellisense for all user settings fields

azure-pipelines.yml, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj, src/AppInstallerCLIPackage/AppInstallerCLIPackage.wapproj, src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj, src/IndexCreationTool/IndexCreationTool.csproj, src/LocalhostWebServer/LocalhostWebServer.csproj, src/Microsoft.Management.Configuration.OutOfProc/Prepare-ConfigurationOOPTests.ps1, src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj, src/Microsoft.Management.Configuration.Projection/Microsoft.Management.Configuration.Projection.csproj, src/Microsoft.Management.Configuration.UnitTests/Helpers/OutOfProcAttribute.cs, src/Microsoft.Management.Configuration.UnitTests/Microsoft.Management.Configuration.UnitTests.csproj, src/Microsoft.Management.Configuration.UnitTests/Tests/OpenConfigurationSetTests.cs, src/Microsoft.Management.Deployment.Projection/Microsoft.Management.Deployment.Projection.csproj, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Microsoft.WinGet.Client.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Client.Engine/Microsoft.WinGet.Client.Engine.csproj, src/PowerShell/Microsoft.WinGet.Client/ModuleFiles/Microsoft.WinGet.Client.psd1, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Microsoft.WinGet.Configuration.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Microsoft.WinGet.Configuration.Engine.csproj, src/PowerShell/Microsoft.WinGet.Configuration/ModuleFiles/Microsoft.WinGet.Configuration.psd1, src/PowerShell/scripts/Initialize-LocalWinGetModules.ps1, src/WinGetSourceCreator/WinGetSourceCreator.csproj, src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj
.NET 6 and PowerShell SDK 7.2 are no longer supported.  This change updates the uses of the PowerShell SDK to 7.4 and all .NET 6 projects to .NET 8.
winget.exe configuration via the dev package and the PS modules locally.
The pipeline should cover the rest of the affected scenarios.
=> Update to .NET 8 and PS SDK 7.4

doc/specs/#163 - Dependencies.md, doc/specs/#182 - Support for installation of portable standalone apps.md, doc/specs/#364 - Feature Toggle.md, doc/windows/package-manager/package/winget-validation.md, doc/windows/package-manager/winget/features.md, doc/windows/package-manager/winget/validate.md
-----
This PR is a minor one. It solves some dead links in the documentation.
List of positives I couldn't find to solve:
List of potential false positives:
=> Solve dead links

src/AppInstallerCLICore/Core.cpp
The CLI arg validation code has gotten more complicated and now there is more room for exceptions to occur. For example, if there is an error when reading the admin settings or group policies that determine if an argument is available.
This adds generic exception handling at the top-level of arg validation so that we can exit gracefully and show an error, instead of just crashing.
Partial fix for #5098. This addresses the no output, but not the cause of the error
=> Add missing top-level exception handling for arg validation

src/AppInstallerCLITests/CustomHeader.cpp, src/AppInstallerCLITests/RestClient.cpp, src/AppInstallerCommonCore/Rest.cpp, src/AppInstallerRepositoryCore/Rest/RestClient.cpp, src/AppInstallerRepositoryCore/Rest/RestClient.h, src/AppInstallerRepositoryCore/Rest/RestSourceFactory.cpp
When the `RestSourceReference` retrieves the information, store it and pass it along to `RestClient::Create` so that it can reuse the value rather than calling again.
=> Store information result in RestSourceReference for reuse

src/AppInstallerCommonCore/Architecture.cpp
Due to legacy reasons, GetNativeSystemInfo() will return x64 when x86 binaries running on arm64 machines. IsWow64Process2 is the new api that'll correctly report host machine architecture.
=> Use IsWow64Process2 to determine system architecture

doc/Settings.md, schemas/JSON/settings/settings.schema.0.2.json
-----
This PR relates to issue #2899 and PR #4541
=> Add missing setting in schema

src/AppInstallerCLICore/Workflows/DownloadFlow.cpp
Manually validated cancel works without retrying.
Fixes #4943
=> Handle installer download cancelled case before retrying on zero byte download

src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/AddSourceCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/DisableSettingCmdlet.cs, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Cmdlets/EnableSettingCmdlet.cs
-----
This pull request adds the `ValidateSet` attribute for three cmdlets, which will help users quickly discover the available types or setting names.
=> Add validateset attribute for relevant cmdlets

src/AppInstallerCLICore/Argument.cpp, src/AppInstallerCLICore/Command.cpp, src/AppInstallerCLICore/Commands/DownloadCommand.cpp, src/AppInstallerCLICore/Commands/DownloadCommand.h, src/AppInstallerCLICore/Commands/ShowCommand.cpp, src/AppInstallerCLICore/ExecutionArgs.h, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp, src/AppInstallerCLICore/Workflows/ManifestComparator.cpp, src/AppInstallerCLICore/Workflows/WorkflowBase.cpp, src/AppInstallerCLIE2ETests/DownloadCommand.cs, src/AppInstallerCLIE2ETests/TestData/Manifests/TestMultipleInstallers.yaml, src/AppInstallerCLITests/MSStoreDownloadFlow.cpp, src/AppInstallerCommonCore/Architecture.cpp, src/AppInstallerCommonCore/Public/AppInstallerArchitecture.h, src/Microsoft.Management.Deployment/PackageManager.cpp
Also added Complete for Download command. Tested manually and added e2e tests.
=> Support any architecture for Download and Show command

src/Microsoft.Management.Deployment/PackageCatalog.cpp
Move to a background thread when running `FindPackagesAsync` to make it actually asynchronous.
=> Make async function actually async

src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCommonCore/ExperimentalFeature.cpp, src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h, src/AppInstallerCommonCore/Public/winget/UserSettings.h, src/AppInstallerCommonCore/UserSettings.cpp, src/AppInstallerSharedLib/Public/winget/Runtime.h, src/AppInstallerSharedLib/Runtime.cpp
Make self elevation stable and move to using the token elevation state to decide when to use it.
=> Make self elevation stable

.github/actions/spelling/expect.txt, src/AppInstallerCLITests/RestInterface_1_0.cpp, src/AppInstallerCommonCore/HttpClientHelper.cpp, src/AppInstallerCommonCore/Public/winget/HttpClientHelper.h, src/AppInstallerRepositoryCore/Rest/Schema/1_0/RestInterface_1_0.cpp
When searching for store source with id that's recently taken down, store source will return 404 instead of empty results (what winget-cli-restsource does). This will be treated as a source search error in our code. The fix is to treat 404 response with certain schema as empty result instead of failure.
Tested manually with store source and added unit tests.
fixes #4785, fixes #4784
=> Fix certain msstore source 404 failures by treating them as empty responses

src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp, src/Microsoft.Management.Configuration.Processor/Extensions/ValueSetExtensions.cs, src/Microsoft.Management.Configuration.UnitTests/Helpers/ValueSetExtensions.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/OpenConfigurationSetTests.cs, src/Microsoft.Management.Configuration/ConfigurationSet.cpp, src/Microsoft.Management.Configuration/ConfigurationSet.h, src/Microsoft.Management.Configuration/ConfigurationSetParser_0_3.cpp, src/Microsoft.Management.Configuration/ConfigurationSetParser_0_3.h, src/Microsoft.Management.Configuration/ConfigurationSetSerializer.cpp, src/Microsoft.Management.Configuration/ConfigurationSetSerializer.h, src/Microsoft.Management.Configuration/ConfigurationSetSerializer_0_3.cpp, src/Microsoft.Management.Configuration/ConfigurationSetSerializer_0_3.h, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.idl
In response to some other discussions, update the configuration environment behavior:
1. Add an environment at the set level
2. Don't inherit environment data into child units, and don't promote environment data when serializing
Updated the one consumer of environment (dynamic factory) to be responsible for the flow of the security context from the set to the immediate child units.
Also improved serialization of groups to output the non-resource properties.
=> Update configuration environment behavior

src/AppInstallerCLIE2ETests/ConfigureExportCommand.cs
When I was reviewing the pipeline runs, I always saw configure export test tear down time out when uninstalling the test package. Then I realized the test source was reset before we call uninstall and causing the package to be not found.
=> Fix configure export test tear down

src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj, src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj, src/Microsoft.Management.Configuration.UnitTests/Microsoft.Management.Configuration.UnitTests.csproj, src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Microsoft.WinGet.Client.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Client.Engine/Microsoft.WinGet.Client.Engine.csproj, src/PowerShell/Microsoft.WinGet.Configuration.Cmdlets/Microsoft.WinGet.Configuration.Cmdlets.csproj, src/PowerShell/Microsoft.WinGet.Configuration.Engine/Microsoft.WinGet.Configuration.Engine.csproj, src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj
According to the NuGet management tools in Visual Studio, `Newtonsoft.Json` had different versions being used across different projects within the solution. This PR bumps them all to the same version, moving some from `13.0.2`  up to `13.0.3`. In the cases where the version specification was added, it is due to the package being a transient dependency
-----
=> Update Newtonsoft.Json to be same version across all projects

src/AppInstallerCommonCore/HttpClientHelper.cpp, src/AppInstallerCommonCore/Public/winget/HttpClientHelper.h, src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/Common/FinderCommand.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/Exceptions/CatalogConnectException.cs
To better expose the underlying result code, convert the `http_exception` to a `ResultException` so that the HRESULT can be properly extracted.
Using the PowerShell module and interfering with my connection, I was able to see that the connect result's extended error was originally `8007023E`, but changed to the appropriate `80072EE2` with the change.
=> Convert cpprestsdk to WIL exception for better handling

src/Microsoft.Management.Deployment/PackageCatalog.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.cpp, src/Microsoft.Management.Deployment/PackageManager.cpp
Add forgotten lifetime extension for async function.
Changed the sample caller to call `FindPackagesAsync`, then destroy the catalog object.
=> For truly async calls we must maintain our lifetime

src/Microsoft.Management.Deployment/PackageCatalog.cpp, src/Microsoft.Management.Deployment/PackageCatalogReference.cpp, src/Microsoft.Management.Deployment/PackageManager.cpp
Add forgotten lifetime extension for async function.
Changed the sample caller to call `FindPackagesAsync`, then destroy the catalog object.
CP #5199
=> For truly async calls we must maintain our lifetime (1.10)

src/WinGetUtilInterop/WinGetUtilInterop.csproj
I know that NuGet packages are typically not updated unless there are CVEs, important bug fixes, or other specific need to. However, when reviewing the list of NuGet packages installed, I saw that YamlDotNet was several versions out of date. This package directly affects the parsing of manifests within WinGet and the associated utilities. Given that, I thought it best to update it, especially given the fact that 1.10 is preparing to go through the release cycle, which would give these changes enough time to be tested in the 1.11 previews and testing cycles.
This change only directly updates the top-level project - `WinGetUtilInterop`. I'm expecting that all the other projects which have this NuGet package as a transient dependency will pick up this new version, as all of them have a …
=> Update YamlDotNet to Latest

src/AppInstallerRepositoryCore/CompositeSource.cpp
Fixes #5202 
When moving the primary package to a new location, update the index so any future attempts to reference it target the correct location.
=> Update primary index when moving package

src/AppInstallerCLITests/Versions.cpp, src/AppInstallerSharedLib/Versions.cpp
- #5211
I don't know whether or not this will resolve the above issue, but I also don't think it can hurt?
Instead of relying on the parameters to be in the correct order for minimum and maximum when creating a VersionRange, the code can instead just put them in the right order.
-----
=> Don't rely on parameter order when creating VersionRange

src/AppInstallerCLIE2ETests/Helpers/TestCommon.cs, src/AppInstallerCLIE2ETests/Interop/UninstallInterop.cs, src/AppInstallerCLIE2ETests/Interop/UpgradeInterop.cs, src/AppInstallerCLIE2ETests/TestData/Manifests/TestUpgradeAvailableApi.1.0.0.0.yaml, src/AppInstallerCLIE2ETests/TestData/Manifests/TestUpgradeAvailableApi.2.0.0.0.yaml, src/AppInstallerCLITests/RestInterface_1_0.cpp, src/AppInstallerCommonCore/Manifest/YamlParser.cpp, src/Microsoft.Management.Deployment/CatalogPackage.cpp, src/Microsoft.Management.Deployment/PackageManager.cpp, src/Microsoft.Management.Deployment/PackageManager.idl, src/PowerShell/Microsoft.WinGet.Client.Engine/Extensions/CatalogPackageExtensions.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSCatalogPackage.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSDownloadResult.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSFoundCatalogPackage.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSInstallResult.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSRepairResult.cs, src/PowerShell/Microsoft.WinGet.Client.Engine/PSObjects/PSUninstallResult.cs, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_10ManifestMerged.yaml, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_9ManifestMerged.yaml
Added e2e tests. Also added unit tests for rest source with multiple manifest versions response.
Also fixed the Source Name logic in the PS output class to retrieve matching source name for the package id.
=> Consider installer applicability in IsUpdateAvailable COM api

src/AppInstallerCLICore/COMContext.cpp, src/AppInstallerCLICore/Core.cpp, src/AppInstallerCLITests/main.cpp, src/AppInstallerRepositoryCore/InstallerMetadataCollectionContext.cpp, src/AppInstallerSharedLib/AppInstallerLogging.cpp, src/AppInstallerSharedLib/Public/AppInstallerLogging.h, src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp, src/Microsoft.Management.Deployment/PackageManagerSettings.cpp, src/WinGetUtil/Exports.cpp, src/WindowsPackageManager/ConfigurationStaticFunctions.cpp
The user setting to control the logging channels was no longer being respected after a previous change to enable all channels during initialization (and to send the initialization logs to the debug stream).
`EnableChannel` for logging has always been semantically "add the given channel(s) to the list of enabled channels".
Every place that we were calling `EnableChannel` was really semantically wanting to set the list of enabled channels rather than add to it.
This change creates a new function `SetEnabledChannels` that behaves that way; it simply sets the enabled channel mask to the given value.  All callers of `EnableChannel` were changed to use this new function.
=> Fix logging channel setting

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/TestData/Manifest-Bad-InstallerTypeZip-PortableNotExe.yaml, src/AppInstallerCLITests/TestData/Manifest-Bad-InstallerTypeZip-PortableNotExe_Root.yaml, src/AppInstallerCLITests/TestData/Manifest-Good-InstallerTypeZip-PortableExe.yaml, src/AppInstallerCLITests/YamlManifest.cpp, src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp, src/AppInstallerCommonCore/Public/winget/ManifestValidation.h
For the `portable` installer type, the `winget-pkgs` repository has a policy of not allowing scripts as installers. This includes `.bat`, `.ps1`, and `.cmd` files.
In addition to the policy at `winget-pkgs`, the client itself is not designed to handle portable files that are not `.exe` types. Issues have been filed asking for WinGet to support these in the future, but it currently does not -
* https://github.com/microsoft/winget-cli/issues/5083
* https://github.com/microsoft/winget-cli/issues/5086
* https://github.com/microsoft/winget-cli/issues/5087
This PR adds a validation option which validates the `RelativeFilePath` within a zip file is always a `.exe`, but can be extended to include additional formats as the requests above are addressed. This was added as a validation option …
=> Add validation option for portable installer type in archives

src/AppInstallerSharedLib/Filesystem.cpp
Fixes #5276
Although I don't understand precisely why, we get access denied when attempting to open a directory with `WRITE_OWNER` even when we are already the owner.  It may have to do with permissions to the parent directory, but the root cause isn't actually important here.
Our directory management code always attempts to set any directory to a known state, including the owner.  It does so without any pre-check to see if the owner is already set to the desired value.
If we get `ERROR_ACCESS_DENIED` when attempting to set the owner, check if the owner is already correct.  If it is, attempt to set just the DACL.
Manual repro and validation that the fix works when the issue is exactly as described.
=> Handle access denied error when setting owner if already owner

.config/configuration.winget, doc/Developing.md
Setting developer mode, installing Visual Studio 2022 & fetching and installing VS components all require elevation. Added `securityContext: elevated` for these resources. Removed `allowPrerelease: true` for `Microsoft.WinGet.DSC/WinGetPackage` as it's GA now. Also fixed a bad link in the docs
-----
=> Add securityContext to configuration file

src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/Common/PackageCommand.cs, src/PowerShell/tests/Microsoft.WinGet.Client.Tests.ps1
Swap the version finding code in the PowerShell module from using a direct string comparison to using the `CompareToVersion` function.  This enables non-exact version matching, such as "1 == 1.0.0".
Adds a test with a short version to validate the change.
=> Use version comparison function rather than string compare in PS

src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp
Fixes #5318
Mitigates many other issues getting 0x80070490 from installed package enumeration
Check for `IPackageManager9` before using it to prevent an AV on older Windows versions.
Attempt to `FindPackagesForUserWithPackageTypes` with fewer types if it fails with `E_NOT_SET`.  While this is an OS issue, enumerating fewer (or no) packages is generally better than an error that completely blocks usage.
Manually tried both user and system scopes to ensure proper mainline functionality.
=> More graceful MSIX enumeration failure handling

src/AppInstallerCLICore/Workflows/InstallFlow.cpp, src/AppInstallerCLICore/Workflows/InstallFlow.h, src/AppInstallerCLITests/InstallDependenciesFlow.cpp
Cherry pick #5327 to 1.10
When `download` was added, the COM download and install split for dependencies was accidentally implemented. But it was validated only with download in mind, so the download part worked for download intent. With dependencies, the split basically attempted to install the dependencies twice, causing a failure on the second attempt due to internal assertions.
For the COM download command, explicitly force that we are only downloading.
=> Only download during COM download

doc/troubleshooting/README.md
=> troubleshooting source error

src/AppInstallerCLICore/ContextOrchestrator.cpp
Fixes #5365
Fix the issue in two ways:
1. Only use `- 1` if `supportedConcurrentThreads` is greater than 1.
2. Swap the order of setting min and max thread counts on the pool so that setting the minimum thread count to 1 overrides a "bad" allowed thread count of 0 (there are better ways to not do something than creating a thread pool that isn't allowed any threads).
=> Fix it twice

src/AppInstallerCLIE2ETests/Interop/FindPackagesInterop.cs, src/Microsoft.Management.Deployment/PackageVersionInfo.cpp
Fixes #5349
Return an empty `hstring` if we don't find a metadata key rather than attempting to dereference an invalid iterator.
Thanks @luke-patchblox for pointing out the issue precisely (although you took all the fun out of diagnosing it 😝)
=> Handle not finding metadata

src/Microsoft.Management.Deployment/CatalogPackage.cpp, src/Microsoft.Management.Deployment/CatalogPackage.h
DefaultInstallVersion being null causes larger than expected issues. The change proposes to return latest applicable version if exists, to minimize duplicate installs/ upgrade failures. If no latest applicable version, return latest available version if exists.
=> Better DefaultInstallVersion

src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters, src/AppInstallerCLICore/Commands/DscCommand.cpp, src/AppInstallerCLICore/Commands/DscComposableObject.h, src/AppInstallerCLICore/Commands/DscPackageResource.cpp, src/AppInstallerCLICore/Commands/DscSourceResource.cpp, src/AppInstallerCLICore/Commands/DscSourceResource.h, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/pch.h, src/AppInstallerCLIE2ETests/ConfigureCommand.cs, src/AppInstallerCLIE2ETests/DSCv3PackageResourceCommand.cs, src/AppInstallerCLIE2ETests/DSCv3ResourceCommands.cs, src/AppInstallerCLIE2ETests/DSCv3ResourceTestBase.cs, src/AppInstallerCLIE2ETests/DSCv3SourceResourceCommand.cs, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/pch.h, src/AppInstallerSharedLib/pch.h
Add a new DSC v3 resource: `source`.  This largely follows the design of the v2 resource, but uses the v3 paradigm for existence.
Other minor changes:
- Refactor the existing package resource tests into a test base.
- Fix an issue building valijson.
Added E2E tests to invoke the source resource in a variety of situations.
=> Dscv3 source resource

src/AppInstallerCLI.sln, src/AppInstallerTestExeInstaller/AppInstallerTestExeInstaller.vcxproj, src/PureLib/PureLib.vcxproj, src/VcpkgCustomTriplets/arm64-release-static.cmake, src/VcpkgCustomTriplets/arm64-release.cmake, src/VcpkgCustomTriplets/arm64.cmake, src/VcpkgCustomTriplets/common.cmake, src/VcpkgCustomTriplets/x64-release-static.cmake, src/VcpkgCustomTriplets/x64-release.cmake, src/VcpkgCustomTriplets/x64.cmake, src/VcpkgCustomTriplets/x86-release-static.cmake, src/VcpkgCustomTriplets/x86-release.cmake, src/VcpkgCustomTriplets/x86.cmake, src/Xlang/UndockedRegFreeWinRT/src/UndockedRegFreeWinRT/UndockedRegFreeWinRT/UndockedRegFreeWinRT.vcxproj, src/cpprestsdk/cpprestsdk.vcxproj
After the change to have our dependencies use vcpkgs instead of checking in a clone of the code, we got BinSkim alerts due to some of them not using our custom triplets with the compilation flags that we need. This PR ensures that all projects include the `vcpkg.props` that makes CMake use our custom triplets instead of the default `{arch}-windows` ones.
It is unclear to me why this happened. For example, why the test installer exe was building the vcpkgs at all, but the logs show that as one of the root projects for the issue.
Besides importing `vcpkg.props` in more projects, this also does a little refactor of the triplets to reduce duplication and have the required flags in a single place
=> Ensure all vcpkgs use our custom triplets

src/VcpkgCustomTriplets/arm64-release-static.cmake
In #5423 I used a wrong variable for the arm64-release-static vcpkg triplet. Didn't notice it until running on internal builds because we don't build that configuration in CI builds here...
=> Fix arm64-release-static vcpkg triplet

.github/actions/spelling/patterns.txt, azure-pipelines.yml, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Validated by removing the "install dsc v3" step in pipeline and e2e tests work.
=> Install dsc v3 package if not found when processing dsc v3 configuration file

azure-pipelines.yml, src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCLIE2ETests/ConfigureExportCommand.cs
=> Use Microsoft.Windows.Settings in configure export all

src/AppInstallerCLICore/Commands/DscUserSettingsFileResource.cpp, src/AppInstallerCLIE2ETests/DSCv3UserSettingsFileResourceCommand.cs
=> Make partial the default for user-settings-file

src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp, src/AppInstallerCLICore/ConfigurationSetProcessorFactoryRemoting.cpp, src/Microsoft.Management.Configuration.Processor/DSCv3/Helpers/ProcessorRunSettings.cs, src/Microsoft.Management.Configuration.Processor/DSCv3/Set/DSCv3ConfigurationSetProcessor.cs, src/Microsoft.Management.Configuration.Processor/DSCv3/Unit/DSCv3ConfigurationUnitProcessor.cs, src/Microsoft.Management.Configuration.UnitTests/Tests/DSCv3ProcessorTests.cs
Even if not found, attempt to use DSCv3 resources.  This is largely to avoid PowerShell/DSC#786, which only seems to affect dsc.exe's ability to run processes when listing adapted resources.
Also applies the `DiagnosticTraceEnabled` state to the elevated processor.  This is set when the config logging area is enabled and set to verbose.
When running manually, the logs indicate that the adapted `list` invocations are failing, but the attempt to use the resource still succeeds.
=> Attempt to use DSCv3 resources even if they were not found

src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp
To prevent an error from attempting to parse a boolean from an empty string, only forward the diagnostics (verbose) property if it has been set.
Tried with and without verbose, logs are as expected.  We should take time in the future to make the E2E tests exercise the dynamic factory more.
=> Only forward the verbose property if it has been set

src/vcpkg.props
When setting the path for the vcpkg installed directory in the shared props file, we were using `$(ProjectDir)\..\`. This works fine for most projects because they are one level under the `src` directory, but `UndockedRegFreeWinRT` is deeper in the tree so it would end up having its own separata vcpkg_installed directory.
=> Make UndockedRegFreeWinRT use same vcpkg_installed directory

src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters, src/AppInstallerCLICore/Commands/DscAdminSettingsResource.cpp, src/AppInstallerCLICore/Commands/DscAdminSettingsResource.h, src/AppInstallerCLICore/Commands/DscCommand.cpp, src/AppInstallerCLICore/Commands/DscComposableObject.h, src/AppInstallerCLICore/Commands/SettingsCommand.cpp, src/AppInstallerCLICore/Resources.h, src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp, src/AppInstallerCLICore/Workflows/SettingsFlow.cpp, src/AppInstallerCLICore/Workflows/SettingsFlow.h, src/AppInstallerCLIE2ETests/DSCv3AdminSettingsResourceCommand.cs, src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw, src/AppInstallerCommonCore/AdminSettings.cpp, src/AppInstallerCommonCore/Public/winget/AdminSettings.h
Adds an admin settings resource to mirror the existing v2.
Also adds `winget settings reset --all` to reset all admin settings to their default values (respecting group policy of course).
Added E2E tests for invoking the resource.
=> DSCv3 admin settings resource

src/Microsoft.Management.Deployment/Helpers.cpp
`AppCapability::CreateWithProcessIdForUser` does not accept a null user on Windows 10 v1903. Treat this case as if the API didn't exist.
Fixes #5378.
-----
=> Fix catalog connection failure due to AppCapability::CreateWithProcessIdForUser throwing E_INVALIDARG when called with a null user on Windows 10 v1903

.github/actions/spelling/expect.txt, src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp, src/AppInstallerRepositoryCore/pch.h
Based on https://devblogs.microsoft.com/oldnewthing/20210215-00/
Fixes #5363.
-----
=> Fix crash due to static weak pointer referencing an object in an unloaded DLL

src/VcpkgPortOverlay/libyaml/vcpkg.json
The latest version of libyaml available from the official vcpkg repo has a vulnerability, and the current recommendation is to manually patch it. To apply the patch I added a port overlay here.
Component Governance is still flagging this as unpatched. This may be because we are using the same port version as the one that is known bad in the official repo, so I'm increasing the port version. Hopefully this will make CG happy; otherwise we'll need to file for an exception.
=> Increase libyaml vcpkg port version

.github/PULL_REQUEST_TEMPLATE.md, doc/ReleaseNotes.md, doc/Settings.md, src/AppInstallerCLI.sln
This adds a text file with the notes we add to each release here in GitHub.
I intend to update the publishing script to include these notes automatically so I don't have to manually copy them each time.
These notes are not intended to be a full changelog of all versions, but rather just about the changes in the current version. (Although maybe we should have a changelog for all major versions at least.)
It would be nice if we manage to keep the notes up to date every time we make a change, but if we forget we can still edit the release after the fact.
=> Add text file with the release notes

src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp, src/Microsoft.Management.Configuration/ConfigurationProcessor.h, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.idl
This pull request introduces a new feature to test configuration units in the `ConfigurationProcessor` class. The most important changes include the addition of synchronous and asynchronous methods for testing configuration units, along with their implementation and interface definitions.
* Added `TestUnit` and `TestUnitAsync` methods to the `ConfigurationProcessor` class for testing configuration units. These methods validate the state of the configuration processor and delegate the logic to the new `TestUnitImpl` method. (`src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp`, [src/Microsoft.Management.Configuration/ConfigurationProcessor.cppR1068-R1132](diffhunk://#diff-87fc2b065652feeac26cfec1a39df0f1b1dfea560ed24e28cc0295c04b5e3915R1068-R1132))
* Implemented …
=> Expose TestUnit method to COM API

azure-pipelines.yml, src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj, src/ConfigurationRemotingServer/Program.cs, src/Microsoft.Management.Configuration.Processor/DSCv3/Helpers/ProcessExecution.cs, src/Microsoft.Management.Configuration.Processor/Public/PathEnvironmentVariableHandler.cs
Added a hidden window to listen for UserPreferenceChanged event (WM_SETTINGCHANGE) and update the process's PATH if needed.
Manually validated by running a configuration file with multiple resources, change the env var during the run, and verified in logs file that new path got included in runs after the change.
=> Refresh PATH in configuration remoting server

src/AppInstallerCLICore/Workflows/PortableFlow.cpp
Only use the installed version's scope when we have one to use.
=> Fix AV in portable flow

azure-pipelines.loc.yml
The loc pipeline uses windows-2019 agents that are being deprecated.
=> Use windows-latest agents in localization pipeline

doc/ReleaseNotes.md, src/binver/binver/version.h
=> Bump version to v1.12

src/AppInstallerCLICore/AppInstallerCLICore.vcxproj, src/AppInstallerCLICore/Commands/DscCommandBase.cpp, src/AppInstallerCLICore/Commands/DscCommandBase.h
Use `UseProdCLSIDs` rather than `WingetDisableTestHooks` to drive the dev/not-dev decision in DSC v3 resources.  This only matters to the internal local builds; everywhere else they are the same value.
=> Move to proper signal for dev/not-dev

src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
`Repair-WinGetPackageManager` is failing to install winget in some Win10 systems. The issue seems come from #5517 and be caused because in some cases we fail to mark any one architecture as the right one to use for dependencies. This PR is a partial revert of #5517 to add the previous logic as a fallback.
May fix #5559 (but I haven't set up an environment to test it...)
=> Repair Repair-WinGetPackageManager

src/VcpkgCustomTriplets/common.cmake
Yet another attempt to fix that crash we are seeing 🙃
See #5587
In the past we had added `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` globally to fix a similar crash using `Directory.Build.props`, but that does not flow from MSBuild to vcpkg. This change adds it to all the ports we use.
=> Add more missing flags for vcpkg

src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp
Fixes #4410 
Catch errors coming from `FindProvisionedPackages` and ignore them.  This is most likely to happen when the caller is not elevated.
```PowerShell
> winget install notepad++.notepad++ --scope machine
Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070005 : Access is denied.
> wingetdev install notepad++.notepad++ --scope machine
Found Notepad++ [Notepad++.Notepad++] Version 8.8.3
Downloading https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.8.3/npp.8.8.3.Installer.x64.exe
██████████████████████████████  6.52 MB / 6.52 MB …
```
=> Swallow provisioned package errors

.github/actions/spelling/expect.txt, src/AppInstallerSharedLib/YamlWrapper.cpp
=> Handle Byte Order Mark during validation

src/AppInstallerCLICore/ConfigurationSetProcessorFactoryRemoting.cpp, src/AppInstallerCLIPackage/AppInstallerCLIPackage.wapproj, src/AppInstallerCLIPackage/Package.appxmanifest, src/AppInstallerCommonCore/SelfManagement.cpp, src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj, src/targets/ReferenceEmbeddedCsWinRTProject.targets
When trying to create the actual package containing the MCP server, we found issues in merging the directory contents.  Specifically, some common nuget packages were used at different versions.
Reference the MCP project from the configuration server project, forcing the nuget package resolution to consider them as one unit.  This also helpfully outputs them as merged already.
Also change the name of the directory in the package to reflect the expanded contents.
My locally built package works for both MCP and configuration scenarios.
=> Resolve nuget package graph for .NET projects together

src/AppInstallerCLICore/Commands/TestCommand.cpp, src/AppInstallerCLICore/Public/ShutdownMonitoring.h, src/AppInstallerCLICore/ShutdownMonitoring.cpp, src/AppInstallerCLICore/pch.h, src/AppInstallerCLIE2ETests/AppShutdownTests.cs, src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp, src/AppInstallerSharedLib/AppInstallerSharedLib.vcxproj, src/AppInstallerSharedLib/AppInstallerSharedLib.vcxproj.filters, src/AppInstallerSharedLib/COMStaticStorage.cpp, src/AppInstallerSharedLib/Public/winget/COMStaticStorage.h, src/AppInstallerSharedLib/pch.h, src/WindowsPackageManager/main.cpp
The use of the COM static store was causing crashes on long lived processes because the implementation of `DllCanUnloadNow` did not count those objects, nor did it clean them up.  This led to our module being unloaded, then when it was reloaded, the recreation of the static store object would invoke the deletion of the old one, which was pointing to the old, unloaded module location.
WindowsPackageManager.dll serves many purposes, making the lifetime of statics complex.
- It serves as "in-proc" for the CLI
- It is the core implementation for the in-proc COM
- It is the core implementation for the OOP COM
In order to support in-proc COM, we must put static lifetime COM objects in the static store.  But in order to support unloading, we must also clean them up.  Additionally, we don't want …
=> Improve COM static store usage

src/AppInstallerCLICore/Commands/TestCommand.cpp, src/AppInstallerCLICore/ExecutionContext.cpp, src/AppInstallerCLICore/pch.h, src/AppInstallerCLIE2ETests/AppShutdownTests.cs, src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp, src/AppInstallerSharedLib/AppInstallerSharedLib.vcxproj, src/AppInstallerSharedLib/AppInstallerSharedLib.vcxproj.filters, src/AppInstallerSharedLib/COMStaticStorage.cpp, src/AppInstallerSharedLib/Public/winget/COMStaticStorage.h, src/AppInstallerSharedLib/pch.h, src/WindowsPackageManager/main.cpp
CP from #5680 
Ported changes backward from the termination handling refactor.
Built and ran the test command locally to validate.
=> Improve COM static store usage (port to 1.11)

src/AppInstallerCLIPackage/Package.appxmanifest, src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj
Fixes #5259 
Register the configuration class names in the manifest to support proper activation (not C++/WinRT fallback behavior).
Change the configuration link inputs to use the older `icu*.dll` files rather than the one that comes in the umbrella of `onecoreuap.lib` [`icu.lib`].
Test build works on RS5 VM.
=> Fixes for older OSes

src/AppInstallerCLITests/AppInstallerCLITests.vcxproj, src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters, src/AppInstallerCLITests/RestClient.cpp, src/AppInstallerCLITests/RestInterface_1_12.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/ManifestJSONParser.cpp, src/AppInstallerRepositoryCore/Rest/RestClient.cpp, src/AppInstallerRepositoryCore/Rest/Schema/1_12/Interface.h, src/AppInstallerRepositoryCore/Rest/Schema/1_12/Json/ManifestDeserializer.h, src/AppInstallerRepositoryCore/Rest/Schema/1_12/Json/ManifestDeserializer_1_12.cpp, src/AppInstallerRepositoryCore/Rest/Schema/1_12/RestInterface_1_12.cpp, src/AppInstallerRepositoryCore/Rest/Schema/CommonRestConstants.h, src/WinGetUtilInterop.UnitTests/ManifestUnitTest/V1ManifestReadTest.cs, src/WinGetUtilInterop.UnitTests/TestCollateral/V1_12ManifestMerged.yaml, src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj
Closes #5694 
Updates the RestSource and interface to support v1.12 Manifest schema.
* Added Manifest 1.12 Schema to the Rest source and support for the new installer type.
* Added tests for v1.12 rest source.
* Added unit tests for WinGetUtilInterop for the v1.12 merged manifest and validating the new installertype.
Tested:
* WinGetUtilInterop Unit tests passed, verified in debugger that the new v1.12 manifest and manifest properties were being tested and validated.
* AppInstallerCLITests for [RestSource] and the new [Interface_1_12] both pass.
(This is part of schema update for 1.12 so nothing new to add to release notes.)
-----
=> Add RestSource and tests for Manifest v1.12

src/AppInstallerCLITests/CompositeSource.cpp, src/AppInstallerCLITests/SQLiteIndexSource.cpp, src/AppInstallerCLITests/TestSource.cpp, src/AppInstallerCLITests/TestSource.h, src/AppInstallerRepositoryCore/CompositeSource.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSourceV1.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSourceV1.h, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSourceV2.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSourceV2.h, src/AppInstallerRepositoryCore/Public/winget/RepositorySearch.h, src/AppInstallerRepositoryCore/RepositorySearch.cpp, src/AppInstallerRepositoryCore/Rest/RestSource.cpp, src/AppInstallerSharedLib/Public/winget/LocIndependent.h
Fixes #5629 
(and probably quite a few more list/upgrade some-query-provided performance related issues)
While things could still be made better, the good case (where files were already cached locally) of the previous behavior trying to complete `winget list Micro` was taking 51 seconds.  With this change, it takes 6 seconds on the debug build.  Given that there is intentionally little to no I/O and much of the CPU time is likely spent in our code, that should speed up more with the release.
The indexed `IPackage` implementation for v2 needed to acquire the intermediate manifest to provide the response for `GetVersionKeys`.  Since this is used extensively to perform correlation between available packages and local items during a search, any available packages found by the query would then …
=> Improve slow searches involving installed items

src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp, src/AppInstallerCLITests/DateTime.cpp, src/AppInstallerSharedLib/DateTime.cpp, src/AppInstallerSharedLib/Public/AppInstallerDateTime.h, src/WindowsPackageManager/ConfigurationStaticFunctions.cpp
Make `OutputTimePoint` more flexible by allowing arbitrary fields and behaviors to be requested via flags.
Shorten the default installer log filename by removing the leading `WinGet-` and dropping the milliseconds.  Some installers use the log file path as a base with no error handling to ensure a valid path is produced.  Anything we can remove means more likely success.
=> Shorter default installer log filename

src/AppInstallerCLICore/PortableInstaller.cpp, src/AppInstallerCLICore/PortableInstaller.h, src/AppInstallerCLICore/Workflows/PortableFlow.cpp, src/AppInstallerCLITests/PortableInstaller.cpp
Fixes #5688
We were not recording ARP changes for portable installs, which prevented the product code from being in the tracking database, which led to inconclusive correlation results for packages with shared normalized name+publisher.
Portable install flow extracts the `AppsAndFeaturesEntry` for the install and puts it into the `CorrelatedAppsAndFeaturesEntries` context item.
Manually confirmed fix, updated test to ensure product code extraction.
=> Add the ARP correlation entry to the context for portable installs

src/AppInstallerCLITests/SQLiteIndex.cpp, src/AppInstallerCLITests/SQLiteIndexSource.cpp, src/AppInstallerRepositoryCore/Microsoft/SQLiteIndexSourceV2.h, src/AppInstallerRepositoryCore/Microsoft/Schema/2_0/PackagesTable.cpp, src/AppInstallerRepositoryCore/RepositorySearch.cpp
Fixes #4928
Fixes providing "1" for the version when the version is actually "1.0" and the like (there is probably an issue filed but I didn't find it after a quick search).
Due to SQLite helpfully not being picky about data types, the packages table in the v2 index was using INT64 for every column, when in reality they should mostly by strings (TEXT).  When the version was parsable as a number, it would drop unnecessary portions (trailing 0s).
New code in the v2 index and the composite package changes were using string comparison instead of `Version`, requiring an exact string match rather than `Version` equality.
Use the data type that we already had set up rather than always INT64.  This will require a service update to actually fix anything (but doesn't require a client update).
Use …
=> Fix two unrelated version issues

.github/actions/spelling/allow.txt, .github/workflows/.github/workflows/automatic-issue-deduplication.yml
-----
This adds a bot to automatically detect duplicate issues after an issue is opened or re-opened. It can only apply the "duplicate" label. It will not close the issue and it will leave a comment with the duplicate issue(s).
=> Add workflow for automatic issue deduplication

.github/actions/spelling/allow.txt, azure-pipelines.yml, src/AppInstallerCLIE2ETests/ConfigureCommand.cs, src/AppInstallerCLITests/Downloader.cpp, src/AppInstallerCLITests/RestClient.cpp, src/AppInstallerCLITests/Settings.cpp, src/AppInstallerCLITests/Strings.cpp, src/AppInstallerCLITests/TestRestRequestHandler.cpp, src/AppInstallerCommonCore/Downloader.cpp, src/AppInstallerCommonCore/Public/AppInstallerDownloader.h, src/AppInstallerCommonCore/Public/AppInstallerRuntime.h, src/AppInstallerCommonCore/Public/winget/Settings.h, src/AppInstallerCommonCore/Runtime.cpp, src/AppInstallerCommonCore/Settings.cpp, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj, src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters, src/AppInstallerRepositoryCore/Rest/RestClient.cpp, src/AppInstallerRepositoryCore/Rest/RestInformationCache.cpp, src/AppInstallerRepositoryCore/Rest/RestInformationCache.h, src/AppInstallerSharedLib/AppInstallerStrings.cpp, src/AppInstallerSharedLib/JsonUtil.cpp, src/AppInstallerSharedLib/Public/AppInstallerSHA256.h, src/AppInstallerSharedLib/Public/AppInstallerStrings.h, src/AppInstallerSharedLib/Public/winget/JsonUtil.h, src/AppInstallerSharedLib/SHA256.cpp
Store and use the `/information` response from REST sources per their `cache-control` header.
At the base of this change is a new type of setting stream: `Encrypted`.  These settings are encrypted to the user and machine that the data is stored on.
Based on the log file from running with and without a cached value, the time between close log lines dropped from 189 ms to 8 ms for the msstore source.  This time saving should be in effect for the large majority of uses of WinGet.
Added tests across various levels of the change.
Manually verified functionality of CLI.
=> Cache information responses from REST sources

doc/ReleaseNotes.md, src/AppInstallerCLICore/PortableInstaller.cpp
Closes #4044
Closes #3616 
The path is being lost under the condition of Dev Mode being disabled with a user install, because we only set the PATH if symlinks are not available. In this situation, the portable package is registered with a path set, and that information is added to the ARP entry. When an upgrade occurs, this path being set value is true and when removing the old version we are also removing the path since it was set. Then when we add the new version, the variable that says the path was set is still true, so it does not re-add the path and does not set the path information in the ARP entry.
The fix is to update the variable that indicates the path has been set whenever we remove the path. This causes the install of the new version to recognize that the path has been removed …
=> Fix portable path removal on upgrade

src/SfsClient/sfs-client/cgmanifest.json
Component Governance is reporting issues from openssl. The alert is caused by it being in the `cgmanifest.json` of `sfs-client` even though [they don't use it on Windows](https://github.com/microsoft/sfs-client/blob/63aab71b46d92977a60b231849bebcf6cbd37715/vcpkg.json#L21). Since it is not actually used, we can't do something like overriding the version (and even if we did, CG would also pick the version in the json).
Removing it from their cgmanifest should get rid of the alert, although it will cause issues the next time we update the subtree.
=> Remove openssl from sfsclient cgmanifest
