microsoft/winget-cli

- doc/windows-package-manager-v1-roadmap.md
here's a very important and crucial pr for you guys
> small typos in roadmap

- README.md
Of course when I was reading for content, I didn't catch the space needed for the link.
> Whitespace for the win!

- doc/specs/#364 - Feature Toggle.md
> Feature Toggle Spec

- src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp
For #365 
Prior to this change, the interactive switches needed to be provided in order for the --interactive option to work. With this change, the goal is to provide a more intuitive experience.  The following table shows the expected behavior, where we fall back to the secondary switches if the primary are not provided, and no switches if we run out of options.
Requested | Primary | Secondary
-- | -- | --
Silent | Silent | SilentWithProgress
SilentWithProgress | SilentWithProgress | Silent
Interactive | Interactive | 
Since Interactive is typically the default interactivity level of an installer, we assume that not providing any switches is agreeing with such a statement.
Existing tests and manual validation of an MSI installer with --interactive.
> Change how interactivity level arguments are chosen

- src/YamlCppLib/yaml-cpp/src/scanscalar.cpp
> Remove phrase

- src/AppInstallerCLI/AppInstallerCLI.vcxproj
- src/JsonCppLib/JsonCppLib.vcxproj
- src/WinGetUtil/WinGetUtil.vcxproj
- src/YamlCppLib/YamlCppLib.vcxproj
Per [BinSkim](https://github.com/microsoft/binskim), we need to enable Control Flow Guard.  In addition, I enabled at least /W3 warnings as suggested (which was only not on in our external subtrees).
> Enable Control Flow Guard

- src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp
Just doing what the robot overlords tell me.
> Rephrase due to policheck

- NOTICE
Not sure why there is so much change, but this file is generated, so it is what it is.
> Update NOTICE for yaml parser change

- doc/settings.schema.json
> Fix the title in the json schema

- doc/Settings.md
> Fixed small Typo in Settings.md

- doc/windows-package-manager-v1-roadmap.md
> Improved punctuation in windows-package-manager-v1-roadmap.md

- README.md
The link to the framework packages download is obsolete. This one replaces it.
> Update instructions for installing Desktop Bridge

- NOTICE
> Update license file including valijson

- WinGetUtil.nuspec
> Adding PDBs for WingetUtil to nuget package

- schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.locale.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json
> Minor schema changes from review comments and for better compatibility

- schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json
- src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
- src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
- src/AppInstallerCLITests/TestData/Manifest-Bad-Channel-NotSupported.yaml
- src/AppInstallerCLITests/TestData/ManifestV1-Singleton.yaml
- src/AppInstallerCLITests/TestData/MultiFileManifestV1/ManifestV1-MultiFile-Installer.yaml
- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerCommonCore/Manifest/ManifestValidation.cpp
- src/WinGetUtil/Exports.cpp
- src/WinGetUtil/Source.def
> Add back Channel Not Supported check

- azure-pipelines.yml
> Make Component Governance task required again

- schemas/JSON/packages/packages.schema.1.0.json
> Fix WinGetVersion regex in packages schema

- azure-pipelines.yml
> Reenable component governance task in PR validation

- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
> Update tags per internal review

- src/AppInstallerCLICore/Commands/ShowCommand.cpp
- src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
Fix double identity reporting.
> Fix double Found output

- schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json
- src/AppInstallerCLITests/TestData/ManifestV1-Singleton.yaml
- src/AppInstallerCLITests/TestData/MultiFileManifestV1/ManifestV1-MultiFile-Installer.yaml
- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp
- src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp
- src/AppInstallerCommonCore/Public/winget/ManifestCommon.h
- src/AppInstallerCommonCore/Public/winget/ManifestInstaller.h
> Correct InstallModes in manifest schema

- README.md
adding link to Keivan's GH account
> adding link to Keivan's GH account for Readme.md

- WinGetUtil.nuspec
> Publish manifest schemas in wingetutil nuget package

- README.md
https://docs.microsoft.com/windows/package-manager/winget/
> adding adminstrator considerations from docs.microsoft.com

- schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json
To be consistent with value from AppxManifest.
> Update file extension max length

- src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj
- src/IndexCreationTool/IndexCreationTool.csproj
- src/LocalhostWebServer/LocalhostWebServer.csproj
Updated net core projects framework to .NET 5.0 from 3.1.
> Update .net core projects to target framework .NET 5.0

- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Upgrade description was update
info for show should be information
-----
#799
> minor changes to display text

- README.md
I hope this is ok, since I didn't see it mentioned anywhere and the spec has been v1.0 for a little while now.
-----
> Point manifest spec link to v1.0.

- src/AppInstallerCLITests/JsonHelper.cpp
- src/AppInstallerCLITests/RestClient.cpp
- src/AppInstallerCLITests/RestHelper.cpp
- src/AppInstallerCLITests/RestInterface_1_0.cpp
- src/AppInstallerCLITests/SearchRequestSerializer.cpp
- src/AppInstallerRepositoryCore/Rest/HttpClientHelper.cpp
- src/AppInstallerRepositoryCore/Rest/HttpClientHelper.h
- src/AppInstallerRepositoryCore/Rest/RestClient.cpp
- src/AppInstallerRepositoryCore/Rest/RestClient.h
- src/AppInstallerRepositoryCore/Rest/RestSource.cpp
- src/AppInstallerRepositoryCore/Rest/RestSource.h
- src/AppInstallerRepositoryCore/Rest/RestSourceFactory.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Interface.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Interface.h
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/InformationResponseDeserializer.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/SearchRequestSerializer.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/SearchRequestSerializer.h
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/SearchResponseDeserializer.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/IRestClient.h
- src/AppInstallerRepositoryCore/Rest/Schema/JsonHelper.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/JsonHelper.h
- src/AppInstallerRepositoryCore/Rest/Schema/RestHelper.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/RestHelper.h
- [ Y] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ N] Are you working against an Issue?
-----
This PR contains the following changes:
- Implemented logic to accept continuation token and maximum results in Rest source search method.
- Added usage of source identifier from Rest Information endpoint.
- Added Package family names and Product codes and implemented required methods that use these fields.
- Added check to verify search request package match fields and match types and fixed some other small Todos.
- Added unit tests for the above changes.
> Rest source search result continuation token, PFN and product codes

- .github/actions/spelling/expect.txt
- doc/windows/package-manager/index.md
This is a first attempt at synchronizing documentation in the GitHub project with docs.microsoft.com.
-----
> Working on docs

- src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
- src/AppInstallerRepositoryCore/CompositeSource.cpp
Fixes part of issues from #752
Also cleaned up unused fuzzing configuration from CommonCore project.
> Make correlation logic from available source to installed source look at all versions instead of just latest

- doc/windows-package-manager-v1-roadmap.md
> Roadmap Update

- schemas/JSON/manifests/preview/manifest.0.1.0.json
- schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.locale.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.singleton.1.0.0.json
> Set url max length to 2048

- README.md
- doc/admx/DesktopAppInstaller.admx
- src/AppInstallerCLI/AppInstallerCLI.vcxproj
- src/AppInstallerCLICore/AppInstallerCLICore.vcxproj
- src/AppInstallerCLIE2ETests/TestData/IndexPackageManifest.xml
- src/AppInstallerCLIE2ETests/TestData/Package/AppxManifest.xml
- src/AppInstallerCLIPackage/AppInstallerCLIPackage.wapproj
- src/AppInstallerCLIPackage/Package.appxmanifest
- src/AppInstallerCommonCore/AppInstallerCommonCore.vcxproj
- src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj
- src/AppInstallerRepositoryCore/Microsoft/Schema/1_1/ManifestMetadataTable.cpp
- src/AppInstallerTestExeInstaller/AppInstallerTestExeInstaller.vcxproj
- src/AppInstallerTestMsixInstaller/AppInstallerTestMsixInstaller.wapproj
- src/WinGetUtil/WinGetUtil.vcxproj
> Update min supported version to 1809

- doc/Settings.md
> added json highlighting (line 90-94) in Settings.md

- README.md
> Note on insider program

- doc/windows/package-manager/package/repository.md
-----
A documentation update based on what @denelon spoke about in microsoft/winget-pkgs#15674.
> Documentation update to indicate packages are being manually validated again.

- doc/windows/package-manager/package/repository.md
- doc/windows/package-manager/winget/export.md
- doc/windows/package-manager/winget/features.md
- doc/windows/package-manager/winget/import.md
- doc/windows/package-manager/winget/index.md
- doc/windows/package-manager/winget/install.md
- doc/windows/package-manager/winget/list.md
- doc/windows/package-manager/winget/search.md
- doc/windows/package-manager/winget/settings.md
- doc/windows/package-manager/winget/show.md
- doc/windows/package-manager/winget/source.md
- doc/windows/package-manager/winget/uninstall.md
- doc/windows/package-manager/winget/upgrade.md
-----
On checking some documentation there were a lot of broken images.  I've updated the image path and now the images are displaying.
> Broken Image Paths Fixed

- doc/specs/#1155 - Enhancements to list command.md
-----
#1155 Enhancements to list command
> Create #1155 - Enhancements to list command.md

- src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp
We have seen `rename` fail, and given that we are so far into the process at this point there is no reason not to just wait and retry.
Existing tests and manual validation of golden path.
> Retry on rename

- schemas/JSON/manifests/v1.0.0/manifest.defaultLocale.1.0.0.json
- schemas/JSON/manifests/v1.0.0/manifest.version.1.0.0.json
Nice to have a default value, and enables our codegen'd object model to have a default value set for this property
> Setting DefaultLocale's default value to "en-US"

- src/AppInstallerRepositoryCore/Rest/RestClient.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/CommonRestConstants.h
- [Y ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [] Are you working against an Issue?
-----
> Removing support for older rest schema versions

- .github/actions/spelling/allow.txt
- src/AppInstallerCLICore/COMContext.cpp
- src/AppInstallerCLITests/Sources.cpp
- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
- src/AppInstallerRepositoryCore/Public/AppInstallerRepositorySource.h
- src/AppInstallerRepositoryCore/RepositorySource.cpp
- src/Microsoft.Management.Deployment/PackageManager.cpp
- src/Microsoft.Management.Deployment/PackageManager.idl
- src/WinGetServer/WinMain.cpp
Add Microsoft Store REST Source as default option
Fix gaps found in telemetry from data validation
-----
> Add Microsoft Store REST Source as default option and fix telemetry gaps

- README.md
> Administrator Considerations

- doc/specs/#396 - Settings command.md
-----
Creating a draft PR with no attached issue based on [this discussion](https://github.com/microsoft/winget-cli/discussions/1285#discussioncomment-1013660)
cc @denelon
> Update Settings Command Spec for Clarity

- doc/windows/package-manager/package/manifest.md
- doc/windows/package-manager/package/repository.md
- doc/windows/package-manager/package/windows-package-manager-policies.md
- doc/windows/package-manager/package/winget-validation.md
- doc/windows/package-manager/winget/export.md
- doc/windows/package-manager/winget/features.md
- doc/windows/package-manager/winget/import.md
- doc/windows/package-manager/winget/index.md
- doc/windows/package-manager/winget/list.md
- doc/windows/package-manager/winget/uninstall.md
- doc/windows/package-manager/winget/upgrade.md
- doc/windows/package-manager/winget/validate.md
> Fixed links and spacing

- src/AppInstallerCLICore/AppInstallerCLICore.vcxproj.filters
A previous commit didn't merge the filters files properly; this fixes that.
> Fix bad merge in filters file

- src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
> Show the version number during install.

- src/AppInstallerCLICore/Resources.h
- src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
> Display count of available upgrades

- src/AppInstallerRepositoryCore/RepositorySource.cpp
Fix a bad merge from two active PRs going in close to each other.
> Fix bad merge

- src/AppInstallerCLICore/Workflows/ShowFlow.cpp
- src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
> Add colons after agreement labels

- doc/Settings.md
> doc/Settings.md: Add missing "a"

- doc/windows/package-manager/index.md
- doc/windows/package-manager/winget/index.md
> Update Docs [suggestions]

- schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json
> Fix Installer return code max value in schema by bad merge

- azure-pipelines.nuget.yml
Fix nuget release pipeline, the fix is the same as #1082
> Fix nuget release pipeline

- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Noticed a missing string for `import` help; adding it now.
> Add missing resource string

- src/AppInstallerCLICore/Workflows/InstallFlow.cpp
-----
Resolves #1682. (Well, my core complaint, anyway. The discussion about a11y should be put in a new issue, since I think @denelon has brought up some good points!)
> Made the Installation Disclaimer for the Microsoft Store bold.

- cgmanifest.json
> Update component governance manifest with valijson v0.6 commit

- NOTICE
> Update Notice from latest component governance output

- doc/troubleshooting/README.md
-----
- Adding information about a known issue and workaround on Windows 11 Pro image in Azure.
> Update TSG with more information about a known issue

- doc/windows/package-manager/winget/upgrade.md
- [x ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
-----
> Fix Typo in upgrade.md

- Localization/Resources/de-DE/winget.resw
- Localization/Resources/es-ES/winget.resw
- Localization/Resources/fr-FR/winget.resw
- Localization/Resources/it-IT/winget.resw
- Localization/Resources/ja-JP/winget.resw
- Localization/Resources/ko-KR/winget.resw
- Localization/Resources/pt-BR/winget.resw
- Localization/Resources/ru-RU/winget.resw
- Localization/Resources/zh-CN/winget.resw
- Localization/Resources/zh-TW/winget.resw
Update localizations from internal 2201.12001
> Update localization strings

- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Adding some comments in the resources file where we didn't quite get the intended meaning across for localization, based on what I saw for #1846
> Add comments for localization

- src/AppInstallerCommonCore/Downloader.cpp
- src/AppInstallerCommonCore/Public/AppInstallerRuntime.h
- src/AppInstallerCommonCore/Runtime.cpp
> Check FS feature flags instead of checking for NTFS

- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
> Anonymize Com caller value

- .github/actions/spelling/allow.txt
- WinGetInProcCom.nuspec
- azure-pipelines.nuget.in-proc-com.yml
- azure-pipelines.nuget.yml
- src/AppInstallerCLI.sln
Tested with my local fork and the pipeline ran successfully.
> Add nuget publish pipeline for in-proc Com binaries

- WinGetInProcCom.nuspec
> Make In-proc Com nuget package better support .net framework 4.*

- azure-pipelines.yml
- Added succeededOrFailed to always try artifacts publish steps
- Fixed WinGetUtils search pattern
- Updated BinSkim to latest release binaries
> Build pipeline updates and improvements

- src/AppInstallerCLICore/Workflows/ShowFlow.cpp
```
License: Proprietary
Copyright: © 2013-2022 ESL Gaming Online, Inc.
Documentation:
FAQ: https://client.badlion.net/faq
Installer:
Type: nullsoft
Locale: en-US
Download Url: https://client-updates-cdn77.badlion.net/Badlion%20Client%20Setup%203.8.0.exe
SHA256: 4b89cc2702b3691cf4bf26683b448fe0c2910659193de7dde3c263225406dca4
```
```
License: Proprietary
Copyright: © 2013-2022 ESL Gaming Online, Inc.
Documentation:
FAQ: https://client.badlion.net/faq
Installer:
Type: nullsoft
Locale: en-US
Download Url: https://client-updates-cdn77.badlion.net/Badlion%20Client%20Setup%203.8.0.exe
SHA256: 4b89cc2702b3691cf4bf26683b448fe0c2910659193de7dde3c263225406dca4
```
> Indent documentations in 'show' command

- src/binver/binver/version.h
Increment version from 1.3 to 1.4
> Bump version to 1.4

- src/AppInstallerCLITests/SQLiteIndex.cpp
- src/AppInstallerRepositoryCore/Microsoft/Schema/1_0/Interface_1_0.cpp
- src/AppInstallerRepositoryCore/Microsoft/Schema/1_4/DependenciesTable.cpp
- src/AppInstallerRepositoryCore/PackageDependenciesValidation.cpp
> Fix WinGetUtil index operations for manifest dependencies without min version

- src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj
- src/Microsoft.Management.Deployment.Projection/Microsoft.Management.Deployment.Projection.csproj
Update CsWinRTWindowsMetadata value
~10.0.17763.0~ => 10.0.22000.0
> Update CsWinRTWindowsMetadata value

- doc/Settings.md
Adds documentation for the new settings that are supported in the 1.3 client.
> Update documentation with 1.3 settings

- README.md
> fix `ms-windows-store` link not rendered in md

- schemas/JSON/manifests/v1.3.0/manifest.installer.1.3.0.json
- schemas/JSON/manifests/v1.3.0/manifest.singleton.1.3.0.json
- src/AppInstallerCLITests/TestData/ManifestV1_3-Singleton.yaml
- src/AppInstallerCLITests/TestData/MultiFileManifestV1_3/ManifestV1_3-MultiFile-Installer.yaml
- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp
- src/AppInstallerCommonCore/Public/winget/ManifestCommon.h
For future potential launch from UI com caller scenarios(i.e. Store)
> Add DisplayName to InstallationMetadata installed files

- src/AppInstallerCLICore/Commands/UpgradeCommand.cpp
> Add Aliases to allow for quick upgrade of all and unknown

- src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp
> Map operation return code for msstore type installation failure as well

- cgmanifest.json
> Add Pure to component governance manifest

- src/AppInstallerCLICore/PortableInstaller.cpp
> Add space before path when files remain on uninstall

- doc/Settings.md
-----
Noticed zipInstall isn't mentioned in the Settings.md. So added it.
> Add zip installation to experimental features section of Settings.md

- src/AppInstallerCLICore/Workflows/DownloadFlow.cpp
Related to https://github.com/microsoft/winget-pkgs/issues/79677
> Always fall back on msix streaming failure

- src/AppInstallerRepositoryCore/ARPCorrelationAlgorithms.cpp
VS is unhappy about this code with newer versions.
> Treat little numbers as big numbers

- src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj
- src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj
> Fix compliance issues by setting Newtonsoft.Json to recommended version

- src/AppInstallerCLICore/Workflows/InstallFlow.cpp
Reverts microsoft/winget-cli#2660
> Revert "Get arguments when using archive type package"

- src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp
Tested locally that after passing in --silent, there is no toast notification.
> Disable toast notification for silent mode for MSStore type installation

- azure-pipelines.yml
- src/PureLib/PureLib.vcxproj
Resolves build issues related to BinSkim for PureLib.
> Add spectre configuration for PureLib

- doc/Settings.md
- schemas/JSON/settings/settings.schema.0.2.json
- src/AppInstallerCLICore/Workflows/ArchiveFlow.cpp
- src/AppInstallerCLICore/Workflows/InstallFlow.cpp
- src/AppInstallerCLIE2ETests/BaseCommand.cs
- src/AppInstallerCLIE2ETests/InstallCommand.cs
- src/AppInstallerCLITests/WorkFlow.cpp
- src/AppInstallerCommonCore/ExperimentalFeature.cpp
- src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h
- src/AppInstallerCommonCore/Public/winget/UserSettings.h
- src/AppInstallerCommonCore/UserSettings.cpp
Removes all code related to the zip install feature as experimental in preparation for a stable release.
> Make zip feature stable

- Localization/Policies/de-DE/DesktopAppInstaller.adml
- Localization/Policies/es-ES/DesktopAppInstaller.adml
- Localization/Policies/fr-FR/DesktopAppInstaller.adml
- Localization/Policies/it-IT/DesktopAppInstaller.adml
- Localization/Policies/ja-JP/DesktopAppInstaller.adml
- Localization/Policies/ko-KR/DesktopAppInstaller.adml
- Localization/Policies/pt-BR/DesktopAppInstaller.adml
- Localization/Policies/ru-RU/DesktopAppInstaller.adml
- Localization/Policies/zh-CN/DesktopAppInstaller.adml
- Localization/Policies/zh-TW/DesktopAppInstaller.adml
- Localization/Resources/de-DE/winget.resw
- Localization/Resources/es-ES/winget.resw
- Localization/Resources/fr-FR/winget.resw
- Localization/Resources/it-IT/winget.resw
- Localization/Resources/ja-JP/winget.resw
- Localization/Resources/ko-KR/winget.resw
- Localization/Resources/pt-BR/winget.resw
- Localization/Resources/ru-RU/winget.resw
- Localization/Resources/zh-CN/winget.resw
- Localization/Resources/zh-TW/winget.resw
Pull in the latest localized strings
> Update localized strings

- src/PowerShell/Microsoft.WinGet.Client/Helpers/ComObjectFactory.cs
Suppresses a build error relating to a windows-only api.
> Suppress CA1416 warning #2

- src/binver/Update-BinVer.ps1
This will be used in internal release builds.
> UpdateBinVer script support for updating build version only

- src/binver/binver/version.h
Increment version from 1.4 to 1.5
> Bump version from 1.5

- doc/windows-package-manager-release-roadmap.md
- doc/windows/package-manager/package/manifest.md
- doc/windows/package-manager/package/windows-package-manager-policies.md
- doc/windows/package-manager/winget/index.md
Creating as draft for later merge
> Update Documentation for manifest 1.4

- src/AppInstallerCLICore/Workflows/SettingsFlow.cpp
- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
* Standardize winget capitalization in winget.resw
* Add placeholder to string for clarification which admin setting has been modified
-----
> Show which admin setting has been enabled/disabled in confirmation string

- src/AppInstallerCLITests/RestClient.cpp
- src/AppInstallerRepositoryCore/Rest/RestClient.cpp
> Add rest interface 1.4 to supported list

- src/AppInstallerCLI/AppInstallerCLI.vcxproj
> fix: remove extra space

- .github/ISSUE_TEMPLATE/Feature_Request.yml
> feat(template): update title + desc for feature request

- .github/ISSUE_TEMPLATE/Documentation_Issue.yml
> feat(template): update title + desc for docs report

- .github/ISSUE_TEMPLATE/Bug_Report.yml
-----
I made a typo in the commit, sorry about that.
> feat(template): update title + desc for bug report

- src/AppInstallerCommonCore/Runtime.cpp
Verified the issue #2740 repros before this change and issue was fixed after applying this change.
> Give admin access to temp folder

- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
As winget gets more usage, we'd like to down sampling the telemetry events.
> Down sampling telemetry events

- src/AppInstallerCLIE2ETests/Interop/InstallInterop.cs
- src/AppInstallerCLIE2ETests/TestData/Manifests/TestZipInstaller_PackageInstallerInfo.yaml
- src/Microsoft.Management.Deployment/Converters.cpp
- src/Microsoft.Management.Deployment/Converters.h
- src/Microsoft.Management.Deployment/PackageInstallerInfo.cpp
- src/Microsoft.Management.Deployment/PackageInstallerInfo.h
- src/Microsoft.Management.Deployment/PackageManager.idl
- src/Microsoft.Management.Deployment/PackageVersionInfo.cpp
- src/Microsoft.Management.Deployment/PackageVersionInfo.h
Changes: 
- Modify PackageManager.idl to add support for ElevationRequirement
> Add support for elevation requirement in COM

- src/AppInstallerCLICore/Workflows/PinFlow.cpp
> Fix order of pin labels

- src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
- src/Microsoft.Management.Configuration.Projection/Microsoft.Management.Configuration.Projection.csproj
- src/Microsoft.Management.Configuration.UnitTests/Helpers/TempFile.cs
- src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationDetailsTests.cs
- src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj
Move Microsoft.Management.Configuration projects to target 10.0.19041.0.
Fix UTs Microsoft.Management.Configuration flaky tests.
> Microsoft.Management.Configuration Windows target platform

- src/AppInstallerCLICore/Workflows/MSStoreInstallerHandler.cpp
> Fix typo in MSStore get entitlement log

- src/AppInstallerCLICore/Workflows/WorkflowBase.cpp
> Explicitly prevent fallthrough on OperationType

- src/Microsoft.Management.Deployment/PackageCatalogReference.cpp
> Make sure source agreements are initialized before checking

- src/ConfigurationRemotingServer/ConfigurationRemotingServer.csproj
- src/PowerShell/Microsoft.WinGet.Client/Microsoft.WinGet.Client.csproj
Our internal build had some issues not finding some files.
> Fix internal build

- doc/Settings.md
- doc/windows/package-manager/winget/settings.md
-----
This prevents a [404](https://github.com/microsoft/winget-cli/blob/master/privacy.md) when clicking "primary privacy statement" [here](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md) and [here](https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/winget/settings.md).
> fix PRIVACY.md links

- src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
- src/Microsoft.Management.Configuration.Processor/Properties/AssemblyInfo.cs
Due to the internal build setup, we need to manually set these attributes.
> Add manual platform attributes

- doc/windows/package-manager/winget/exitcodes.md
- doc/windows/package-manager/winget/returnCodes.md
This PR takes the friendly error messages from `Errors.cpp` and puts them into a table with the corresponding return response. 
Also related to -
* #3201
-----
> Add Table of Error Codes to Docs

- src/AppInstallerCLICore/Argument.cpp
- src/AppInstallerCLICore/Workflows/UpdateFlow.cpp
- src/AppInstallerRepositoryCore/PackageInstalledStatus.cpp
> Move HasData check to default installation location check only

- Localization/Resources/de-DE/winget.resw
- Localization/Resources/es-ES/winget.resw
- Localization/Resources/fr-FR/winget.resw
- Localization/Resources/it-IT/winget.resw
- Localization/Resources/ja-JP/winget.resw
- Localization/Resources/ko-KR/winget.resw
- Localization/Resources/pt-BR/winget.resw
- Localization/Resources/ru-RU/winget.resw
- Localization/Resources/zh-CN/winget.resw
- Localization/Resources/zh-TW/winget.resw
Update the localization files from the internal localization integration build.
> Update localization from build 2306.01001

- src/binver/binver/version.h
Increment winget client version from 1.5 to 1.6
> Bump version from 1.5 to 1.6

- .github/policies/moderatorTriggers.yml
> Add Breaking-Change label to comment triggers

- tools/CorrelationTestbed/Test-CorrelationInSandbox.ps1
> Force close sandbox server upon timeout

- schemas/JSON/manifests/v1.5.0/manifest.defaultLocale.1.5.0.json
- schemas/JSON/manifests/v1.5.0/manifest.locale.1.5.0.json
- schemas/JSON/manifests/v1.5.0/manifest.singleton.1.5.0.json
> Relax InstallationNotes max length

- src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj
- src/WindowsPackageManager/WindowsPackageManager.vcxproj
Add USE_PROD_CLSIDS to vcxprojs that need it.
> Add missing definitions to release builds

- src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj
- src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
Verified locally by restoring the solution on a clean environment.
> Fix Component Governace issue with System.Security.Cryptography.Xml

- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
This reverts commit 6bfc3d04c4a7f917815486fddcf1042c8ba1fb10.
We need to revert this change until those downstream are prepared.
> Revert "Down sampling (#2950)"

- src/AppInstallerCLICore/Workflows/DownloadFlow.cpp
-----
This proposes to fix issue #3558 by replacing the error message with a slightly more generic but already existing resource string.
> Replace download cancelled message with a localized message

- src/AppInstallerCLICore/Workflows/InstallFlow.cpp
- src/AppInstallerCLITests/RestInterface_1_6.cpp
- src/AppInstallerCLITests/TestData/MultiFileManifestV1_6/ManifestV1_6-MultiFile-Installer.yaml
- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer.h
- src/AppInstallerRepositoryCore/Rest/Schema/1_0/Json/ManifestDeserializer_1_0.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_1/Json/ManifestDeserializer_1_1.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_6/Json/ManifestDeserializer.h
- src/AppInstallerRepositoryCore/Rest/Schema/1_6/Json/ManifestDeserializer_1_6.cpp
Also a small change in logging.
> Improve rest client manifest parsing for upgrade behavior deny

- src/binver/binver/version.h
Increases the minor version from 6 to 7
> Bump client version from 1.6 to 1.7

- .github/actions/spelling/allow.txt
- SECURITY.md
-----
With https://github.com/microsoft/repo-templates/pull/13 merged, this new version of SECURITY.md can be also applied to this repository.
> Update SECURITY.md from 0.0.2 to 0.0.9

- src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp
> Add norestart to msi uninstall args

- .github/actions/spelling/expect.txt
- src/AppInstallerRepositoryCore/SourceList.cpp
Change the alternate URL as the older one is being deprecated.
> Change alternate url

- src/AppInstallerCommonCore/HttpStream/HttpClientWrapper.cpp
> Cherry pick 3645 to 1.6

- .github/actions/spelling/expect.txt
- src/AppInstallerRepositoryCore/SourceList.cpp
> Cherry pick 3646 to 1.6

- src/AppInstallerCLICore/Workflows/DependencyNodeProcessor.cpp
- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
> Fix localized strings output

- src/AppInstallerRepositoryCore/RepositorySource.cpp
- src/AppInstallerRepositoryCore/pch.h
> Cherry pick 3661 into 1.6

- .github/actions/spelling/expect.txt
- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
- src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
- src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h
- src/AppInstallerRepositoryCore/RepositorySource.cpp
- src/Microsoft.Management.Deployment/Helpers.cpp
- src/Microsoft.Management.Deployment/Helpers.h
- src/Microsoft.Management.Deployment/PackageCatalogReference.cpp
- src/Microsoft.Management.Deployment/PackageCatalogReference.h
- src/Microsoft.Management.Deployment/PackageManager.cpp
- src/Microsoft.Management.Deployment/PackageManager.h
- src/Microsoft.Management.Deployment/PackageManager.idl
- src/Microsoft.Management.Deployment/pch.h
> Cherry pick 3665 into 1.6

- src/AppInstallerCLICore/Workflows/DependencyNodeProcessor.cpp
- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
#3673 
cc @Johnmcpms / @ranm-msft
> Cherry pick 3673 into 1.6

- src/AppInstallerRepositoryCore/CompositeSource.cpp
- src/AppInstallerRepositoryCore/Public/winget/RepositorySource.h
- src/AppInstallerRepositoryCore/RepositorySource.cpp
- src/Microsoft.Management.Deployment/PackageCatalogReference.cpp
- src/Microsoft.Management.Deployment/PackageCatalogReference.h
- src/Microsoft.Management.Deployment/PackageManager.idl
> Cherry pick 3703

- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
- src/AppInstallerCommonCore/Public/AppInstallerTelemetry.h
- src/Microsoft.Management.Deployment/PackageManager.cpp
- src/Microsoft.Management.Deployment/PackageManager.h
> Cherry pick 3711 to 1.6

- src/AppInstallerCLITests/Sources.cpp
- src/AppInstallerRepositoryCore/SourcePolicy.cpp
> Cherry pick 3725 into 1.6

- src/AppInstallerCLICore/Argument.cpp
- src/AppInstallerCLICore/Argument.h
> Allow --accept-source-agreements with local manifests

- src/AppInstallerCLICore/Workflows/ShellExecuteInstallerHandler.cpp
Move the Windows Feature `dism.exe` calling code around and make the test hook return from the primary function.  This ensures that all code is being compiled when test hooks are enabled, and the test hooks are simple, early returns.
> Fix non-test hook code for Windows Feature

- src/JsonCppLib/JsonCppLib.vcxproj
> Cherry-Pick: Add missing condition for using toolset v143 when building JsonCppLib for arm (#3773)

- src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj
The control for switching between servers was not done previously.
> Fix OOP config helper

- .configurations/configuration.dsc.yaml
- schemas/JSON/configuration/configuration.schema.0.1.json
- schemas/JSON/configuration/configuration.schema.0.2.json
- descriptions were added to other schema properties
- minor grammar/punctuation fixes/changes were made
-----
> Configuration schema property descriptions added

- src/AppInstallerRepositoryCore/Microsoft/PredefinedInstalledSourceFactory.cpp
> Include framework packages during installed packages enumeration

- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp
> Restrict on agreement text only

- schemas/JSON/manifests/v1.6.0/manifest.defaultLocale.1.6.0.json
- schemas/JSON/manifests/v1.6.0/manifest.installer.1.6.0.json
- schemas/JSON/manifests/v1.6.0/manifest.locale.1.6.0.json
- schemas/JSON/manifests/v1.6.0/manifest.singleton.1.6.0.json
- schemas/JSON/manifests/v1.6.0/manifest.version.1.6.0.json
- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerCommonCore/Manifest/ManifestYamlPopulator.cpp
> Cherry-pick changes for nuget 1.7.3

- src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj
- src/WinGetUtil/WinGetUtil.vcxproj
Remove unnecessary debug flags to unblock utils nuget release
> Remove debug flags to unblock utils nuget release

- .github/workflows/similarissues.yml
Added an if statement to similarIssues.yml so that the logic can be updated to not show as 'failure' when no similar issue is found.
None
Small change only
> Update similarIssues.yml to not show 'fail' when no similar issues found 

- .github/workflows/similarissues.yml
Explicitly add issues read permissions to similar issues workflow for the minimum required access.
> Similar issues workflow explicit permission

- src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
- src/WinGetUtilInterop.UnitTests/APIUnitTests/SQLiteIndexUnitTests.cs
Updating dependency on System.Data.SqlClient due to a Component Governance alert
> Update dependency on System.Data.SqlClient

- src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj
- src/WinGetUtil/WinGetUtil.vcxproj
Cherry-pick c49f0a3fb50bf7750f7b6f6e48d8fd4c452abed8 "Remove unnecessary debug flags to unblock utils nuget release" for new 1.7.7 nuget
Actually to nuget branch...
> Remove debug flags to unblock utils nuget release (#4030)

- src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj
- src/WinGetUtil/WinGetUtil.vcxproj
Wrong branch :(
Reverts microsoft/winget-cli#4127
> Revert "Remove debug flags to unblock utils nuget release (#4030)"

- WinGetUtil.nuspec
- azure-pipelines.nuget.yml
Fix nuget pipeline for correct net standard version.
> Retarget to netstandard2.1

- WinGetUtil.nuspec
- azure-pipelines.nuget.yml
Cherry-pick #4130 to master
Fix nuget pipeline for correct net standard version.
> Retarget to netstandard2.1 (#4130)

- doc/windows-package-manager-release-roadmap.md
> Update links in Roadmap

- src/WinGetUtilInterop.UnitTests/ManifestUnitTest/V1ManifestReadTest.cs
- src/WinGetUtilInterop.UnitTests/TestCollateral/V1_7ManifestMerged.yaml
- src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj
- src/WinGetUtilInterop/Manifest/V1/InstallerSwitches.cs
- src/WinGetUtilInterop/Manifest/V1/Manifest.cs
- src/WinGetUtilInterop/Manifest/V1/ManifestInstaller.cs
> Add 1.7 manifest fields to WingetUtilsInterop

- src/Microsoft.Management.Configuration/ConfigurationProcessor.cpp
- src/Microsoft.Management.Configuration/ConfigurationSet.cpp
- src/Microsoft.Management.Configuration/ConfigurationSet.h
- src/Microsoft.Management.Configuration/Telemetry/Telemetry.cpp
- src/Microsoft.Management.Configuration/Telemetry/Telemetry.h
Validated by putting breakpoints and saw input hash passed in.
> Log configuration input hash in configuration summary telemetry

- doc/specs/#658 - WinGet Download.md
> Update WinGet Download spec with accurate PS cmdlet help

- .github/actions/spelling/expect.txt
- doc/troubleshooting/README.md
* #4187
* https://github.com/microsoft/winget-cli/issues/3832
* https://github.com/microsoft/winget-cli/issues/3706
* https://github.com/microsoft/winget-cli/issues/4117
-----
> Add Troubleshooting Step for CDN

- src/WinGetYamlFuzzing/OneFuzzConfig.json
Updates the OneFuzzConfig.json file with the corresponding pipeline id (630)
> Update fuzzing code coverage pipeline id

- src/binver/binver/version.h
> Increment version to 1.8

- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Microsoft.WinGet.Client.Engine.csproj
- src/PowerShell/Microsoft.WinGet.Client.Engine/Properties/Resources.Designer.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Properties/Resources.resx
> Update Repair-WinGetPackageManager with UiXaml 2.8 (#4218)

- src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Microsoft.WinGet.Client.Cmdlets.csproj
Cherry-pick from commit: b07d2ebb7d865f95320e2bc708a2d1efb2152c5a
> Copy semver.dll to direct dependencies (#4226)

- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
- Resolves #4208
-----
See https://github.com/microsoft/winget-cli/issues/4208#issuecomment-1981557092
> Fix xamlAsset value (powershell module)

- .github/policies/moderatorTriggers.yml
* Add most labels
* Allow closing and re-opening issues
* Allow resetting labels
* Synchronize moderator list with winget-pkgs
* Put label triggers in lexographical order
@denelon
-----
> Update Triage Triggers

- .github/policies/labelManagement.triageLabels.yml
- .github/policies/moderatorTriggers.yml
> Remove Needs-Triage when labels are applied

- .github/policies/labelManagement.triageLabels.yml
> Fix conflict with Issue Forms

- src/PowerShell/CommonFiles/PowerShellCmdlet.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
Fix PowerShellCmdlet (#4247)
Fix xamlAsset value (powershell module) (#4240)
> Cherry pick: Fix xamlAsset value (powershell module) (#4240) and Fix PowerShellCmdlet (#4247)

- .github/policies/moderatorTriggers.yml
> Add Trigger for Needs-Repro Label

- .github/workflows/similarissues.yml
Issue bot now includes info about the issue body, improving its accuracy.
- [ X] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
-----
> Update similarissues.yml to include body information as well

- src/AppInstallerCLITests/Sources.cpp
- src/AppInstallerRepositoryCore/SourceList.cpp
Cherry-pick commit: cf13dc241e5fc1b18f9eca7a47b2fb0d2178cbb3
> Ignore corrupted source data (#4291)

- .github/actions/spelling/allow.txt
- azure-pipelines.yml
- src/AppInstallerCLI.sln
- src/AppInstallerCLICore/Core.cpp
- src/AppInstallerCLICore/pch.h
- src/AppInstallerCommonCore/Debugging.cpp
- src/AppInstallerCommonCore/Public/winget/Debugging.h
- src/Microsoft.Management.Configuration.OutOfProc/Prepare-ConfigurationOOPTests.ps1
- src/WinGetServer/Utils.cpp
- src/WinGetServer/Utils.h
- src/WinGetServer/WinGetServerManualActivation_Client.cpp
- src/WinGetServer/WinMain.cpp
cherry-pick commit: 834806b5392c2f21f677135846e23eb3348812d9
> Better server start coordination (#4292)

- src/Xlang/UndockedRegFreeWinRT/src/UndockedRegFreeWinRT/UndockedRegFreeWinRT/typeresolution.cpp
> Cherry pick #4389 to 1.7

- src/PowerShell/Microsoft.WinGet.Client.Cmdlets/Resolver/ModuleInit.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/OperationWithProgressBase.cs
- src/PowerShell/Microsoft.WinGet.Configuration.Engine/Commands/ConfigurationCommand.cs
> Cherry pick #4392 to 1.7

- src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp
- src/Microsoft.Management.Configuration.UnitTests/Tests/OpenConfigurationSetTests.cs
> Make SecurityContext field name camelCase (#4433)

- src/AppInstallerCLICore/Workflows/DownloadFlow.cpp
> Remove Parent Directory when Empty

- cgmanifest.json
- src/SfsClient/SfsClient.vcxproj
- src/SfsClient/readme.md
- src/SfsClient/sfs-client/CMakeLists.txt
- src/SfsClient/sfs-client/samples/tool/SFSClientTool.cpp
Command used
```
git subtree pull -P src/SfsClient/sfs-client https://github.com/microsoft/sfs-client 1.0.0 --squash
```
> Update sfs-client to 1.0.0 release

- azure-pipelines.loc.yml
Moving from AppID+Secret to federated identity auth
> Update localization pipeline to new auth type

- azure-pipelines.loc.yml
Fix for #4532. Azure Pipeline does not like service connections to be specified with variables.
I swear this time I actually tested the pipeline...
> Fix loc pipeline service connection

- azure-pipelines.yml
- #4559 
-----
From [Run BinSkim](https://dev.azure.com/ms/winget-cli/_build/results?buildId=582538&view=logs&j=d4ea2893-dbfa-5202-65c3-8a2f8e9ac04c&t=d19b5f22-4e19-57a3-aa3c-69953199f198&l=11):
> ##[warning]* Please upgrade the version of this build task in your build to major version: 4. For more information, please see: [aka.ms/gdn-v1-deprecation](https://aka.ms/gdn-v1-deprecation)
-----
From [Publish Security Analysis Logs](https://dev.azure.com/ms/winget-cli/_build/results?buildId=582538&view=logs&j=d4ea2893-dbfa-5202-65c3-8a2f8e9ac04c&t=d8c28f17-50c1-5a1f-2b5f-a5aaa9eb5518&l=11):
> ##[warning]* Please upgrade the version of this build task in your build to major version: 3. For more information, please see: https://aka.ms/gdn-v1-deprecation
-----
> Update Pipeline Component Versions

- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerCommonCore/Manifest/YamlWriter.cpp
Fixes #4497
Added unit tests and manually validated the fix.
> Fix export manifest with multiple locales

- Localization/Policies/de-DE/DesktopAppInstaller.adml
- Localization/Policies/es-ES/DesktopAppInstaller.adml
- Localization/Policies/fr-FR/DesktopAppInstaller.adml
- Localization/Policies/it-IT/DesktopAppInstaller.adml
- Localization/Policies/ja-JP/DesktopAppInstaller.adml
- Localization/Policies/ko-KR/DesktopAppInstaller.adml
- Localization/Policies/pt-BR/DesktopAppInstaller.adml
- Localization/Policies/ru-RU/DesktopAppInstaller.adml
- Localization/Policies/zh-CN/DesktopAppInstaller.adml
- Localization/Policies/zh-TW/DesktopAppInstaller.adml
- Localization/Resources/de-DE/winget.resw
- Localization/Resources/es-ES/winget.resw
- Localization/Resources/fr-FR/winget.resw
- Localization/Resources/it-IT/winget.resw
- Localization/Resources/ja-JP/winget.resw
- Localization/Resources/ko-KR/winget.resw
- Localization/Resources/pt-BR/winget.resw
- Localization/Resources/ru-RU/winget.resw
- Localization/Resources/zh-CN/winget.resw
- Localization/Resources/zh-TW/winget.resw
Pulls in latest patch for strings in preparation for 1.8 release.
> Apply latest patch for localized strings

- cgmanifest.json
- src/YamlCppLib/libyaml/.github/workflows/dist.yaml
- src/YamlCppLib/libyaml/.github/workflows/main.yml
- src/YamlCppLib/libyaml/.gitignore
- src/YamlCppLib/libyaml/.makefile
- src/YamlCppLib/libyaml/Makefile.am
- src/YamlCppLib/libyaml/examples/strings.yaml
- src/YamlCppLib/libyaml/include/yaml.h
- src/YamlCppLib/libyaml/pkg/ReadMe.md
- src/YamlCppLib/libyaml/pkg/docker/.gitignore
- src/YamlCppLib/libyaml/pkg/docker/Dockerfile
- src/YamlCppLib/libyaml/pkg/docker/Makefile
- src/YamlCppLib/libyaml/pkg/docker/output/ReadMe
- src/YamlCppLib/libyaml/pkg/docker/scripts/libyaml-dist.sh
- src/YamlCppLib/libyaml/src/parser.c
- src/YamlCppLib/libyaml/src/scanner.c
- src/YamlCppLib/libyaml/tests/run-emitter-test-suite.c
- src/YamlCppLib/libyaml/tests/run-parser-test-suite.c
- src/YamlCppLib/libyaml/tests/run-parser.c
- src/YamlCppLib/libyaml/tests/test-reader.c
- src/YamlCppLib/readme.md
Component governance fix: update libyaml
> Cherry-pick Update libyaml (#4583)

- doc/Settings.md
- schemas/JSON/settings/settings.schema.0.2.json
- src/AppInstallerCommonCore/ExperimentalFeature.cpp
- src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h
- src/AppInstallerCommonCore/Public/winget/UserSettings.h
- src/AppInstallerCommonCore/UserSettings.cpp
- src/AppInstallerRepositoryCore/Microsoft/PreIndexedPackageSourceFactory.cpp
Remove the experimental state from index v2.
> Remove experimental from index v2

- .gitignore
Add `AnyCPU` to the build artifact ignores.
> Add AnyCPU to .gitignore

- src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
Upgrade System.Formats.Asn1 from 6.0.0 to 6.0.1
> Fix Component Governance

- src/SfsClient/readme.md
- src/SfsClient/sfs-client/.github/dependabot.yml
- src/SfsClient/sfs-client/cgmanifest.json
- src/SfsClient/sfs-client/client/tests/functional/details/CurlConnectionTests.cpp
- src/SfsClient/sfs-client/client/tests/util/TestHelper.cpp
- src/SfsClient/sfs-client/samples/integration-do-client/IntegrationDOClient.cpp
- src/SfsClient/sfs-client/samples/tool/SFSClientTool.cpp
- src/SfsClient/sfs-client/scripts/pip.requirements.txt
- src/SfsClient/sfs-client/vcpkg.json
Pulls in the change to address the component governance issue for curl 8.4.0
Related PR that fixes this issue:
https://github.com/microsoft/sfs-client/pull/205
> Pull in latest SFSClient

- .github/actions/spelling/allow.txt
- .github/actions/spelling/expect.txt
- src/AppInstallerCommonCore/NetworkSettings.cpp
> Fix downloader selection

- src/AppInstallerCLI.sln
Add a project dependency in the solution for `Microsoft.Management.Deployment.OutOfProc` on `WinGetServer`.
> Add missing solution dependency

- src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp
Adds diagnostics to the dynamic factory.
Manually confirmed that diagnostics now flow out of dynamic factory.
> Add diagnostics to dynamic factory

- src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj
Update dependencies on CLIE2ETests projects to fix CG alerts
> Fix Component Governance issues

- src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj
- src/AppInstallerCLIE2ETests/ConfigureTestCommand.cs
- src/AppInstallerCLIE2ETests/Helpers/TestCommon.cs
- src/AppInstallerCLIE2ETests/PowerShell/PowerShellHost.cs
Fixes dotnet restore errors during build by updating to the latest patch for affected packages.
> Update nuget for E2E test project 

- src/WinGetYamlFuzzing/OneFuzzConfig.json
Updates to the correct area path.
> Update fuzzing template area path

- Localization/Resources/de-DE/winget.resw
- Localization/Resources/es-ES/winget.resw
- Localization/Resources/fr-FR/winget.resw
- Localization/Resources/it-IT/winget.resw
- Localization/Resources/ja-JP/winget.resw
- Localization/Resources/ko-KR/winget.resw
- Localization/Resources/pt-BR/winget.resw
- Localization/Resources/ru-RU/winget.resw
- Localization/Resources/zh-CN/winget.resw
- Localization/Resources/zh-TW/winget.resw
Applies the latest patch for updated localized strings.
> Pull in latest localized strings

- src/binver/binver/version.h
In coded lines, the clock ticks on,
From dawn to dusk, until it’s gone.
Versions rise with whispered lore,
From simple roots, to something more.
Bugs are squashed, new feats take flight,
Updates cascade in endless light.
Yet in each change, a piece remains,
A bit of history in the gains.
Time’s passage
[A series of tokens deemed reasonably likely by an artificial neural network when provided with some other tokens generated by a biological neural network.]
> Update minor version

- src/AppInstallerCLIE2ETests/AppInstallerCLIE2ETests.csproj
- src/Microsoft.Management.Configuration.Processor/Microsoft.Management.Configuration.Processor.csproj
Update dependency System.IO.Packaging due to CVE-2024-43484, CVE-2024-43483
> Update package with CVEs

- src/AppInstallerCLITests/SQLiteIndex.cpp
- src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.cpp
- src/AppInstallerRepositoryCore/Microsoft/SQLiteIndex.h
- src/AppInstallerRepositoryCore/Microsoft/Schema/1_5/Interface.h
- src/AppInstallerRepositoryCore/Microsoft/Schema/1_5/Interface_1_5.cpp
- src/WinGetUtil/Exports.cpp
- src/WinGetUtil/Source.def
- src/WinGetUtil/WinGetUtil.h
- src/WinGetUtilInterop.UnitTests/APIUnitTests/SQLiteIndexUnitTests.cs
- src/WinGetUtilInterop/Api/WinGetSQLiteIndex.cs
- src/WinGetUtilInterop/Interfaces/IWinGetSQLiteIndex.cs
Removes these commits from the release 1.9 branch
> Revert ARP error change and AddOrUpdate return bool in 1.9

- src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
- src/AppInstallerCLITests/AppInstallerCLITests.vcxproj.filters
- src/AppInstallerCLITests/RestClient.cpp
- src/AppInstallerCLITests/RestInterface_1_9.cpp
- src/AppInstallerCLITests/YamlManifest.cpp
- src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj
- src/AppInstallerRepositoryCore/AppInstallerRepositoryCore.vcxproj.filters
- src/AppInstallerRepositoryCore/ManifestJSONParser.cpp
- src/AppInstallerRepositoryCore/Rest/RestClient.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_9/Interface.h
- src/AppInstallerRepositoryCore/Rest/Schema/1_9/Json/ManifestDeserializer.h
- src/AppInstallerRepositoryCore/Rest/Schema/1_9/Json/ManifestDeserializer_1_9.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/1_9/RestInterface_1_9.cpp
- src/AppInstallerRepositoryCore/Rest/Schema/CommonRestConstants.h
- src/WinGetUtilInterop.UnitTests/ManifestUnitTest/V1ManifestReadTest.cs
- src/WinGetUtilInterop.UnitTests/TestCollateral/V1_9ManifestMerged.yaml
- src/WinGetUtilInterop.UnitTests/WinGetUtilInterop.UnitTests.csproj
- src/WinGetUtilInterop/Manifest/V1/Manifest.cs
- src/WinGetUtilInterop/Manifest/V1/ManifestInstaller.cs
> Add support for 1.9 manifest in rest source parsing and winget utils interop

- src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/CliCommand.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/UserSettingsCommand.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/VersionCommand.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Commands/WinGetPackageManagerCommand.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Common/WinGetIntegrity.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Extensions/ReleaseExtensions.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/AppxModuleHelper.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/PackageDependency.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/WinGetVersion.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/WingetCLIWrapper.cs
- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/WingetDependencies.cs
- src/PowerShell/scripts/Initialize-LocalWinGetModules.ps1
Cp to fix repair-wingetpackagemanager
> Fix Repair-WinGetPackageManager cmdlet by retrieving dependencies from GitHub assets #4923

- src/vcpkg.json
See https://curl.se/docs/CVE-2024-9681.html
> Update curl dependency due to CVE-2024-9681

- src/AppInstallerCommonCore/AppInstallerTelemetry.cpp
Reduce the `RepairFailure` event to a measure.
> Change RepairFailure telemetry event to measure

- doc/Settings.md
> Winget cli

- schemas/JSON/settings/settings.schema.0.2.json
-----
When inspecting the schema for settings, the default value for `ConfigureBehavior` is missing. This PR adds the default value.
> Add default value for `ConfigureBehavior`

- doc/Settings.md
-----
Adds `maxResumes` to docs. This relates to #3165
> Add maxResumes to list

- samples/MinimalCallers/C#/Configuration-InProc/C#_Configuration_InProc.csproj
> Update dependencies with CVEs in sample projects

- Localization/Policies/de-DE/DesktopAppInstaller.adml
- Localization/Policies/fr-FR/DesktopAppInstaller.adml
- Localization/Resources/de-DE/winget.resw
- Localization/Resources/es-ES/winget.resw
- Localization/Resources/fr-FR/winget.resw
- Localization/Resources/it-IT/winget.resw
- Localization/Resources/ja-JP/winget.resw
- Localization/Resources/ko-KR/winget.resw
- Localization/Resources/pt-BR/winget.resw
- Localization/Resources/ru-RU/winget.resw
- Localization/Resources/zh-CN/winget.resw
- Localization/Resources/zh-TW/winget.resw
> Update localized strings with latest patch

- Localization/Resources/de-DE/winget.resw
- Localization/Resources/es-ES/winget.resw
- Localization/Resources/fr-FR/winget.resw
- Localization/Resources/it-IT/winget.resw
- Localization/Resources/ja-JP/winget.resw
- Localization/Resources/ko-KR/winget.resw
- Localization/Resources/pt-BR/winget.resw
- Localization/Resources/ru-RU/winget.resw
- Localization/Resources/zh-CN/winget.resw
- Localization/Resources/zh-TW/winget.resw
This PR was created by a script that automates running the loc pipeline, downloading and applying the patch, and creating the PR here. See internal PR 12220802 for the actual script :)
> Apply latest loc patch

- src/binver/binver/version.h
> Bump version to 1.11

- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
> Completion of missing `}`

- src/AppInstallerCommonCore/HttpClientHelper.cpp
Some of the `http_exception`s coming through this function don't have error codes set.  Throwing that success code causes WIL to fail fast.
Forced an exception without a code to be thrown (force the Store DNS to map to another web server so that the certificate did not match).
> Don't let unset error codes be thrown

- src/AppInstallerCLIE2ETests/InstallCommand.cs
> Fix e2e test failure caused by message change

- azure-pipelines.yml
Make the pipelines build multiple projects in parallel. In the few tests I did, there wasn't an improvement larger than the typical variability there is but there were no issues either, so I'm just gambling that it may bring some benefit with no proof 🤷‍♀️
> Build in parallel

- src/AppInstallerCLICore/ConfigurationDynamicRuntimeFactory.cpp
- src/Microsoft.Management.Configuration.UnitTests/Tests/ConfigurationMixedElevationTests.cs
Added unit test. Manually validated as well.
> Fix DynamicProcessor crash when working on individual units without a set

- src/AppInstallerCLI/AppInstallerCLI.vcxproj
- src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
- src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj
- src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj.filters
- src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj
- src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj
- src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj.filters
- src/Microsoft.Management.Deployment.OutOfProc/Microsoft.Management.Deployment.OutOfProc.vcxproj
- src/Microsoft.Management.Deployment.OutOfProc/Microsoft.Management.Deployment.OutOfProc.vcxproj.filters
- src/WinGetServer/WinGetServer.vcxproj
- src/WinGetUtil/WinGetUtil.vcxproj
- src/WindowsPackageManager/WindowsPackageManager.vcxproj
Enable shadow stack support in all native binaries.
BinSkim is marking this as needed in one native binary; adding it to all of them.
> Enable shadow stack

- src/AppInstallerCLI/AppInstallerCLI.vcxproj
- src/AppInstallerCLITests/AppInstallerCLITests.vcxproj
- src/Microsoft.Management.Configuration.OutOfProc/Microsoft.Management.Configuration.OutOfProc.vcxproj
- src/Microsoft.Management.Configuration/Microsoft.Management.Configuration.vcxproj
- src/Microsoft.Management.Deployment.InProc/Microsoft.Management.Deployment.InProc.vcxproj
- src/Microsoft.Management.Deployment.OutOfProc/Microsoft.Management.Deployment.OutOfProc.vcxproj
- src/WinGetServer/WinGetServer.vcxproj
- src/WinGetUtil/WinGetUtil.vcxproj
- src/WindowsPackageManager/WindowsPackageManager.vcxproj
CET compatible is not supported by arm64 builds and will cause build failure.
Also removed the entries in AppinstallerTests, I'll send a pr to exclude test binaries from binskim.
> Fix arm64 builds

- src/vcpkg.json
Update curl to 1.12.1 to address CVEs:
* CVE-2025-0167
* CVE-2025-0665
* CVE-2025-0725
> Update curl to 1.12.1

- .github/actions/spelling/expect.txt
- src/Microsoft.Management.Configuration.Projection/Microsoft.Management.Configuration.Projection.csproj
- src/Microsoft.Management.Deployment.CsWinRTProjection/Microsoft.Management.Deployment.CsWinRTProjection.csproj
Disable the assembly info override in the internal build.
> Disable assembly info override

- src/VcpkgCustomTriplets/arm64-release-static.cmake
- src/VcpkgCustomTriplets/arm64-release.cmake
- src/VcpkgCustomTriplets/arm64.cmake
- src/VcpkgCustomTriplets/common.cmake
- src/VcpkgCustomTriplets/x64-release-static.cmake
- src/VcpkgCustomTriplets/x64-release.cmake
- src/VcpkgCustomTriplets/x64.cmake
- src/VcpkgCustomTriplets/x86-release-static.cmake
- src/VcpkgCustomTriplets/x86-release.cmake
- src/VcpkgCustomTriplets/x86.cmake
> Fix debug build with vcpkg

- src/Microsoft.Management.Configuration.Processor/DSCv3/Helpers/ProcessorSettings.cs
Until DSCv3 support is not experimental, allow the preview build to be found automatically.
> Allow preview dsc while experimental

- src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp
Merge after https://github.com/microsoft/winget-cli/pull/5443
> Elevated for exported Microsoft.Windows.Settings

- .github/actions/spelling/expect.txt
- src/WinGetYamlFuzzing/OneFuzzConfig.json
> Fix fuzzing job path

- cgmanifest.json
> Missing comma in cgmanifest.json

- doc/Settings.md
- schemas/JSON/settings/settings.schema.0.2.json
- src/AppInstallerCLICore/Commands/DscCommandBase.cpp
- src/AppInstallerCLICore/ConfigurationSetProcessorFactoryRemoting.cpp
- src/AppInstallerCLICore/ConfigureExportCommand.h
- src/AppInstallerCLICore/Workflows/ConfigurationFlow.cpp
- src/AppInstallerCLIE2ETests/ConfigureCommand.cs
- src/AppInstallerCLIE2ETests/ConfigureExportCommand.cs
- src/AppInstallerCLIE2ETests/ConfigureShowCommand.cs
- src/AppInstallerCLIE2ETests/ConfigureTestCommand.cs
- src/AppInstallerCLIE2ETests/DSCv3AdminSettingsResourceCommand.cs
- src/AppInstallerCLIE2ETests/DSCv3PackageResourceCommand.cs
- src/AppInstallerCLIE2ETests/DSCv3SourceResourceCommand.cs
- src/AppInstallerCLIE2ETests/DSCv3UserSettingsFileResourceCommand.cs
- src/AppInstallerCommonCore/ExperimentalFeature.cpp
- src/AppInstallerCommonCore/Public/winget/ExperimentalFeature.h
- src/AppInstallerCommonCore/Public/winget/UserSettings.h
- src/AppInstallerCommonCore/UserSettings.cpp
- src/PowerShell/tests/RunTests.ps1
Move the `dsc3` and `configureExport` features to stable.
> Make dsc3 and export experimentals stable

- src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw
Change long descriptions for their primary use in DSC manifest.
> Update DSC command descriptions

- azure-pipelines.loc.yml
I didn't remember that localization is so nice we do it twice
See #5533
> Update the other TDBuild task

- src/PowerShell/Microsoft.WinGet.Client.Engine/Helpers/ManagementDeploymentFactory.cs
Call `CoAllowSetForegroundWindow` from the PS module to prevent/reduce instances of the UAC prompt being launched but not foreground.
> Allow set foreground from PS

- src/AppInstallerCLICore/CompletionData.cpp
[CompletionData.cpp](cci:7://file:///c:/Users/T2430514/Downloads/winget-cli/src/AppInstallerCLICore/CompletionData.cpp:0:0-0:0) passed a potentially negative `char` to `std::isspace`, invoking undefined behaviour on non-ASCII input (signed `char` platforms). This occasionally caused crashes or incorrect cursor repositioning when autocompleting commands containing UTF-8 characters.
The character is now explicitly cast to `unsigned char` before the `std::isspace` check:
```cpp
!std::isspace(static_cast<unsigned char>(commandLine[cursor - 1]))
```
This aligns with standard C++ guidance and makes the completion logic robust across all locales.
> Undefined-behaviour fix: safely call std::isspace in CompletionData

- doc/ReleaseNotes.md
- #5585
When I rebased the above PR, I missed the commit which updated the release notes document. This PR corrects that so @florelis doesn't yell at me.
-----
> Update release notes for BOM Handling

- src/Directory.Packages.props
- src/WinGetMCPServer/Exceptions/ToolResponseException.cs
- src/WinGetMCPServer/Response/PackageResponse.cs
- src/WinGetMCPServer/Response/ToolResponse.cs
- src/WinGetMCPServer/WingetPackageTools.cs
Update to the latest nuget available for the C# MCP SDK.
> Update to latest MCP nuget

- doc/ReleaseNotes.md
> Update release notes to mention WinUI dependency change

- src/Directory.Build.props
Implement @florelis suggestion from #5749.
> Improve shared props layout

- .github/workflows/automatic-issue-deduplication.yml
> Change label_as_duplicate to false in workflow
